export default defineEventHandler((event) => {
    const data = [
        {
            "ListName": "中國新說唱",
            "SongList": [
                {
                    "SongTitle": "隆裡電絲",
                    "SongID": "q04lzMnSaqU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=q04lzMnSaqU&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=q04lzMnSaqU&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "中國說唱巔峰對決 第四期",
                    "ArtistID": "MPREb_eSWNLyX2bYP",
                    "ArtistMusicUrl": "https://music.youtube.com/browse/MPREb_eSWNLyX2bYP",
                    "ArtistUrl": "https://youtube.com/browse/MPREb_eSWNLyX2bYP",
                    "time": "3:40",
                    "second": 220
                },
                {
                    "SongTitle": "隆裡電絲",
                    "SongID": "q04lzMnSaqU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=q04lzMnSaqU&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=q04lzMnSaqU&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "中國說唱巔峰對決 第四期",
                    "ArtistID": "MPREb_eSWNLyX2bYP",
                    "ArtistMusicUrl": "https://music.youtube.com/browse/MPREb_eSWNLyX2bYP",
                    "ArtistUrl": "https://youtube.com/browse/MPREb_eSWNLyX2bYP",
                    "time": "3:40",
                    "second": 220
                },
                {
                    "SongTitle": "危险派对",
                    "SongID": "xEifHCxChyE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=xEifHCxChyE&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=xEifHCxChyE&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "危险派对",
                    "ArtistID": "MPREb_avp2ZA9PIjG",
                    "ArtistMusicUrl": "https://music.youtube.com/browse/MPREb_avp2ZA9PIjG",
                    "ArtistUrl": "https://youtube.com/browse/MPREb_avp2ZA9PIjG",
                    "time": "3:01",
                    "second": 181
                },
                {
                    "SongTitle": "PG One - 都是你 \"All Of You\" feat. h3R3 (Lyric Video)",
                    "SongID": "x-SVAkOGfNY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=x-SVAkOGfNY&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=x-SVAkOGfNY&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "PG One",
                    "ArtistID": "UCJjYbjaAD0JWAcOA0IPDdEA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCJjYbjaAD0JWAcOA0IPDdEA",
                    "ArtistUrl": "https://youtube.com/channel/UCJjYbjaAD0JWAcOA0IPDdEA",
                    "time": "3:12",
                    "second": 192
                },
                {
                    "SongTitle": "髒藝術家",
                    "SongID": "_WSMUBOFRkI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=_WSMUBOFRkI&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=_WSMUBOFRkI&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "髒藝術家",
                    "ArtistID": "MPREb_cP8AWGuwWGo",
                    "ArtistMusicUrl": "https://music.youtube.com/browse/MPREb_cP8AWGuwWGo",
                    "ArtistUrl": "https://youtube.com/browse/MPREb_cP8AWGuwWGo",
                    "time": "3:25",
                    "second": 205
                },
                {
                    "SongTitle": "不用去猜 (Jazz Version)",
                    "SongID": "_l7XHnaC1tU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=_l7XHnaC1tU&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=_l7XHnaC1tU&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Jony J",
                    "ArtistID": "UCaIDelQQ-oSIOwh9wO3lRjw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCaIDelQQ-oSIOwh9wO3lRjw",
                    "ArtistUrl": "https://youtube.com/channel/UCaIDelQQ-oSIOwh9wO3lRjw",
                    "time": "3:34",
                    "second": 214
                },
                {
                    "SongTitle": "五百二十赫兹",
                    "SongID": "onpuXrKQZ8Q",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=onpuXrKQZ8Q&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=onpuXrKQZ8Q&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Capper",
                    "ArtistID": "UCe6tJ55jn8FY8Haix83KjuA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCe6tJ55jn8FY8Haix83KjuA",
                    "ArtistUrl": "https://youtube.com/channel/UCe6tJ55jn8FY8Haix83KjuA",
                    "time": "3:07",
                    "second": 187
                },
                {
                    "SongTitle": "一席之地",
                    "SongID": "5h0vro8f87Y",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=5h0vro8f87Y&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=5h0vro8f87Y&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "中國說唱巔峰對決 第五期",
                    "ArtistID": "MPREb_oDfV6dqTbyL",
                    "ArtistMusicUrl": "https://music.youtube.com/browse/MPREb_oDfV6dqTbyL",
                    "ArtistUrl": "https://youtube.com/browse/MPREb_oDfV6dqTbyL",
                    "time": "4:47",
                    "second": 287
                },
                {
                    "SongTitle": "不得不撒",
                    "SongID": "oGq10pLSnQc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=oGq10pLSnQc&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=oGq10pLSnQc&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "中國說唱巔峰對決 第六期",
                    "ArtistID": "MPREb_Tr0D9oiQWeL",
                    "ArtistMusicUrl": "https://music.youtube.com/browse/MPREb_Tr0D9oiQWeL",
                    "ArtistUrl": "https://youtube.com/browse/MPREb_Tr0D9oiQWeL",
                    "time": "4:28",
                    "second": 268
                },
                {
                    "SongTitle": "別怕變老",
                    "SongID": "g4Fdmycj39k",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=g4Fdmycj39k&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=g4Fdmycj39k&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "艾熱AIR",
                    "ArtistID": "UC1qxGNk1QGGOvyn5aFg28WQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC1qxGNk1QGGOvyn5aFg28WQ",
                    "ArtistUrl": "https://youtube.com/channel/UC1qxGNk1QGGOvyn5aFg28WQ",
                    "time": "4:09",
                    "second": 249
                },
                {
                    "SongTitle": "少数派报告",
                    "SongID": "dMfBNvJkafs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=dMfBNvJkafs&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=dMfBNvJkafs&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Tizzy T",
                    "ArtistID": "UCrC0V-DmDZrzr4L1J5kOjLQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCrC0V-DmDZrzr4L1J5kOjLQ",
                    "ArtistUrl": "https://youtube.com/channel/UCrC0V-DmDZrzr4L1J5kOjLQ",
                    "time": "4:54",
                    "second": 294
                },
                {
                    "SongTitle": "纵容",
                    "SongID": "P2t5BWpRiDY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=P2t5BWpRiDY&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=P2t5BWpRiDY&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Capper",
                    "ArtistID": "UCe6tJ55jn8FY8Haix83KjuA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCe6tJ55jn8FY8Haix83KjuA",
                    "ArtistUrl": "https://youtube.com/channel/UCe6tJ55jn8FY8Haix83KjuA",
                    "time": "3:19",
                    "second": 199
                },
                {
                    "SongTitle": "麒麟",
                    "SongID": "qf-HqgxIotA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=qf-HqgxIotA&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=qf-HqgxIotA&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "早安",
                    "ArtistID": "UCN-fpTjyhmJ-op23b_hyuuw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCN-fpTjyhmJ-op23b_hyuuw",
                    "ArtistUrl": "https://youtube.com/channel/UCN-fpTjyhmJ-op23b_hyuuw",
                    "time": "3:09",
                    "second": 189
                },
                {
                    "SongTitle": "清風調",
                    "SongID": "UAFoOdwYS8w",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=UAFoOdwYS8w&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=UAFoOdwYS8w&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "中國說唱巔峰對決 第一期",
                    "ArtistID": "MPREb_U8TxL3yEdvX",
                    "ArtistMusicUrl": "https://music.youtube.com/browse/MPREb_U8TxL3yEdvX",
                    "ArtistUrl": "https://youtube.com/browse/MPREb_U8TxL3yEdvX",
                    "time": "3:43",
                    "second": 223
                },
                {
                    "SongTitle": "无人区玫瑰",
                    "SongID": "M7ZijOfuhCc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=M7ZijOfuhCc&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=M7ZijOfuhCc&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Capper",
                    "ArtistID": "UCe6tJ55jn8FY8Haix83KjuA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCe6tJ55jn8FY8Haix83KjuA",
                    "ArtistUrl": "https://youtube.com/channel/UCe6tJ55jn8FY8Haix83KjuA",
                    "time": "3:36",
                    "second": 216
                },
                {
                    "SongTitle": "阿司匹林",
                    "SongID": "o1sQ2kTKUB0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=o1sQ2kTKUB0&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=o1sQ2kTKUB0&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "王以太",
                    "ArtistID": "UCmfq2-6nkZFvS5LYtshQmEw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCmfq2-6nkZFvS5LYtshQmEw",
                    "ArtistUrl": "https://youtube.com/channel/UCmfq2-6nkZFvS5LYtshQmEw",
                    "time": "3:23",
                    "second": 203
                },
                {
                    "SongTitle": "雪 Distance (合作演出：罗言)",
                    "SongID": "T0GMi2IzhD4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=T0GMi2IzhD4&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=T0GMi2IzhD4&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Capper",
                    "ArtistID": "UCe6tJ55jn8FY8Haix83KjuA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCe6tJ55jn8FY8Haix83KjuA",
                    "ArtistUrl": "https://youtube.com/channel/UCe6tJ55jn8FY8Haix83KjuA",
                    "time": "2:46",
                    "second": 166
                },
                {
                    "SongTitle": "除了說唱我什麼都不會",
                    "SongID": "ZTE39TXVWl8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ZTE39TXVWl8&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=ZTE39TXVWl8&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "MC HotDog熱狗",
                    "ArtistID": "UCW3Q3F5SByAWsYtRRFIMuNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCW3Q3F5SByAWsYtRRFIMuNA",
                    "ArtistUrl": "https://youtube.com/channel/UCW3Q3F5SByAWsYtRRFIMuNA",
                    "time": "3:36",
                    "second": 216
                },
                {
                    "SongTitle": "🌊Jony-J / 满舒克 🌊 ：LOST 🌕 Lyrics Video 🌕",
                    "SongID": "hLgtoogc69U",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=hLgtoogc69U&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=hLgtoogc69U&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "ZHONG.TV",
                    "ArtistID": "UCYpaEt_D5OB2aisQvNmPWrw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCYpaEt_D5OB2aisQvNmPWrw",
                    "ArtistUrl": "https://youtube.com/channel/UCYpaEt_D5OB2aisQvNmPWrw",
                    "time": "4:15",
                    "second": 255
                },
                {
                    "SongTitle": "人間天堂",
                    "SongID": "FSauBG2tWGs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=FSauBG2tWGs&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=FSauBG2tWGs&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "王以太",
                    "ArtistID": "UCmfq2-6nkZFvS5LYtshQmEw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCmfq2-6nkZFvS5LYtshQmEw",
                    "ArtistUrl": "https://youtube.com/channel/UCmfq2-6nkZFvS5LYtshQmEw",
                    "time": "3:28",
                    "second": 208
                },
                {
                    "SongTitle": "Sorry",
                    "SongID": "5scZTplmET0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=5scZTplmET0&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=5scZTplmET0&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "艾福杰尼",
                    "ArtistID": "UC6baW2EqmOWGSiKKU28K9zQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC6baW2EqmOWGSiKKU28K9zQ",
                    "ArtistUrl": "https://youtube.com/channel/UC6baW2EqmOWGSiKKU28K9zQ",
                    "time": "5:08",
                    "second": 308
                },
                {
                    "SongTitle": "若即若離",
                    "SongID": "HYWiQ_dV2sY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=HYWiQ_dV2sY&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=HYWiQ_dV2sY&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "K!ddingboi",
                    "ArtistID": "UCnH5EE2FTsS9gVQXhYrKCcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCnH5EE2FTsS9gVQXhYrKCcg",
                    "ArtistUrl": "https://youtube.com/channel/UCnH5EE2FTsS9gVQXhYrKCcg",
                    "time": "4:42",
                    "second": 282
                },
                {
                    "SongTitle": "一席之地Cypher",
                    "SongID": "lus1klcvLd0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=lus1klcvLd0&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=lus1klcvLd0&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "中國說唱巔峰對決 第六期",
                    "ArtistID": "MPREb_Tr0D9oiQWeL",
                    "ArtistMusicUrl": "https://music.youtube.com/browse/MPREb_Tr0D9oiQWeL",
                    "ArtistUrl": "https://youtube.com/browse/MPREb_Tr0D9oiQWeL",
                    "time": "4:56",
                    "second": 296
                },
                {
                    "SongTitle": "差不多先生",
                    "SongID": "g-QS-3L5UTs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=g-QS-3L5UTs&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=g-QS-3L5UTs&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "MC HotDog",
                    "ArtistID": "UCW3Q3F5SByAWsYtRRFIMuNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCW3Q3F5SByAWsYtRRFIMuNA",
                    "ArtistUrl": "https://youtube.com/channel/UCW3Q3F5SByAWsYtRRFIMuNA",
                    "time": "4:26",
                    "second": 266
                },
                {
                    "SongTitle": "心如止水",
                    "SongID": "zeWJs6F8teQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=zeWJs6F8teQ&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=zeWJs6F8teQ&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Ice Paper",
                    "ArtistID": "UCBrwmyj8_ZOHkhDD62UdtDQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCBrwmyj8_ZOHkhDD62UdtDQ",
                    "ArtistUrl": "https://youtube.com/channel/UCBrwmyj8_ZOHkhDD62UdtDQ",
                    "time": "3:06",
                    "second": 186
                },
                {
                    "SongTitle": "My Man",
                    "SongID": "0Me6ujmdO2c",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=0Me6ujmdO2c&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=0Me6ujmdO2c&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Jony J",
                    "ArtistID": "UCaIDelQQ-oSIOwh9wO3lRjw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCaIDelQQ-oSIOwh9wO3lRjw",
                    "ArtistUrl": "https://youtube.com/channel/UCaIDelQQ-oSIOwh9wO3lRjw",
                    "time": "3:26",
                    "second": 206
                },
                {
                    "SongTitle": "很久很久",
                    "SongID": "d5gwqvgtJXI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=d5gwqvgtJXI&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=d5gwqvgtJXI&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "楊和蘇KeyNG",
                    "ArtistID": "UC87NfAX3JD-ezuwsbDlZ2xA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC87NfAX3JD-ezuwsbDlZ2xA",
                    "ArtistUrl": "https://youtube.com/channel/UC87NfAX3JD-ezuwsbDlZ2xA",
                    "time": "5:21",
                    "second": 321
                },
                {
                    "SongTitle": "刘聪KEY.L  👁️⃤    没钥匙的锁 【 LYRIC VIDEO 】",
                    "SongID": "CSjRJZoTmo0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=CSjRJZoTmo0&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=CSjRJZoTmo0&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "ZHONG.TV",
                    "ArtistID": "UCYpaEt_D5OB2aisQvNmPWrw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCYpaEt_D5OB2aisQvNmPWrw",
                    "ArtistUrl": "https://youtube.com/channel/UCYpaEt_D5OB2aisQvNmPWrw",
                    "time": "5:21",
                    "second": 321
                },
                {
                    "SongTitle": "(高音質) 艾福杰尼 After Journey  - 酒精 ALCOHOL",
                    "SongID": "XNLe5dedFkw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=XNLe5dedFkw&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=XNLe5dedFkw&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "JohnnyChen Studios",
                    "ArtistID": "UCyYY95Bs3A5ppgnJrRQjqOQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCyYY95Bs3A5ppgnJrRQjqOQ",
                    "ArtistUrl": "https://youtube.com/channel/UCyYY95Bs3A5ppgnJrRQjqOQ",
                    "time": "3:40",
                    "second": 220
                },
                {
                    "SongTitle": "100",
                    "SongID": "fmo5ihh5mus",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=fmo5ihh5mus&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=fmo5ihh5mus&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "黑怕盲盒Vol.1示愛系列",
                    "ArtistID": "MPREb_BVW6iQqnrYH",
                    "ArtistMusicUrl": "https://music.youtube.com/browse/MPREb_BVW6iQqnrYH",
                    "ArtistUrl": "https://youtube.com/browse/MPREb_BVW6iQqnrYH",
                    "time": "3:46",
                    "second": 226
                },
                {
                    "SongTitle": "橘子",
                    "SongID": "GPa0J6oMjbQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=GPa0J6oMjbQ&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=GPa0J6oMjbQ&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "你最好知道",
                    "ArtistID": "MPREb_qQc4Z6H3nN3",
                    "ArtistMusicUrl": "https://music.youtube.com/browse/MPREb_qQc4Z6H3nN3",
                    "ArtistUrl": "https://youtube.com/browse/MPREb_qQc4Z6H3nN3",
                    "time": "3:34",
                    "second": 214
                },
                {
                    "SongTitle": "套路 (合作演出：Jony J)",
                    "SongID": "XhSp_Wz2kk8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=XhSp_Wz2kk8&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=XhSp_Wz2kk8&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "3ASiC",
                    "ArtistID": "UCL2kVJWQch-WOi2d6ypjsjw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2kVJWQch-WOi2d6ypjsjw",
                    "ArtistUrl": "https://youtube.com/channel/UCL2kVJWQch-WOi2d6ypjsjw",
                    "time": "2:41",
                    "second": 161
                },
                {
                    "SongTitle": "虎山行",
                    "SongID": "U7b2pfa_m5k",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=U7b2pfa_m5k&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=U7b2pfa_m5k&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "GAI",
                    "ArtistID": "UCo9qhWHad0h7TmDypR7R6DA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCo9qhWHad0h7TmDypR7R6DA",
                    "ArtistUrl": "https://youtube.com/channel/UCo9qhWHad0h7TmDypR7R6DA",
                    "time": "4:02",
                    "second": 242
                },
                {
                    "SongTitle": "江湖流",
                    "SongID": "-exzLtADPMg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=-exzLtADPMg&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=-exzLtADPMg&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "江湖流",
                    "ArtistID": "MPREb_32Sz6bCeaZV",
                    "ArtistMusicUrl": "https://music.youtube.com/browse/MPREb_32Sz6bCeaZV",
                    "ArtistUrl": "https://youtube.com/browse/MPREb_32Sz6bCeaZV",
                    "time": "4:50",
                    "second": 290
                },
                {
                    "SongTitle": "Follow",
                    "SongID": "GC-_tWEUIH8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=GC-_tWEUIH8&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=GC-_tWEUIH8&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "梨冻紧",
                    "ArtistID": "UC99aGcwCtDYrE8MtoTid9IA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC99aGcwCtDYrE8MtoTid9IA",
                    "ArtistUrl": "https://youtube.com/channel/UC99aGcwCtDYrE8MtoTid9IA",
                    "time": "4:04",
                    "second": 244
                },
                {
                    "SongTitle": "COCO",
                    "SongID": "B8TJ8MDdHLo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=B8TJ8MDdHLo&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=B8TJ8MDdHLo&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Aioz",
                    "ArtistID": "UCdbf0vh-20T7SnH90anaq5Q",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCdbf0vh-20T7SnH90anaq5Q",
                    "ArtistUrl": "https://youtube.com/channel/UCdbf0vh-20T7SnH90anaq5Q",
                    "time": "3:05",
                    "second": 185
                },
                {
                    "SongTitle": "吹 right now",
                    "SongID": "5Z56LiSGJZI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=5Z56LiSGJZI&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=5Z56LiSGJZI&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "中國說唱巔峰對決 第九期",
                    "ArtistID": "MPREb_uqdSIcGPlJP",
                    "ArtistMusicUrl": "https://music.youtube.com/browse/MPREb_uqdSIcGPlJP",
                    "ArtistUrl": "https://youtube.com/browse/MPREb_uqdSIcGPlJP",
                    "time": "4:16",
                    "second": 256
                },
                {
                    "SongTitle": "红花会 - 圣诞夜 (feat. 贝贝, PG ONE, 阿之, 丁飞  & K9999) [Official Lyric Video]",
                    "SongID": "yaoJIQjgvZY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=yaoJIQjgvZY&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=yaoJIQjgvZY&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "FirePanda",
                    "ArtistID": "UCF_L4w8YAPLD3baqI05Au6A",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCF_L4w8YAPLD3baqI05Au6A",
                    "ArtistUrl": "https://youtube.com/channel/UCF_L4w8YAPLD3baqI05Au6A",
                    "time": "4:49",
                    "second": 289
                },
                {
                    "SongTitle": "年轻的国王们 Gen Z Group",
                    "SongID": "yV0qmsD7Vl8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=yV0qmsD7Vl8&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=yV0qmsD7Vl8&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Capper",
                    "ArtistID": "UCe6tJ55jn8FY8Haix83KjuA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCe6tJ55jn8FY8Haix83KjuA",
                    "ArtistUrl": "https://youtube.com/channel/UCe6tJ55jn8FY8Haix83KjuA",
                    "time": "3:13",
                    "second": 193
                },
                {
                    "SongTitle": "隨身聽2000",
                    "SongID": "YruF8v_vG1o",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=YruF8v_vG1o&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=YruF8v_vG1o&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "中國說唱巔峰對決 第十一期加更",
                    "ArtistID": "MPREb_5oYL5AXdLJp",
                    "ArtistMusicUrl": "https://music.youtube.com/browse/MPREb_5oYL5AXdLJp",
                    "ArtistUrl": "https://youtube.com/browse/MPREb_5oYL5AXdLJp",
                    "time": "4:10",
                    "second": 250
                },
                {
                    "SongTitle": "🌹 红花会 🌹 : 贝贝  - ONE CASUAL SONG 🎮 【 LYRIC VIDEO 】",
                    "SongID": "GWhnimelUGw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=GWhnimelUGw&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=GWhnimelUGw&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "ZHONG.TV",
                    "ArtistID": "UCYpaEt_D5OB2aisQvNmPWrw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCYpaEt_D5OB2aisQvNmPWrw",
                    "ArtistUrl": "https://youtube.com/channel/UCYpaEt_D5OB2aisQvNmPWrw",
                    "time": "2:52",
                    "second": 172
                },
                {
                    "SongTitle": "After Journey",
                    "SongID": "mp17yFOKfzY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=mp17yFOKfzY&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=mp17yFOKfzY&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "After Journey",
                    "ArtistID": "UChTBTm2A5C1xJrlsDB6-FIg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UChTBTm2A5C1xJrlsDB6-FIg",
                    "ArtistUrl": "https://youtube.com/channel/UChTBTm2A5C1xJrlsDB6-FIg",
                    "time": "3:51",
                    "second": 231
                },
                {
                    "SongTitle": "花,太陽,彩虹,你",
                    "SongID": "IoFnp_qAE6g",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=IoFnp_qAE6g&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=IoFnp_qAE6g&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Mai",
                    "ArtistID": "UCa4WZChr5QmbIR4dh4OxAJg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCa4WZChr5QmbIR4dh4OxAJg",
                    "ArtistUrl": "https://youtube.com/channel/UCa4WZChr5QmbIR4dh4OxAJg",
                    "time": "3:43",
                    "second": 223
                },
                {
                    "SongTitle": "My Boo (合作演出：c0de731)",
                    "SongID": "TN7uVHMQTaI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=TN7uVHMQTaI&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=TN7uVHMQTaI&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "KEY.L刘聪",
                    "ArtistID": "UCh1-RB0LOOn-B69rHkKiyvQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCh1-RB0LOOn-B69rHkKiyvQ",
                    "ArtistUrl": "https://youtube.com/channel/UCh1-RB0LOOn-B69rHkKiyvQ",
                    "time": "3:54",
                    "second": 234
                },
                {
                    "SongTitle": "不用去猜",
                    "SongID": "PQYVfWZ07PQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=PQYVfWZ07PQ&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=PQYVfWZ07PQ&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Jony J",
                    "ArtistID": "UCaIDelQQ-oSIOwh9wO3lRjw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCaIDelQQ-oSIOwh9wO3lRjw",
                    "ArtistUrl": "https://youtube.com/channel/UCaIDelQQ-oSIOwh9wO3lRjw",
                    "time": "3:33",
                    "second": 213
                },
                {
                    "SongTitle": "目不轉睛",
                    "SongID": "dHbWwjYHgDA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=dHbWwjYHgDA&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=dHbWwjYHgDA&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "王以太",
                    "ArtistID": "UCmfq2-6nkZFvS5LYtshQmEw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCmfq2-6nkZFvS5LYtshQmEw",
                    "ArtistUrl": "https://youtube.com/channel/UCmfq2-6nkZFvS5LYtshQmEw",
                    "time": "2:43",
                    "second": 163
                },
                {
                    "SongTitle": "苦咖啡·唯一",
                    "SongID": "oLbZq3lET3c",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=oLbZq3lET3c&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=oLbZq3lET3c&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "那奇沃夫",
                    "ArtistID": "UC66S5szxcBslu86SYxRJ4Fg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC66S5szxcBslu86SYxRJ4Fg",
                    "ArtistUrl": "https://youtube.com/channel/UC66S5szxcBslu86SYxRJ4Fg",
                    "time": "3:04",
                    "second": 184
                },
                {
                    "SongTitle": "晚安 Good Nite",
                    "SongID": "y7aQ_YlabBo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=y7aQ_YlabBo&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=y7aQ_YlabBo&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "中國說唱巔峰對決 第一期",
                    "ArtistID": "MPREb_U8TxL3yEdvX",
                    "ArtistMusicUrl": "https://music.youtube.com/browse/MPREb_U8TxL3yEdvX",
                    "ArtistUrl": "https://youtube.com/browse/MPREb_U8TxL3yEdvX",
                    "time": "3:51",
                    "second": 231
                },
                {
                    "SongTitle": "防火线 (合作演出：刘柏辛)",
                    "SongID": "Gt5-HaGB1KE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Gt5-HaGB1KE&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=Gt5-HaGB1KE&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Jony J",
                    "ArtistID": "UCaIDelQQ-oSIOwh9wO3lRjw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCaIDelQQ-oSIOwh9wO3lRjw",
                    "ArtistUrl": "https://youtube.com/channel/UCaIDelQQ-oSIOwh9wO3lRjw",
                    "time": "4:21",
                    "second": 261
                },
                {
                    "SongTitle": "喜新恋旧",
                    "SongID": "W8G2Wzlhh78",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=W8G2Wzlhh78&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=W8G2Wzlhh78&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Jony J",
                    "ArtistID": "UCaIDelQQ-oSIOwh9wO3lRjw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCaIDelQQ-oSIOwh9wO3lRjw",
                    "ArtistUrl": "https://youtube.com/channel/UCaIDelQQ-oSIOwh9wO3lRjw",
                    "time": "4:23",
                    "second": 263
                },
                {
                    "SongTitle": "顽家",
                    "SongID": "4nIkgUydo2Q",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=4nIkgUydo2Q&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=4nIkgUydo2Q&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Jony J",
                    "ArtistID": "UCaIDelQQ-oSIOwh9wO3lRjw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCaIDelQQ-oSIOwh9wO3lRjw",
                    "ArtistUrl": "https://youtube.com/channel/UCaIDelQQ-oSIOwh9wO3lRjw",
                    "time": "2:56",
                    "second": 176
                },
                {
                    "SongTitle": "想把你留在这里",
                    "SongID": "WJTTwkZjKPY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=WJTTwkZjKPY&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=WJTTwkZjKPY&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Tizzy T",
                    "ArtistID": "UCKUKirmk8HTritPbExSi1dw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCKUKirmk8HTritPbExSi1dw",
                    "ArtistUrl": "https://youtube.com/channel/UCKUKirmk8HTritPbExSi1dw",
                    "time": "3:21",
                    "second": 201
                },
                {
                    "SongTitle": "甜葡萄 红眼睛",
                    "SongID": "FDSeB0VRXCU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=FDSeB0VRXCU&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=FDSeB0VRXCU&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Jony J",
                    "ArtistID": "UCaIDelQQ-oSIOwh9wO3lRjw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCaIDelQQ-oSIOwh9wO3lRjw",
                    "ArtistUrl": "https://youtube.com/channel/UCaIDelQQ-oSIOwh9wO3lRjw",
                    "time": "2:58",
                    "second": 178
                },
                {
                    "SongTitle": "亞特蘭蒂斯之心",
                    "SongID": "D4dp73I4JnA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=D4dp73I4JnA&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=D4dp73I4JnA&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "GALI",
                    "ArtistID": "UCXhsue-MvJ2FU4j-wPC_RdA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCXhsue-MvJ2FU4j-wPC_RdA",
                    "ArtistUrl": "https://youtube.com/channel/UCXhsue-MvJ2FU4j-wPC_RdA",
                    "time": "3:44",
                    "second": 224
                },
                {
                    "SongTitle": "你最好知道",
                    "SongID": "pTOuaczWLXc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=pTOuaczWLXc&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=pTOuaczWLXc&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Tizzy T",
                    "ArtistID": "UCrC0V-DmDZrzr4L1J5kOjLQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCrC0V-DmDZrzr4L1J5kOjLQ",
                    "ArtistUrl": "https://youtube.com/channel/UCrC0V-DmDZrzr4L1J5kOjLQ",
                    "time": "3:18",
                    "second": 198
                },
                {
                    "SongTitle": "匕首",
                    "SongID": "MwdU4-zUbb8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=MwdU4-zUbb8&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=MwdU4-zUbb8&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Tizzy T",
                    "ArtistID": "UCrC0V-DmDZrzr4L1J5kOjLQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCrC0V-DmDZrzr4L1J5kOjLQ",
                    "ArtistUrl": "https://youtube.com/channel/UCrC0V-DmDZrzr4L1J5kOjLQ",
                    "time": "2:54",
                    "second": 174
                },
                {
                    "SongTitle": "飞船失事",
                    "SongID": "X1oNloZHDlQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=X1oNloZHDlQ&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=X1oNloZHDlQ&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Tizzy T",
                    "ArtistID": "UCrC0V-DmDZrzr4L1J5kOjLQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCrC0V-DmDZrzr4L1J5kOjLQ",
                    "ArtistUrl": "https://youtube.com/channel/UCrC0V-DmDZrzr4L1J5kOjLQ",
                    "time": "3:36",
                    "second": 216
                },
                {
                    "SongTitle": "雨不停",
                    "SongID": "EF-o_1oOfhY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=EF-o_1oOfhY&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=EF-o_1oOfhY&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Tizzy T",
                    "ArtistID": "UCrC0V-DmDZrzr4L1J5kOjLQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCrC0V-DmDZrzr4L1J5kOjLQ",
                    "ArtistUrl": "https://youtube.com/channel/UCrC0V-DmDZrzr4L1J5kOjLQ",
                    "time": "3:42",
                    "second": 222
                },
                {
                    "SongTitle": "你",
                    "SongID": "-DRbot9w7gk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=-DRbot9w7gk&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=-DRbot9w7gk&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Tizzy T",
                    "ArtistID": "UCrC0V-DmDZrzr4L1J5kOjLQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCrC0V-DmDZrzr4L1J5kOjLQ",
                    "ArtistUrl": "https://youtube.com/channel/UCrC0V-DmDZrzr4L1J5kOjLQ",
                    "time": "3:34",
                    "second": 214
                },
                {
                    "SongTitle": "贫民百万男孩",
                    "SongID": "xUJULaUk24o",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=xUJULaUk24o&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=xUJULaUk24o&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Tizzy T",
                    "ArtistID": "UCrC0V-DmDZrzr4L1J5kOjLQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCrC0V-DmDZrzr4L1J5kOjLQ",
                    "ArtistUrl": "https://youtube.com/channel/UCrC0V-DmDZrzr4L1J5kOjLQ",
                    "time": "3:32",
                    "second": 212
                },
                {
                    "SongTitle": "頭文字T",
                    "SongID": "unaFXWa5ets",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=unaFXWa5ets&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=unaFXWa5ets&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "中國說唱巔峰對決 先導片",
                    "ArtistID": "MPREb_MFe0WgH6boe",
                    "ArtistMusicUrl": "https://music.youtube.com/browse/MPREb_MFe0WgH6boe",
                    "ArtistUrl": "https://youtube.com/browse/MPREb_MFe0WgH6boe",
                    "time": "1:29",
                    "second": 89
                },
                {
                    "SongTitle": "Tizzy T - 變 ft.Jony J  (720p music video)",
                    "SongID": "iOzWNJKzc10",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=iOzWNJKzc10&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=iOzWNJKzc10&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Lu Collection",
                    "ArtistID": "UCEX6Swga5ceP3kkb6olsuog",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCEX6Swga5ceP3kkb6olsuog",
                    "ArtistUrl": "https://youtube.com/channel/UCEX6Swga5ceP3kkb6olsuog",
                    "time": "3:12",
                    "second": 192
                },
                {
                    "SongTitle": "Tizzy T - 不必為我擔心  (720p music video)",
                    "SongID": "nAYXSBjKrJA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=nAYXSBjKrJA&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=nAYXSBjKrJA&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Lu Collection",
                    "ArtistID": "UCEX6Swga5ceP3kkb6olsuog",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCEX6Swga5ceP3kkb6olsuog",
                    "ArtistUrl": "https://youtube.com/channel/UCEX6Swga5ceP3kkb6olsuog",
                    "time": "3:43",
                    "second": 223
                },
                {
                    "SongTitle": "Tizzy T - 市中心  (720p music video)",
                    "SongID": "6U_SwJjwSFY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=6U_SwJjwSFY&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=6U_SwJjwSFY&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Lu Collection",
                    "ArtistID": "UCEX6Swga5ceP3kkb6olsuog",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCEX6Swga5ceP3kkb6olsuog",
                    "ArtistUrl": "https://youtube.com/channel/UCEX6Swga5ceP3kkb6olsuog",
                    "time": "3:59",
                    "second": 239
                },
                {
                    "SongTitle": "小丑女",
                    "SongID": "FHJrmWXflHM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=FHJrmWXflHM&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=FHJrmWXflHM&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "楊和蘇KeyNG",
                    "ArtistID": "UC87NfAX3JD-ezuwsbDlZ2xA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC87NfAX3JD-ezuwsbDlZ2xA",
                    "ArtistUrl": "https://youtube.com/channel/UC87NfAX3JD-ezuwsbDlZ2xA",
                    "time": "3:33",
                    "second": 213
                },
                {
                    "SongTitle": "70%",
                    "SongID": "VQk_9VUpVdk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=VQk_9VUpVdk&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=VQk_9VUpVdk&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "GALI",
                    "ArtistID": "UClPZts5UPr7f8Gzg8heB8Gg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UClPZts5UPr7f8Gzg8heB8Gg",
                    "ArtistUrl": "https://youtube.com/channel/UClPZts5UPr7f8Gzg8heB8Gg",
                    "time": "3:35",
                    "second": 215
                },
                {
                    "SongTitle": "柑橘乌云Please",
                    "SongID": "QNXEoi3_EKY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=QNXEoi3_EKY&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=QNXEoi3_EKY&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Capper",
                    "ArtistID": "UCe6tJ55jn8FY8Haix83KjuA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCe6tJ55jn8FY8Haix83KjuA",
                    "ArtistUrl": "https://youtube.com/channel/UCe6tJ55jn8FY8Haix83KjuA",
                    "time": "2:58",
                    "second": 178
                },
                {
                    "SongTitle": "Christy",
                    "SongID": "NnIYHwpDZqc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=NnIYHwpDZqc&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=NnIYHwpDZqc&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Tyson Yoshi",
                    "ArtistID": "UC44kj7xDOcCiWB2GKf2bGhA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC44kj7xDOcCiWB2GKf2bGhA",
                    "ArtistUrl": "https://youtube.com/channel/UC44kj7xDOcCiWB2GKf2bGhA",
                    "time": "2:54",
                    "second": 174
                },
                {
                    "SongTitle": "蜥蜴",
                    "SongID": "R-XJFN89584",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=R-XJFN89584&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=R-XJFN89584&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "劉炫廷",
                    "ArtistID": "UCM4svH5LN4HHvGghfEIlBhw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCM4svH5LN4HHvGghfEIlBhw",
                    "ArtistUrl": "https://youtube.com/channel/UCM4svH5LN4HHvGghfEIlBhw",
                    "time": "4:08",
                    "second": 248
                },
                {
                    "SongTitle": "经济舱",
                    "SongID": "QAihdhNnYp0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=QAihdhNnYp0&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=QAihdhNnYp0&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "经济舱",
                    "ArtistID": "MPREb_J8rtT1TpySH",
                    "ArtistMusicUrl": "https://music.youtube.com/browse/MPREb_J8rtT1TpySH",
                    "ArtistUrl": "https://youtube.com/browse/MPREb_J8rtT1TpySH",
                    "time": "3:40",
                    "second": 220
                },
                {
                    "SongTitle": "《中國新說唱2020》純享：李佳隆&林渝植ANO《衛星Satellite》",
                    "SongID": "en_YmdwE_QY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=en_YmdwE_QY&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=en_YmdwE_QY&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "iQIYI TW",
                    "ArtistID": "UCgWD0gHPDM_lCf0PSYDnTIg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCgWD0gHPDM_lCf0PSYDnTIg",
                    "ArtistUrl": "https://youtube.com/channel/UCgWD0gHPDM_lCf0PSYDnTIg",
                    "time": "3:15",
                    "second": 195
                },
                {
                    "SongTitle": "艾熱   李佳隆《星球墜落》高音質   動態歌詞版MV",
                    "SongID": "pPeBbLhZqyg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=pPeBbLhZqyg&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=pPeBbLhZqyg&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Lagu Barat Terbaru - Music home",
                    "ArtistID": "UCwlWJ7xt_7dE133aEAjZAQw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCwlWJ7xt_7dE133aEAjZAQw",
                    "ArtistUrl": "https://youtube.com/channel/UCwlWJ7xt_7dE133aEAjZAQw",
                    "time": "3:00",
                    "second": 180
                },
                {
                    "SongTitle": "李榮浩 & ICE - 王牌冤家 / 歌詞純享版",
                    "SongID": "M60XySbwxZ8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=M60XySbwxZ8&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=M60XySbwxZ8&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "J視界",
                    "ArtistID": "UC5PL-vyFBPoz6_dnCSA4uxQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC5PL-vyFBPoz6_dnCSA4uxQ",
                    "ArtistUrl": "https://youtube.com/channel/UC5PL-vyFBPoz6_dnCSA4uxQ",
                    "time": "3:26",
                    "second": 206
                },
                {
                    "SongTitle": "烈火战马",
                    "SongID": "D9Lx-KiCLSQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=D9Lx-KiCLSQ&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=D9Lx-KiCLSQ&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "GAI周延",
                    "ArtistID": "UCurdCxfs2pjRoLTFKAJo4yA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCurdCxfs2pjRoLTFKAJo4yA",
                    "ArtistUrl": "https://youtube.com/channel/UCurdCxfs2pjRoLTFKAJo4yA",
                    "time": "3:10",
                    "second": 190
                },
                {
                    "SongTitle": "💥 GO$H MUSIC 💥 : 🐜 蚂蚁 🐜 布瑞吉 BRIDGE & K ELEVEN [ LYRIC VIDEO ]",
                    "SongID": "-VyuYkqDspw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=-VyuYkqDspw&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=-VyuYkqDspw&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "ZHONG.TV",
                    "ArtistID": "UCYpaEt_D5OB2aisQvNmPWrw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCYpaEt_D5OB2aisQvNmPWrw",
                    "ArtistUrl": "https://youtube.com/channel/UCYpaEt_D5OB2aisQvNmPWrw",
                    "time": "2:41",
                    "second": 161
                },
                {
                    "SongTitle": "PG ONE - 中二病 Chunibyo (Music Video)",
                    "SongID": "4R5hsTsB47M",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=4R5hsTsB47M&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=4R5hsTsB47M&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "PG One",
                    "ArtistID": "UCdwOe7ah5zxkbfmGUaX8xdA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCdwOe7ah5zxkbfmGUaX8xdA",
                    "ArtistUrl": "https://youtube.com/channel/UCdwOe7ah5zxkbfmGUaX8xdA",
                    "time": "4:07",
                    "second": 247
                },
                {
                    "SongTitle": "老大",
                    "SongID": "c1h2KirX6mU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=c1h2KirX6mU&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=c1h2KirX6mU&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "bridge",
                    "ArtistID": "UC4VgyeK75PqlrtkeFmb9Tjw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC4VgyeK75PqlrtkeFmb9Tjw",
                    "ArtistUrl": "https://youtube.com/channel/UC4VgyeK75PqlrtkeFmb9Tjw",
                    "time": "2:44",
                    "second": 164
                },
                {
                    "SongTitle": "语音备忘录",
                    "SongID": "Bkfha9sfbWw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Bkfha9sfbWw&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=Bkfha9sfbWw&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "PG One",
                    "ArtistID": "UCdwOe7ah5zxkbfmGUaX8xdA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCdwOe7ah5zxkbfmGUaX8xdA",
                    "ArtistUrl": "https://youtube.com/channel/UCdwOe7ah5zxkbfmGUaX8xdA",
                    "time": "3:38",
                    "second": 218
                },
                {
                    "SongTitle": "奴隶",
                    "SongID": "W_jq7JcPI4M",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=W_jq7JcPI4M&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=W_jq7JcPI4M&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Jony J",
                    "ArtistID": "UCaIDelQQ-oSIOwh9wO3lRjw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCaIDelQQ-oSIOwh9wO3lRjw",
                    "ArtistUrl": "https://youtube.com/channel/UCaIDelQQ-oSIOwh9wO3lRjw",
                    "time": "3:10",
                    "second": 190
                },
                {
                    "SongTitle": "寶貝大反派",
                    "SongID": "qCAxSnzN7Hw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=qCAxSnzN7Hw&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=qCAxSnzN7Hw&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "中國說唱巔峰對決 第九期",
                    "ArtistID": "MPREb_uqdSIcGPlJP",
                    "ArtistMusicUrl": "https://music.youtube.com/browse/MPREb_uqdSIcGPlJP",
                    "ArtistUrl": "https://youtube.com/browse/MPREb_uqdSIcGPlJP",
                    "time": "4:03",
                    "second": 243
                },
                {
                    "SongTitle": "PGONE-破釜沉舟〖動態字幕/高音質〗「為人處世算保守也不見得路程變好走」",
                    "SongID": "cMRAjcNESyY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=cMRAjcNESyY&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=cMRAjcNESyY&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Bambi Music FM",
                    "ArtistID": "UCpY85Go88MCLBFkkD02IvpQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCpY85Go88MCLBFkkD02IvpQ",
                    "ArtistUrl": "https://youtube.com/channel/UCpY85Go88MCLBFkkD02IvpQ",
                    "time": "2:51",
                    "second": 171
                },
                {
                    "SongTitle": "加冕",
                    "SongID": "qyCJrfbO_Rg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=qyCJrfbO_Rg&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=qyCJrfbO_Rg&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "楊和蘇KeyNG",
                    "ArtistID": "UC87NfAX3JD-ezuwsbDlZ2xA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC87NfAX3JD-ezuwsbDlZ2xA",
                    "ArtistUrl": "https://youtube.com/channel/UC87NfAX3JD-ezuwsbDlZ2xA",
                    "time": "3:40",
                    "second": 220
                },
                {
                    "SongTitle": "ㄦ子娃娃",
                    "SongID": "s7GQeW8Sz7s",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=s7GQeW8Sz7s&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=s7GQeW8Sz7s&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "那吾克熱",
                    "ArtistID": "UCtvWCQtM2WaGkGXeRTIkk1Q",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCtvWCQtM2WaGkGXeRTIkk1Q",
                    "ArtistUrl": "https://youtube.com/channel/UCtvWCQtM2WaGkGXeRTIkk1Q",
                    "time": "2:26",
                    "second": 146
                },
                {
                    "SongTitle": "我的新衣 (合作演出：王倩倩和Ty.)",
                    "SongID": "mMwffV_yM98",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=mMwffV_yM98&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=mMwffV_yM98&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "毛衍七",
                    "ArtistID": "UCnPT2nYXUE-hr7o0ZKzhv1g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCnPT2nYXUE-hr7o0ZKzhv1g",
                    "ArtistUrl": "https://youtube.com/channel/UCnPT2nYXUE-hr7o0ZKzhv1g",
                    "time": "4:05",
                    "second": 245
                },
                {
                    "SongTitle": "吴亦凡，Tizzy T，BrAnT.B小白《三年二班》中国有嘻哈 ----【动态歌词Lyrics|高音质】",
                    "SongID": "1FEcI8pKxz8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=1FEcI8pKxz8&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=1FEcI8pKxz8&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "JLyrics Music Channel",
                    "ArtistID": "UCkrMRN2Qa1fYmcUzosPgY_A",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCkrMRN2Qa1fYmcUzosPgY_A",
                    "ArtistUrl": "https://youtube.com/channel/UCkrMRN2Qa1fYmcUzosPgY_A",
                    "time": "3:21",
                    "second": 201
                },
                {
                    "SongTitle": "PG One - H.M.E （完整版）",
                    "SongID": "s9JS-jZGxUA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=s9JS-jZGxUA&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=s9JS-jZGxUA&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Kim Kardashian East",
                    "ArtistID": "UCSDwnmcPJBdhpOCeVMA4yOA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCSDwnmcPJBdhpOCeVMA4yOA",
                    "ArtistUrl": "https://youtube.com/channel/UCSDwnmcPJBdhpOCeVMA4yOA",
                    "time": "4:24",
                    "second": 264
                },
                {
                    "SongTitle": "《中國有嘻哈 精彩回顧》艾福杰尼《庫爾勒》ft cat雨馨",
                    "SongID": "58VCo_IEVtU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=58VCo_IEVtU&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=58VCo_IEVtU&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "iQIYI TW",
                    "ArtistID": "UCgWD0gHPDM_lCf0PSYDnTIg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCgWD0gHPDM_lCf0PSYDnTIg",
                    "ArtistUrl": "https://youtube.com/channel/UCgWD0gHPDM_lCf0PSYDnTIg",
                    "time": "3:19",
                    "second": 199
                },
                {
                    "SongTitle": "Jackson - Papillon",
                    "SongID": "rB671ZZSOrI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=rB671ZZSOrI&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=rB671ZZSOrI&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "B2 Music",
                    "ArtistID": "UCvmt37j6SoB4KdPTVO0JPUA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCvmt37j6SoB4KdPTVO0JPUA",
                    "ArtistUrl": "https://youtube.com/channel/UCvmt37j6SoB4KdPTVO0JPUA",
                    "time": "3:15",
                    "second": 195
                },
                {
                    "SongTitle": "场上称霸",
                    "SongID": "vQutmnKml-E",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=vQutmnKml-E&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=vQutmnKml-E&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "萬妮達",
                    "ArtistID": "UCVZ4Q6obaF-zZk8Z1WjK1Yg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCVZ4Q6obaF-zZk8Z1WjK1Yg",
                    "ArtistUrl": "https://youtube.com/channel/UCVZ4Q6obaF-zZk8Z1WjK1Yg",
                    "time": "3:33",
                    "second": 213
                },
                {
                    "SongTitle": "Queendom",
                    "SongID": "5llSLPwCCw0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=5llSLPwCCw0&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=5llSLPwCCw0&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "萬妮達",
                    "ArtistID": "UCVZ4Q6obaF-zZk8Z1WjK1Yg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCVZ4Q6obaF-zZk8Z1WjK1Yg",
                    "ArtistUrl": "https://youtube.com/channel/UCVZ4Q6obaF-zZk8Z1WjK1Yg",
                    "time": "4:16",
                    "second": 256
                },
                {
                    "SongTitle": "野狼Disco",
                    "SongID": "BaqwYSmrKMo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=BaqwYSmrKMo&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=BaqwYSmrKMo&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "寶石Gem",
                    "ArtistID": "UCYeXrma04p2tsOhrifdGvnw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCYeXrma04p2tsOhrifdGvnw",
                    "ArtistUrl": "https://youtube.com/channel/UCYeXrma04p2tsOhrifdGvnw",
                    "time": "3:59",
                    "second": 239
                },
                {
                    "SongTitle": "Going Go",
                    "SongID": "IfXaQK_7bGY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=IfXaQK_7bGY&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=IfXaQK_7bGY&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "Tizzy T",
                    "ArtistID": "UCKUKirmk8HTritPbExSi1dw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCKUKirmk8HTritPbExSi1dw",
                    "ArtistUrl": "https://youtube.com/channel/UCKUKirmk8HTritPbExSi1dw",
                    "time": "3:27",
                    "second": 207
                },
                {
                    "SongTitle": "孤獨症DEMO",
                    "SongID": "GZOFn8HUo7w",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=GZOFn8HUo7w&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=GZOFn8HUo7w&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "中國說唱巔峰對決 第十一期",
                    "ArtistID": "MPREb_3d55hAyJNzH",
                    "ArtistMusicUrl": "https://music.youtube.com/browse/MPREb_3d55hAyJNzH",
                    "ArtistUrl": "https://youtube.com/browse/MPREb_3d55hAyJNzH",
                    "time": "3:58",
                    "second": 238
                },
                {
                    "SongTitle": "【中國新說唱】第七期│劉柏辛 COCO MAKE ME DO IT 9進6突圍賽",
                    "SongID": "L233mInsgto",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=L233mInsgto&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=L233mInsgto&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "【中國新說唱】官方授權頻道",
                    "ArtistID": "UCBWeFjyATpls3RBUarenx9Q",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCBWeFjyATpls3RBUarenx9Q",
                    "ArtistUrl": "https://youtube.com/channel/UCBWeFjyATpls3RBUarenx9Q",
                    "time": "3:34",
                    "second": 214
                },
                {
                    "SongTitle": "#中国有嘻哈 #rapofchina - Song 03. How Do (PG ONE)",
                    "SongID": "qJi97z4rMI4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=qJi97z4rMI4&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=qJi97z4rMI4&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "PHASELESS无相之相",
                    "ArtistID": "UCrmvsl8uzchoSYdyWLkrWbg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCrmvsl8uzchoSYdyWLkrWbg",
                    "ArtistUrl": "https://youtube.com/channel/UCrmvsl8uzchoSYdyWLkrWbg",
                    "time": "3:25",
                    "second": 205
                },
                {
                    "SongTitle": "PGone万磁王《Fre$h One》",
                    "SongID": "CSYVjviDXJI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=CSYVjviDXJI&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=CSYVjviDXJI&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "iWeibo微博精选",
                    "ArtistID": "UCiiiQqfnndPLI_PwtVN2Ctw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiiiQqfnndPLI_PwtVN2Ctw",
                    "ArtistUrl": "https://youtube.com/channel/UCiiiQqfnndPLI_PwtVN2Ctw",
                    "time": "3:38",
                    "second": 218
                },
                {
                    "SongTitle": "PG ONE - H.M.E『中国有嘻哈』",
                    "SongID": "EhAtfUnD6yQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=EhAtfUnD6yQ&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=EhAtfUnD6yQ&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "247中文说唱",
                    "ArtistID": "UC1WeQmm5Jcqwb9ZmdPCLmNg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC1WeQmm5Jcqwb9ZmdPCLmNg",
                    "ArtistUrl": "https://youtube.com/channel/UC1WeQmm5Jcqwb9ZmdPCLmNg",
                    "time": "3:05",
                    "second": 185
                },
                {
                    "SongTitle": "《中國新說唱》王以太V法老《懸崖華爾滋》 　吳亦凡狂讚：想把兩位都留下｜NOWnews今日新聞",
                    "SongID": "791bg4RrPu8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=791bg4RrPu8&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=791bg4RrPu8&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "NOWnews",
                    "ArtistID": "UCg8EwsqYmiw7G267xxPyXsg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCg8EwsqYmiw7G267xxPyXsg",
                    "ArtistUrl": "https://youtube.com/channel/UCg8EwsqYmiw7G267xxPyXsg",
                    "time": "2:59",
                    "second": 179
                },
                {
                    "SongTitle": "Manta",
                    "SongID": "zZ--vCxXaDQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=zZ--vCxXaDQ&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=zZ--vCxXaDQ&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "劉柏辛",
                    "ArtistID": "UCtHbO8ileCXM7H2JUYMTJxw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCtHbO8ileCXM7H2JUYMTJxw",
                    "ArtistUrl": "https://youtube.com/channel/UCtHbO8ileCXM7H2JUYMTJxw",
                    "time": "3:23",
                    "second": 203
                },
                {
                    "SongTitle": "【中国新说唱】Three Pass-那吾克热 ICE 动态歌词版",
                    "SongID": "ImApImXHTe8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ImApImXHTe8&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=ImApImXHTe8&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "猴屁股娱乐频道",
                    "ArtistID": "UCQl8hhE8-3iZpxkfsVXkojQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCQl8hhE8-3iZpxkfsVXkojQ",
                    "ArtistUrl": "https://youtube.com/channel/UCQl8hhE8-3iZpxkfsVXkojQ",
                    "time": "2:23",
                    "second": 143
                },
                {
                    "SongTitle": "TIME",
                    "SongID": "lvoNVxrYjbI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=lvoNVxrYjbI&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "SongUrl": "https://youtube.com/watch?v=lvoNVxrYjbI&list=PL3qm_8TRqiec-VK7m71rid_A30v2KmcgO",
                    "Artist": "小青龙",
                    "ArtistID": "UCfWCIZ_vyZXZskZgGo8nA-Q",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCfWCIZ_vyZXZskZgGo8nA-Q",
                    "ArtistUrl": "https://youtube.com/channel/UCfWCIZ_vyZXZskZgGo8nA-Q",
                    "time": "2:49",
                    "second": 169
                }
            ]
        }
    ];
    return { data };
});
