export default defineEventHandler((event) => {
    const data = [
        {
            "ListName": "周杰倫",
            "SongList": [
                {
                    "SongTitle": "夜曲",
                    "SongID": "Ii46Q7i4uuk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Ii46Q7i4uuk&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=Ii46Q7i4uuk&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:48",
                    "second": 228
                },
                {
                    "SongTitle": "夜曲",
                    "SongID": "Ii46Q7i4uuk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Ii46Q7i4uuk&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=Ii46Q7i4uuk&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:48",
                    "second": 228
                },
                {
                    "SongTitle": "晴天",
                    "SongID": "SJKoWAd5ySo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=SJKoWAd5ySo&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=SJKoWAd5ySo&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:29",
                    "second": 269
                },
                {
                    "SongTitle": "擱淺",
                    "SongID": "0gTGHajEhKQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=0gTGHajEhKQ&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=0gTGHajEhKQ&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:58",
                    "second": 238
                },
                {
                    "SongTitle": "一路向北",
                    "SongID": "Qq2ix2BewvA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Qq2ix2BewvA&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=Qq2ix2BewvA&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:54",
                    "second": 294
                },
                {
                    "SongTitle": "稻香",
                    "SongID": "l6a5D6yxqEU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=l6a5D6yxqEU&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=l6a5D6yxqEU&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:43",
                    "second": 223
                },
                {
                    "SongTitle": "告白氣球",
                    "SongID": "cSqlwNjq77c",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=cSqlwNjq77c&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=cSqlwNjq77c&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:35",
                    "second": 215
                },
                {
                    "SongTitle": "說好的幸福呢",
                    "SongID": "vpBYwcf1p9I",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=vpBYwcf1p9I&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=vpBYwcf1p9I&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:16",
                    "second": 256
                },
                {
                    "SongTitle": "蒲公英的約定",
                    "SongID": "O3UxZrf0AAk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=O3UxZrf0AAk&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=O3UxZrf0AAk&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:07",
                    "second": 247
                },
                {
                    "SongTitle": "楓",
                    "SongID": "afXwxtQLvZM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=afXwxtQLvZM&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=afXwxtQLvZM&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:37",
                    "second": 277
                },
                {
                    "SongTitle": "七里香",
                    "SongID": "U8E3j6y__BA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=U8E3j6y__BA&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=U8E3j6y__BA&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:57",
                    "second": 297
                },
                {
                    "SongTitle": "青花瓷",
                    "SongID": "DxpndDEAqGk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=DxpndDEAqGk&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=DxpndDEAqGk&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:59",
                    "second": 239
                },
                {
                    "SongTitle": "說了再見",
                    "SongID": "Wlwk9osZ9Mc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Wlwk9osZ9Mc&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=Wlwk9osZ9Mc&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:42",
                    "second": 282
                },
                {
                    "SongTitle": "明明就",
                    "SongID": "yYa4minaocg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=yYa4minaocg&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=yYa4minaocg&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:20",
                    "second": 260
                },
                {
                    "SongTitle": "退後",
                    "SongID": "kNZ5P0AAlmg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=kNZ5P0AAlmg&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=kNZ5P0AAlmg&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:29",
                    "second": 209
                },
                {
                    "SongTitle": "不該",
                    "SongID": "S6Tkc8MT56E",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=S6Tkc8MT56E&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=S6Tkc8MT56E&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:50",
                    "second": 290
                },
                {
                    "SongTitle": "蘭亭序",
                    "SongID": "wpJkdFYBtIY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=wpJkdFYBtIY&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=wpJkdFYBtIY&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:13",
                    "second": 253
                },
                {
                    "SongTitle": "說好不哭",
                    "SongID": "OQwnI4HWZLI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=OQwnI4HWZLI&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=OQwnI4HWZLI&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:41",
                    "second": 221
                },
                {
                    "SongTitle": "給我ㄧ首歌的時間",
                    "SongID": "GMLiH4ndCZY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=GMLiH4ndCZY&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=GMLiH4ndCZY&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:13",
                    "second": 253
                },
                {
                    "SongTitle": "髮如雪",
                    "SongID": "Px_TOP_d9zY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Px_TOP_d9zY&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=Px_TOP_d9zY&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "5:01",
                    "second": 301
                },
                {
                    "SongTitle": "珊瑚海",
                    "SongID": "4wePAQ16tkI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=4wePAQ16tkI&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=4wePAQ16tkI&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:16",
                    "second": 256
                },
                {
                    "SongTitle": "安靜",
                    "SongID": "hTCtmY7MAbw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=hTCtmY7MAbw&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=hTCtmY7MAbw&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "5:34",
                    "second": 334
                },
                {
                    "SongTitle": "我落淚．情緒零碎",
                    "SongID": "JyJ01CRfjSY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=JyJ01CRfjSY&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=JyJ01CRfjSY&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:18",
                    "second": 258
                },
                {
                    "SongTitle": "等你下課",
                    "SongID": "mPKqUi8C1GM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=mPKqUi8C1GM&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=mPKqUi8C1GM&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:30",
                    "second": 270
                },
                {
                    "SongTitle": "不能說的秘密",
                    "SongID": "22sctzlPeAI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=22sctzlPeAI&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=22sctzlPeAI&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:56",
                    "second": 296
                },
                {
                    "SongTitle": "聽媽媽的話",
                    "SongID": "Pi5xzNsmmZU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Pi5xzNsmmZU&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=Pi5xzNsmmZU&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:53",
                    "second": 293
                },
                {
                    "SongTitle": "最長的電影",
                    "SongID": "HwTlELG2fqA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=HwTlELG2fqA&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=HwTlELG2fqA&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:55",
                    "second": 235
                },
                {
                    "SongTitle": "軌跡",
                    "SongID": "dMIQfW6XQ-A",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=dMIQfW6XQ-A&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=dMIQfW6XQ-A&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "5:26",
                    "second": 326
                },
                {
                    "SongTitle": "我不配",
                    "SongID": "9B16I7G4Xj4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=9B16I7G4Xj4&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=9B16I7G4Xj4&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:48",
                    "second": 288
                },
                {
                    "SongTitle": "愛在西元前",
                    "SongID": "CxrnaJWsGjQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=CxrnaJWsGjQ&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=CxrnaJWsGjQ&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:54",
                    "second": 234
                },
                {
                    "SongTitle": "花海",
                    "SongID": "ECE0rE7FksU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ECE0rE7FksU&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=ECE0rE7FksU&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:24",
                    "second": 264
                },
                {
                    "SongTitle": "紅顏如霜",
                    "SongID": "-87P_A1DqzI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=-87P_A1DqzI&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=-87P_A1DqzI&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:18",
                    "second": 258
                },
                {
                    "SongTitle": "聽見下雨的聲音",
                    "SongID": "vbOqG8ZdUnE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=vbOqG8ZdUnE&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=vbOqG8ZdUnE&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:39",
                    "second": 279
                },
                {
                    "SongTitle": "開不了口",
                    "SongID": "TKXYh_GLnGo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=TKXYh_GLnGo&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=TKXYh_GLnGo&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:44",
                    "second": 284
                },
                {
                    "SongTitle": "還在流浪",
                    "SongID": "6lZ0litIdSQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=6lZ0litIdSQ&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=6lZ0litIdSQ&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:26",
                    "second": 266
                },
                {
                    "SongTitle": "算什麼男人",
                    "SongID": "e4ppGoPYuBI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=e4ppGoPYuBI&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=e4ppGoPYuBI&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:49",
                    "second": 289
                },
                {
                    "SongTitle": "簡單愛",
                    "SongID": "kvEeCLf16zM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=kvEeCLf16zM&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=kvEeCLf16zM&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:30",
                    "second": 270
                },
                {
                    "SongTitle": "手寫的從前",
                    "SongID": "t6yzQ_OQD9w",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=t6yzQ_OQD9w&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=t6yzQ_OQD9w&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:57",
                    "second": 297
                },
                {
                    "SongTitle": "我是如此相信",
                    "SongID": "JWeI4M-nBBU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=JWeI4M-nBBU&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=JWeI4M-nBBU&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:26",
                    "second": 266
                },
                {
                    "SongTitle": "最偉大的作品",
                    "SongID": "88ed1o89xEo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=88ed1o89xEo&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=88ed1o89xEo&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:05",
                    "second": 245
                },
                {
                    "SongTitle": "千里之外",
                    "SongID": "D5SYQuCo8lE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=D5SYQuCo8lE&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=D5SYQuCo8lE&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:25",
                    "second": 265
                },
                {
                    "SongTitle": "霍元甲",
                    "SongID": "PcFTm-qQhLw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=PcFTm-qQhLw&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=PcFTm-qQhLw&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:38",
                    "second": 278
                },
                {
                    "SongTitle": "半島鐵盒",
                    "SongID": "dsUTcSVdU2U",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=dsUTcSVdU2U&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=dsUTcSVdU2U&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "5:17",
                    "second": 317
                },
                {
                    "SongTitle": "Mojito",
                    "SongID": "m-3MNcF2COk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=m-3MNcF2COk&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=m-3MNcF2COk&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:06",
                    "second": 186
                },
                {
                    "SongTitle": "回到過去",
                    "SongID": "ROGuzF_K-_k",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ROGuzF_K-_k&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=ROGuzF_K-_k&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:51",
                    "second": 231
                },
                {
                    "SongTitle": "倒影",
                    "SongID": "XvHc_VEop7I",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=XvHc_VEop7I&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=XvHc_VEop7I&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:55",
                    "second": 235
                },
                {
                    "SongTitle": "以父之名",
                    "SongID": "bf_aidageTs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=bf_aidageTs&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=bf_aidageTs&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "5:42",
                    "second": 342
                },
                {
                    "SongTitle": "彩虹",
                    "SongID": "yJm6h7ayL7s",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=yJm6h7ayL7s&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=yJm6h7ayL7s&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:23",
                    "second": 263
                },
                {
                    "SongTitle": "陽光宅男",
                    "SongID": "Q-73b1yLHJo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Q-73b1yLHJo&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=Q-73b1yLHJo&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:42",
                    "second": 222
                },
                {
                    "SongTitle": "藉口",
                    "SongID": "mQ0-oxVvvZ0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=mQ0-oxVvvZ0&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=mQ0-oxVvvZ0&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:18",
                    "second": 258
                },
                {
                    "SongTitle": "紅塵客棧",
                    "SongID": "GUvMWPHVfKM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=GUvMWPHVfKM&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=GUvMWPHVfKM&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:34",
                    "second": 274
                },
                {
                    "SongTitle": "黑色毛衣",
                    "SongID": "0ro4ljL7opY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=0ro4ljL7opY&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=0ro4ljL7opY&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:11",
                    "second": 251
                },
                {
                    "SongTitle": "龍捲風",
                    "SongID": "QMqizmScJfI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=QMqizmScJfI&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=QMqizmScJfI&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:10",
                    "second": 250
                },
                {
                    "SongTitle": "菊花台",
                    "SongID": "VlzzZKbdIyM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=VlzzZKbdIyM&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=VlzzZKbdIyM&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:11",
                    "second": 251
                },
                {
                    "SongTitle": "可愛女人",
                    "SongID": "hlb8YbCjN1Y",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=hlb8YbCjN1Y&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=hlb8YbCjN1Y&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:59",
                    "second": 239
                },
                {
                    "SongTitle": "暗號",
                    "SongID": "EU9-clxTh4A",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=EU9-clxTh4A&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=EU9-clxTh4A&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:29",
                    "second": 269
                },
                {
                    "SongTitle": "斷了的弦",
                    "SongID": "x4cDhhnSzLg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=x4cDhhnSzLg&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=x4cDhhnSzLg&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:57",
                    "second": 297
                },
                {
                    "SongTitle": "浪漫手機",
                    "SongID": "6Gse3_wBULE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=6Gse3_wBULE&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=6Gse3_wBULE&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:00",
                    "second": 240
                },
                {
                    "SongTitle": "錯過的煙火",
                    "SongID": "wwUN9NWXcnY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=wwUN9NWXcnY&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=wwUN9NWXcnY&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:18",
                    "second": 258
                },
                {
                    "SongTitle": "粉色海洋",
                    "SongID": "vEZCoe9GJFk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=vEZCoe9GJFk&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=vEZCoe9GJFk&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:07",
                    "second": 187
                },
                {
                    "SongTitle": "夜的第七章",
                    "SongID": "VwI4LwlPO3k",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=VwI4LwlPO3k&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=VwI4LwlPO3k&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:48",
                    "second": 228
                },
                {
                    "SongTitle": "園遊會",
                    "SongID": "PfCD_7340jw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=PfCD_7340jw&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=PfCD_7340jw&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:13",
                    "second": 253
                },
                {
                    "SongTitle": "白色風車",
                    "SongID": "h9Zdt0qmDhg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=h9Zdt0qmDhg&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=h9Zdt0qmDhg&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:29",
                    "second": 269
                },
                {
                    "SongTitle": "開不了口",
                    "SongID": "aQBGiwqcJ_4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=aQBGiwqcJ_4&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=aQBGiwqcJ_4&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:43",
                    "second": 283
                },
                {
                    "SongTitle": "止戰之殤",
                    "SongID": "dCjqV_PNTyk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=dCjqV_PNTyk&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=dCjqV_PNTyk&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:34",
                    "second": 274
                },
                {
                    "SongTitle": "煙花易冷",
                    "SongID": "akLc2fdLWdY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=akLc2fdLWdY&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=akLc2fdLWdY&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:23",
                    "second": 263
                },
                {
                    "SongTitle": "最長的電影",
                    "SongID": "GXn2KV2zxNY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=GXn2KV2zxNY&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=GXn2KV2zxNY&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:01",
                    "second": 241
                },
                {
                    "SongTitle": "本草綱目",
                    "SongID": "e0ZEiXiIR9o",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=e0ZEiXiIR9o&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=e0ZEiXiIR9o&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:16",
                    "second": 256
                },
                {
                    "SongTitle": "擱淺",
                    "SongID": "XFGbwiHWovI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=XFGbwiHWovI&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=XFGbwiHWovI&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:21",
                    "second": 261
                },
                {
                    "SongTitle": "大笨鐘",
                    "SongID": "wGkCG-gAYYI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=wGkCG-gAYYI&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=wGkCG-gAYYI&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:02",
                    "second": 242
                },
                {
                    "SongTitle": "東風破",
                    "SongID": "XAa8eDe48TI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=XAa8eDe48TI&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=XAa8eDe48TI&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "5:15",
                    "second": 315
                },
                {
                    "SongTitle": "愛情廢柴",
                    "SongID": "vFBSMhRfGdQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=vFBSMhRfGdQ&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=vFBSMhRfGdQ&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:45",
                    "second": 285
                },
                {
                    "SongTitle": "妳聽得到",
                    "SongID": "kXmM_qiOwrs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=kXmM_qiOwrs&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=kXmM_qiOwrs&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:50",
                    "second": 230
                },
                {
                    "SongTitle": "超人不會飛",
                    "SongID": "Lq-xqBLiAiA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Lq-xqBLiAiA&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=Lq-xqBLiAiA&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:59",
                    "second": 299
                },
                {
                    "SongTitle": "星晴",
                    "SongID": "_mr8RmLS1Vg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=_mr8RmLS1Vg&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=_mr8RmLS1Vg&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:19",
                    "second": 259
                },
                {
                    "SongTitle": "反方向的鐘",
                    "SongID": "hjQFrD1Vg7g",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=hjQFrD1Vg7g&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=hjQFrD1Vg7g&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:17",
                    "second": 257
                },
                {
                    "SongTitle": "飄移",
                    "SongID": "UGxJyQKYuas",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=UGxJyQKYuas&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=UGxJyQKYuas&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:04",
                    "second": 244
                },
                {
                    "SongTitle": "聽爸爸的話",
                    "SongID": "-Aae5emEz38",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=-Aae5emEz38&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=-Aae5emEz38&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:23",
                    "second": 263
                },
                {
                    "SongTitle": "甜甜的",
                    "SongID": "l1ufPHu06HY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=l1ufPHu06HY&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=l1ufPHu06HY&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:03",
                    "second": 243
                },
                {
                    "SongTitle": "爺爺泡的茶",
                    "SongID": "M0EV2PpGyzM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=M0EV2PpGyzM&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=M0EV2PpGyzM&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:58",
                    "second": 238
                },
                {
                    "SongTitle": "Mine Mine",
                    "SongID": "5_CrTHSp8ts",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=5_CrTHSp8ts&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=5_CrTHSp8ts&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:28",
                    "second": 268
                },
                {
                    "SongTitle": "愛你沒差",
                    "SongID": "Gx-SOE302Ys",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Gx-SOE302Ys&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=Gx-SOE302Ys&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:40",
                    "second": 280
                },
                {
                    "SongTitle": "黑色幽默",
                    "SongID": "KBI5DDxEinI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=KBI5DDxEinI&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=KBI5DDxEinI&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:43",
                    "second": 283
                },
                {
                    "SongTitle": "世界末日",
                    "SongID": "qd5brxO2eTk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=qd5brxO2eTk&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=qd5brxO2eTk&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:25",
                    "second": 265
                },
                {
                    "SongTitle": "我要夏天",
                    "SongID": "9jI9LD-A4MQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=9jI9LD-A4MQ&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=9jI9LD-A4MQ&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:39",
                    "second": 219
                },
                {
                    "SongTitle": "不愛我就拉倒",
                    "SongID": "_uH2l7RBNnI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=_uH2l7RBNnI&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=_uH2l7RBNnI&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:07",
                    "second": 247
                },
                {
                    "SongTitle": "外婆",
                    "SongID": "Yg3Qs5tNSWE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Yg3Qs5tNSWE&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=Yg3Qs5tNSWE&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:02",
                    "second": 242
                },
                {
                    "SongTitle": "雙截棍",
                    "SongID": "5OOa_TX9NoM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=5OOa_TX9NoM&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=5OOa_TX9NoM&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:21",
                    "second": 201
                },
                {
                    "SongTitle": "傻笑",
                    "SongID": "Ob-Ip9uI7TU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Ob-Ip9uI7TU&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=Ob-Ip9uI7TU&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:49",
                    "second": 289
                },
                {
                    "SongTitle": "哪裡都是你",
                    "SongID": "vnBI03SghrI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=vnBI03SghrI&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=vnBI03SghrI&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:39",
                    "second": 279
                },
                {
                    "SongTitle": "心雨",
                    "SongID": "R5X2LdJX1XM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=R5X2LdJX1XM&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=R5X2LdJX1XM&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:05",
                    "second": 185
                },
                {
                    "SongTitle": "一點點",
                    "SongID": "7g_wiHn8Ltc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=7g_wiHn8Ltc&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=7g_wiHn8Ltc&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:41",
                    "second": 221
                },
                {
                    "SongTitle": "愛的飛行日記",
                    "SongID": "OY9X_2P7ptw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=OY9X_2P7ptw&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=OY9X_2P7ptw&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:14",
                    "second": 254
                },
                {
                    "SongTitle": "公主病",
                    "SongID": "760EiXR2E1s",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=760EiXR2E1s&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=760EiXR2E1s&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:38",
                    "second": 218
                },
                {
                    "SongTitle": "上海 一九四三",
                    "SongID": "38HdYl9JLXA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=38HdYl9JLXA&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=38HdYl9JLXA&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:15",
                    "second": 195
                },
                {
                    "SongTitle": "她的睫毛",
                    "SongID": "AUO__poQLok",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=AUO__poQLok&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=AUO__poQLok&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:52",
                    "second": 232
                },
                {
                    "SongTitle": "分裂",
                    "SongID": "6SxdYm2Yyzc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=6SxdYm2Yyzc&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=6SxdYm2Yyzc&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:12",
                    "second": 252
                },
                {
                    "SongTitle": "倒帶",
                    "SongID": "5IcwnWPr_eM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=5IcwnWPr_eM&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=5IcwnWPr_eM&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:36",
                    "second": 276
                },
                {
                    "SongTitle": "說好的幸福呢+淘汰+青花瓷",
                    "SongID": "f8rBXcRHmWo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=f8rBXcRHmWo&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=f8rBXcRHmWo&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:44",
                    "second": 224
                },
                {
                    "SongTitle": "周大俠",
                    "SongID": "qJBSSZOTjmY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=qJBSSZOTjmY&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=qJBSSZOTjmY&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "2:14",
                    "second": 134
                },
                {
                    "SongTitle": "天涯過客",
                    "SongID": "Cf0j5LzSOy0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Cf0j5LzSOy0&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "SongUrl": "https://youtube.com/watch?v=Cf0j5LzSOy0&list=OLAK5uy_lsLIti8r4lQPmdUdikOs-7pBd02nM4F1o",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:13",
                    "second": 253
                }
            ]
        }
    ]
    return { data };
});
