export default defineEventHandler((event) => {
    const data = [
        {
            "ListName": "KKBOX 歷年排行榜週冠軍歌曲",
            "SongList": [
                {
                    "SongTitle": "曖昧",
                    "SongID": "mebzXfWi87E",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=mebzXfWi87E&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=mebzXfWi87E&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "楊丞琳",
                    "ArtistID": "UC0WDze0vAMrLxULTWMlSuRA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC0WDze0vAMrLxULTWMlSuRA",
                    "ArtistUrl": "https://youtube.com/channel/UC0WDze0vAMrLxULTWMlSuRA",
                    "time": "4:47",
                    "second": 287
                },
                {
                    "SongTitle": "曖昧",
                    "SongID": "mebzXfWi87E",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=mebzXfWi87E&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=mebzXfWi87E&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "楊丞琳",
                    "ArtistID": "UC0WDze0vAMrLxULTWMlSuRA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC0WDze0vAMrLxULTWMlSuRA",
                    "ArtistUrl": "https://youtube.com/channel/UC0WDze0vAMrLxULTWMlSuRA",
                    "time": "4:47",
                    "second": 287
                },
                {
                    "SongTitle": "夜曲",
                    "SongID": "6Q0Pd53mojY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=6Q0Pd53mojY&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=6Q0Pd53mojY&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:54",
                    "second": 234
                },
                {
                    "SongTitle": "張棟樑 Nicholas Teo -  寂寞邊界 Loneliness (官方完整KARAOKE版MV)",
                    "SongID": "LhWTLeFK-sU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=LhWTLeFK-sU&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=LhWTLeFK-sU&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "Timeless Music",
                    "ArtistID": "UCJCg4enuciH7IlFIBaJ_NEQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCJCg4enuciH7IlFIBaJ_NEQ",
                    "ArtistUrl": "https://youtube.com/channel/UCJCg4enuciH7IlFIBaJ_NEQ",
                    "time": "4:35",
                    "second": 275
                },
                {
                    "SongTitle": "天灰",
                    "SongID": "98MngruRenY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=98MngruRenY&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=98MngruRenY&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "S.H.E",
                    "ArtistID": "UCGH6l-Hozjs8vSW83e4u-Gw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCGH6l-Hozjs8vSW83e4u-Gw",
                    "ArtistUrl": "https://youtube.com/channel/UCGH6l-Hozjs8vSW83e4u-Gw",
                    "time": "4:03",
                    "second": 243
                },
                {
                    "SongTitle": "周杰倫&Lara - 珊瑚海 HD",
                    "SongID": "8Q9SVzhwjus",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=8Q9SVzhwjus&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=8Q9SVzhwjus&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "Polo Wong",
                    "ArtistID": "UC3hPmeBEvNLp3oF1zaJgcrw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC3hPmeBEvNLp3oF1zaJgcrw",
                    "ArtistUrl": "https://youtube.com/channel/UC3hPmeBEvNLp3oF1zaJgcrw",
                    "time": "4:22",
                    "second": 262
                },
                {
                    "SongTitle": "王心凌 Cyndi Wang \" 睫毛彎彎 \"(2005)HD",
                    "SongID": "orqdRGQuhEs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=orqdRGQuhEs&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=orqdRGQuhEs&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "まさる",
                    "ArtistID": "UCiov4gseFC_xwVUhmjXnAxQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiov4gseFC_xwVUhmjXnAxQ",
                    "ArtistUrl": "https://youtube.com/channel/UCiov4gseFC_xwVUhmjXnAxQ",
                    "time": "4:03",
                    "second": 243
                },
                {
                    "SongTitle": "王力宏 Kiss Goodbye (Official Video Karaoke)",
                    "SongID": "Clf30eGO5Eg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Clf30eGO5Eg&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=Clf30eGO5Eg&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "金曲年代GOLDEN ERA",
                    "ArtistID": "UCMZNSG_3ka6q34wKSw8uDsg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCMZNSG_3ka6q34wKSw8uDsg",
                    "ArtistUrl": "https://youtube.com/channel/UCMZNSG_3ka6q34wKSw8uDsg",
                    "time": "4:20",
                    "second": 260
                },
                {
                    "SongTitle": "握不住的他",
                    "SongID": "cwHhdtAPIKA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=cwHhdtAPIKA&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=cwHhdtAPIKA&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "蕭蕭",
                    "ArtistID": "UCHvSTO8-Ic4O2_UmWDMJW6w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCHvSTO8-Ic4O2_UmWDMJW6w",
                    "ArtistUrl": "https://youtube.com/channel/UCHvSTO8-Ic4O2_UmWDMJW6w",
                    "time": "3:22",
                    "second": 202
                },
                {
                    "SongTitle": "張惠妹 A-Mei - 人質 Hostage (official 官方完整版MV)",
                    "SongID": "o4JrzNdpKw4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=o4JrzNdpKw4&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=o4JrzNdpKw4&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "Timeless Music",
                    "ArtistID": "UCJCg4enuciH7IlFIBaJ_NEQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCJCg4enuciH7IlFIBaJ_NEQ",
                    "ArtistUrl": "https://youtube.com/channel/UCJCg4enuciH7IlFIBaJ_NEQ",
                    "time": "3:49",
                    "second": 229
                },
                {
                    "SongTitle": "曹操",
                    "SongID": "3J_bkgexrE8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=3J_bkgexrE8&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=3J_bkgexrE8&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "林俊傑",
                    "ArtistID": "UCUJ3KuIIgvh8eVItvb-EdFQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCUJ3KuIIgvh8eVItvb-EdFQ",
                    "ArtistUrl": "https://youtube.com/channel/UCUJ3KuIIgvh8eVItvb-EdFQ",
                    "time": "4:43",
                    "second": 283
                },
                {
                    "SongTitle": "張惠妹 A-Mei - 我要快樂？I Want Happiness (official 官方完整版MV)",
                    "SongID": "NilgON1msY8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=NilgON1msY8&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=NilgON1msY8&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "Timeless Music",
                    "ArtistID": "UCJCg4enuciH7IlFIBaJ_NEQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCJCg4enuciH7IlFIBaJ_NEQ",
                    "ArtistUrl": "https://youtube.com/channel/UCJCg4enuciH7IlFIBaJ_NEQ",
                    "time": "4:52",
                    "second": 292
                },
                {
                    "SongTitle": "光良-約定",
                    "SongID": "tvOg47wf0GQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=tvOg47wf0GQ&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=tvOg47wf0GQ&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "calfunz",
                    "ArtistID": "UCIgZws4nr_78PyoUIR22X8w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCIgZws4nr_78PyoUIR22X8w",
                    "ArtistUrl": "https://youtube.com/channel/UCIgZws4nr_78PyoUIR22X8w",
                    "time": "7:31",
                    "second": 451
                },
                {
                    "SongTitle": "原來",
                    "SongID": "6YxdHy-5FzE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=6YxdHy-5FzE&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=6YxdHy-5FzE&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "林俊傑",
                    "ArtistID": "UCUJ3KuIIgvh8eVItvb-EdFQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCUJ3KuIIgvh8eVItvb-EdFQ",
                    "ArtistUrl": "https://youtube.com/channel/UCUJ3KuIIgvh8eVItvb-EdFQ",
                    "time": "3:43",
                    "second": 223
                },
                {
                    "SongTitle": "楊丞琳 過敏 (Official Video Karaoke)",
                    "SongID": "Emn3M-2Hi4o",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Emn3M-2Hi4o&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=Emn3M-2Hi4o&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "金曲年代GOLDEN ERA",
                    "ArtistID": "UCMZNSG_3ka6q34wKSw8uDsg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCMZNSG_3ka6q34wKSw8uDsg",
                    "ArtistUrl": "https://youtube.com/channel/UCMZNSG_3ka6q34wKSw8uDsg",
                    "time": "4:19",
                    "second": 259
                },
                {
                    "SongTitle": "給我你的愛",
                    "SongID": "9CInTGdSTf0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=9CInTGdSTf0&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=9CInTGdSTf0&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "呂建中",
                    "ArtistID": "UCDS0OcKRmAOKy4IuetXieEg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCDS0OcKRmAOKy4IuetXieEg",
                    "ArtistUrl": "https://youtube.com/channel/UCDS0OcKRmAOKy4IuetXieEg",
                    "time": "4:36",
                    "second": 276
                },
                {
                    "SongTitle": "舞孃",
                    "SongID": "0EN3MnGEBXk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=0EN3MnGEBXk&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=0EN3MnGEBXk&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "蔡依林",
                    "ArtistID": "UC9dLsF7Ss7Wg0kR6TiIWiXg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC9dLsF7Ss7Wg0kR6TiIWiXg",
                    "ArtistUrl": "https://youtube.com/channel/UC9dLsF7Ss7Wg0kR6TiIWiXg",
                    "time": "3:42",
                    "second": 222
                },
                {
                    "SongTitle": "假裝",
                    "SongID": "_34cgR4oUw4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=_34cgR4oUw4&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=_34cgR4oUw4&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "蔡依林",
                    "ArtistID": "UC9dLsF7Ss7Wg0kR6TiIWiXg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC9dLsF7Ss7Wg0kR6TiIWiXg",
                    "ArtistUrl": "https://youtube.com/channel/UC9dLsF7Ss7Wg0kR6TiIWiXg",
                    "time": "5:25",
                    "second": 325
                },
                {
                    "SongTitle": "馬德里不思議",
                    "SongID": "E7Tz8kWaGhA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=E7Tz8kWaGhA&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=E7Tz8kWaGhA&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "蔡依林",
                    "ArtistID": "UC9dLsF7Ss7Wg0kR6TiIWiXg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC9dLsF7Ss7Wg0kR6TiIWiXg",
                    "ArtistUrl": "https://youtube.com/channel/UC9dLsF7Ss7Wg0kR6TiIWiXg",
                    "time": "3:33",
                    "second": 213
                },
                {
                    "SongTitle": "范瑋琪 - 一個像夏天一個像秋天",
                    "SongID": "IhWjeCI7v_g",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=IhWjeCI7v_g&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=IhWjeCI7v_g&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "uesugi94",
                    "ArtistID": "UCmrCGI5AxjTRG5E-CHFQeMw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCmrCGI5AxjTRG5E-CHFQeMw",
                    "ArtistUrl": "https://youtube.com/channel/UCmrCGI5AxjTRG5E-CHFQeMw",
                    "time": "4:10",
                    "second": 250
                },
                {
                    "SongTitle": "李聖傑 Sam Lee【眼底星空】Official Music Video",
                    "SongID": "VLp9Nb2dXW8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=VLp9Nb2dXW8&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=VLp9Nb2dXW8&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "李聖傑",
                    "ArtistID": "UCp6Mowp_ZCQojg25ICvOAAQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCp6Mowp_ZCQojg25ICvOAAQ",
                    "ArtistUrl": "https://youtube.com/channel/UCp6Mowp_ZCQojg25ICvOAAQ",
                    "time": "4:26",
                    "second": 266
                },
                {
                    "SongTitle": "【导师片段】庾澄庆《静静的》《中国新歌声》国庆演唱会 SING!CHINA SP.2 20161003 [浙江卫视官方超清1080P]",
                    "SongID": "8182ot3ZgEw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=8182ot3ZgEw&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=8182ot3ZgEw&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "中國浙江衛視官方頻道 Zhejiang STV Official Channel - 歡迎訂閱 -",
                    "ArtistID": "UCp8cPvx_Od76EL66vvCnhRA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCp8cPvx_Od76EL66vvCnhRA",
                    "ArtistUrl": "https://youtube.com/channel/UCp8cPvx_Od76EL66vvCnhRA",
                    "time": "3:50",
                    "second": 230
                },
                {
                    "SongTitle": "觸電",
                    "SongID": "a5Fsia3hKyo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=a5Fsia3hKyo&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=a5Fsia3hKyo&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "S.H.E",
                    "ArtistID": "UCGH6l-Hozjs8vSW83e4u-Gw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCGH6l-Hozjs8vSW83e4u-Gw",
                    "ArtistUrl": "https://youtube.com/channel/UCGH6l-Hozjs8vSW83e4u-Gw",
                    "time": "4:25",
                    "second": 265
                },
                {
                    "SongTitle": "F.I.R. 飛兒樂團 - 天天夜夜 (official 官方完整版MV)",
                    "SongID": "HXmZiylxAsw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=HXmZiylxAsw&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=HXmZiylxAsw&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "F.I.R.飛兒樂團",
                    "ArtistID": "UCULDopO9sNa9kBs5QnFgmEQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCULDopO9sNa9kBs5QnFgmEQ",
                    "ArtistUrl": "https://youtube.com/channel/UCULDopO9sNa9kBs5QnFgmEQ",
                    "time": "5:01",
                    "second": 301
                },
                {
                    "SongTitle": "周杰倫 Jay Chou【千里之外 Far Away (feat.費玉清 Fei Yu-ching)】-Official Music Video",
                    "SongID": "ocDo3ySyHSI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ocDo3ySyHSI&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=ocDo3ySyHSI&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:32",
                    "second": 272
                },
                {
                    "SongTitle": "親親",
                    "SongID": "k0r3zW4dEtk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=k0r3zW4dEtk&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=k0r3zW4dEtk&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "梁靜茹",
                    "ArtistID": "UC8viexI7VBM6p632pCfTWRg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC8viexI7VBM6p632pCfTWRg",
                    "ArtistUrl": "https://youtube.com/channel/UC8viexI7VBM6p632pCfTWRg",
                    "time": "4:07",
                    "second": 247
                },
                {
                    "SongTitle": "卓文萱 Genie Chuo&曹格 Gary Chaw【梁山伯與茱麗葉】華視偶像劇「戀愛女王」片尾曲 Official Music Video",
                    "SongID": "0NuKS4gK0Lw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=0NuKS4gK0Lw&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=0NuKS4gK0Lw&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "阿牛",
                    "ArtistID": "UCxmdSuMgNGDoJFwi6vJTuvQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCxmdSuMgNGDoJFwi6vJTuvQ",
                    "ArtistUrl": "https://youtube.com/channel/UCxmdSuMgNGDoJFwi6vJTuvQ",
                    "time": "3:59",
                    "second": 239
                },
                {
                    "SongTitle": "[avex官方]羅志祥 精舞門 (MV完整版)",
                    "SongID": "3WAgjt-cDQg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=3WAgjt-cDQg&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=3WAgjt-cDQg&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "愛貝克思 avex taiwan",
                    "ArtistID": "UCH1AHDav6J-2XYkl243Uj3Q",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCH1AHDav6J-2XYkl243Uj3Q",
                    "ArtistUrl": "https://youtube.com/channel/UCH1AHDav6J-2XYkl243Uj3Q",
                    "time": "4:31",
                    "second": 271
                },
                {
                    "SongTitle": "[avex官方]羅志祥 好朋友 (MV完整版)",
                    "SongID": "fX7IuZ74oQs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=fX7IuZ74oQs&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=fX7IuZ74oQs&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "愛貝克思 avex taiwan",
                    "ArtistID": "UCH1AHDav6J-2XYkl243Uj3Q",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCH1AHDav6J-2XYkl243Uj3Q",
                    "ArtistUrl": "https://youtube.com/channel/UCH1AHDav6J-2XYkl243Uj3Q",
                    "time": "4:25",
                    "second": 265
                },
                {
                    "SongTitle": "無神論 (英文版)",
                    "SongID": "pTKDP-2WAJE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=pTKDP-2WAJE&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=pTKDP-2WAJE&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "黃立行",
                    "ArtistID": "UC2Tl3yGEREKC0A9luaGuNDg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC2Tl3yGEREKC0A9luaGuNDg",
                    "ArtistUrl": "https://youtube.com/channel/UC2Tl3yGEREKC0A9luaGuNDg",
                    "time": "3:46",
                    "second": 226
                },
                {
                    "SongTitle": "不痛",
                    "SongID": "zXHqzoroAj4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=zXHqzoroAj4&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=zXHqzoroAj4&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "張韶涵",
                    "ArtistID": "UCKeK5Xj-iCfLOZvMDm3aIkw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCKeK5Xj-iCfLOZvMDm3aIkw",
                    "ArtistUrl": "https://youtube.com/channel/UCKeK5Xj-iCfLOZvMDm3aIkw",
                    "time": "4:06",
                    "second": 246
                },
                {
                    "SongTitle": "羅志祥 - 愛*轉角 MV",
                    "SongID": "xFT8H2QsaJg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=xFT8H2QsaJg&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=xFT8H2QsaJg&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "charli0n",
                    "ArtistID": "UCKo7k1Z4EOijgjlG6xDGpFA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCKo7k1Z4EOijgjlG6xDGpFA",
                    "ArtistUrl": "https://youtube.com/channel/UCKo7k1Z4EOijgjlG6xDGpFA",
                    "time": "4:54",
                    "second": 294
                },
                {
                    "SongTitle": "專屬天使",
                    "SongID": "QdWRuFQZ8RI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=QdWRuFQZ8RI&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=QdWRuFQZ8RI&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "呂建中",
                    "ArtistID": "UCDS0OcKRmAOKy4IuetXieEg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCDS0OcKRmAOKy4IuetXieEg",
                    "ArtistUrl": "https://youtube.com/channel/UCDS0OcKRmAOKy4IuetXieEg",
                    "time": "5:10",
                    "second": 310
                },
                {
                    "SongTitle": "逆光自製MV",
                    "SongID": "2oNN37dbQM8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=2oNN37dbQM8&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=2oNN37dbQM8&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "sunnseea",
                    "ArtistID": "UCdYhLOz7H4z7sz5fOPj9BxQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCdYhLOz7H4z7sz5fOPj9BxQ",
                    "ArtistUrl": "https://youtube.com/channel/UCdYhLOz7H4z7sz5fOPj9BxQ",
                    "time": "4:56",
                    "second": 296
                },
                {
                    "SongTitle": "我懷念的",
                    "SongID": "3Xj6QoLmoF0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=3Xj6QoLmoF0&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=3Xj6QoLmoF0&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "孫燕姿",
                    "ArtistID": "UCLFS9T3qlBLQsVlLASHC1ug",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCLFS9T3qlBLQsVlLASHC1ug",
                    "ArtistUrl": "https://youtube.com/channel/UCLFS9T3qlBLQsVlLASHC1ug",
                    "time": "4:55",
                    "second": 295
                },
                {
                    "SongTitle": "Angela Zhang & Sodagreen -  藍眼睛 - Blue Eyes",
                    "SongID": "eN9wmXIgLBI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=eN9wmXIgLBI&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=eN9wmXIgLBI&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "xXxAngelaZhangxXx",
                    "ArtistID": "UCsjWqxbxCtS-Gvm1j9SLY0A",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCsjWqxbxCtS-Gvm1j9SLY0A",
                    "ArtistUrl": "https://youtube.com/channel/UCsjWqxbxCtS-Gvm1j9SLY0A",
                    "time": "4:18",
                    "second": 258
                },
                {
                    "SongTitle": "陳奕迅 - 淘汰 HD",
                    "SongID": "d5rsn0Yl0Ns",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=d5rsn0Yl0Ns&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=d5rsn0Yl0Ns&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "Polo Wong",
                    "ArtistID": "UC3hPmeBEvNLp3oF1zaJgcrw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC3hPmeBEvNLp3oF1zaJgcrw",
                    "ArtistUrl": "https://youtube.com/channel/UC3hPmeBEvNLp3oF1zaJgcrw",
                    "time": "4:56",
                    "second": 296
                },
                {
                    "SongTitle": "陈奕迅 - 爱情转移 MV",
                    "SongID": "71IQ60O0xV4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=71IQ60O0xV4&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=71IQ60O0xV4&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "meng0217",
                    "ArtistID": "UCLkoQFJu6Ql0k79HVR2PwwA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCLkoQFJu6Ql0k79HVR2PwwA",
                    "ArtistUrl": "https://youtube.com/channel/UCLkoQFJu6Ql0k79HVR2PwwA",
                    "time": "4:17",
                    "second": 257
                },
                {
                    "SongTitle": "五月天",
                    "SongID": "SstOzs4y6Eg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=SstOzs4y6Eg&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=SstOzs4y6Eg&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "S.H.E",
                    "ArtistID": "UCGH6l-Hozjs8vSW83e4u-Gw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCGH6l-Hozjs8vSW83e4u-Gw",
                    "ArtistUrl": "https://youtube.com/channel/UCGH6l-Hozjs8vSW83e4u-Gw",
                    "time": "3:53",
                    "second": 233
                },
                {
                    "SongTitle": "背叛",
                    "SongID": "xHsSWiLsIRY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=xHsSWiLsIRY&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=xHsSWiLsIRY&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "曹格",
                    "ArtistID": "UCUvbtTS_ngEj8QRuzjCiFfQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCUvbtTS_ngEj8QRuzjCiFfQ",
                    "ArtistUrl": "https://youtube.com/channel/UCUvbtTS_ngEj8QRuzjCiFfQ",
                    "time": "5:18",
                    "second": 318
                },
                {
                    "SongTitle": "不能說的秘密",
                    "SongID": "uIWypArI73w",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=uIWypArI73w&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=uIWypArI73w&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "5:36",
                    "second": 336
                },
                {
                    "SongTitle": "我不想忘記你",
                    "SongID": "K-xda8e2FLc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=K-xda8e2FLc&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=K-xda8e2FLc&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "郭靜",
                    "ArtistID": "UCYYhiWcofKhHQuqYD7BUoRw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCYYhiWcofKhHQuqYD7BUoRw",
                    "ArtistUrl": "https://youtube.com/channel/UCYYhiWcofKhHQuqYD7BUoRw",
                    "time": "4:26",
                    "second": 266
                },
                {
                    "SongTitle": "Have You Heard Lately?",
                    "SongID": "xrUyk79DLbg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=xrUyk79DLbg&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=xrUyk79DLbg&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "張惠妹",
                    "ArtistID": "UC5M7vIbPTCOMVF3lTtbeO6g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC5M7vIbPTCOMVF3lTtbeO6g",
                    "ArtistUrl": "https://youtube.com/channel/UC5M7vIbPTCOMVF3lTtbeO6g",
                    "time": "5:11",
                    "second": 311
                },
                {
                    "SongTitle": "張惠妹 A-Mei -  一眼瞬間 A Moment (official官方完整版MV)",
                    "SongID": "Egrpx5g0UgI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Egrpx5g0UgI&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=Egrpx5g0UgI&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "Timeless Music",
                    "ArtistID": "UCJCg4enuciH7IlFIBaJ_NEQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCJCg4enuciH7IlFIBaJ_NEQ",
                    "ArtistUrl": "https://youtube.com/channel/UCJCg4enuciH7IlFIBaJ_NEQ",
                    "time": "5:54",
                    "second": 354
                },
                {
                    "SongTitle": "月牙灣",
                    "SongID": "sZXE20ScmPY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=sZXE20ScmPY&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=sZXE20ScmPY&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "F.I.R.飛兒樂團",
                    "ArtistID": "UCULDopO9sNa9kBs5QnFgmEQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCULDopO9sNa9kBs5QnFgmEQ",
                    "ArtistUrl": "https://youtube.com/channel/UCULDopO9sNa9kBs5QnFgmEQ",
                    "time": "5:13",
                    "second": 313
                },
                {
                    "SongTitle": "特務J",
                    "SongID": "gG6q90HXSkw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=gG6q90HXSkw&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=gG6q90HXSkw&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "蔡依林",
                    "ArtistID": "UC9dLsF7Ss7Wg0kR6TiIWiXg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC9dLsF7Ss7Wg0kR6TiIWiXg",
                    "ArtistUrl": "https://youtube.com/channel/UC9dLsF7Ss7Wg0kR6TiIWiXg",
                    "time": "3:35",
                    "second": 215
                },
                {
                    "SongTitle": "是非題",
                    "SongID": "UYjNLDuIoWc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=UYjNLDuIoWc&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=UYjNLDuIoWc&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "范瑋琪",
                    "ArtistID": "UC49ijorxlIXpZRAC6wEQYWQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC49ijorxlIXpZRAC6wEQYWQ",
                    "ArtistUrl": "https://youtube.com/channel/UC49ijorxlIXpZRAC6wEQYWQ",
                    "time": "4:07",
                    "second": 247
                },
                {
                    "SongTitle": "李玖哲Nicky Lee-想太多Think Too Much-完整版MV.wmv",
                    "SongID": "fVtmLnmkrp4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=fVtmLnmkrp4&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=fVtmLnmkrp4&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "Phạm Kỳ Anh",
                    "ArtistID": "UCoSKuejLZ3_TYc_EScIO1BA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCoSKuejLZ3_TYc_EScIO1BA",
                    "ArtistUrl": "https://youtube.com/channel/UCoSKuejLZ3_TYc_EScIO1BA",
                    "time": "4:30",
                    "second": 270
                },
                {
                    "SongTitle": "楊宗緯 Aska Yang [ 多餘 (愛 星光精選 [昨天今天明天] )] Official Music Video",
                    "SongID": "HF4VdAebmng",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=HF4VdAebmng&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=HF4VdAebmng&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "楊宗緯",
                    "ArtistID": "UC3foh7LHNHBPpcA53e3pikA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC3foh7LHNHBPpcA53e3pikA",
                    "ArtistUrl": "https://youtube.com/channel/UC3foh7LHNHBPpcA53e3pikA",
                    "time": "3:33",
                    "second": 213
                },
                {
                    "SongTitle": "彩虹",
                    "SongID": "WxZvXPTBC0A",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=WxZvXPTBC0A&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=WxZvXPTBC0A&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:33",
                    "second": 273
                },
                {
                    "SongTitle": "我不會唱歌",
                    "SongID": "0-40QqcRAFU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=0-40QqcRAFU&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=0-40QqcRAFU&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "羅志祥",
                    "ArtistID": "UC4_QhSjjcXMO2mxZbu-8oFA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC4_QhSjjcXMO2mxZbu-8oFA",
                    "ArtistUrl": "https://youtube.com/channel/UC4_QhSjjcXMO2mxZbu-8oFA",
                    "time": "6:44",
                    "second": 404
                },
                {
                    "SongTitle": "不想懂得",
                    "SongID": "YaJWn-Spxfc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=YaJWn-Spxfc&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=YaJWn-Spxfc&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "張韶涵",
                    "ArtistID": "UCKeK5Xj-iCfLOZvMDm3aIkw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCKeK5Xj-iCfLOZvMDm3aIkw",
                    "ArtistUrl": "https://youtube.com/channel/UCKeK5Xj-iCfLOZvMDm3aIkw",
                    "time": "4:43",
                    "second": 283
                },
                {
                    "SongTitle": "親愛的那不是愛情",
                    "SongID": "HwF1i_6Iwp8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=HwF1i_6Iwp8&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=HwF1i_6Iwp8&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "張韶涵",
                    "ArtistID": "UCKeK5Xj-iCfLOZvMDm3aIkw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCKeK5Xj-iCfLOZvMDm3aIkw",
                    "ArtistUrl": "https://youtube.com/channel/UCKeK5Xj-iCfLOZvMDm3aIkw",
                    "time": "4:18",
                    "second": 258
                },
                {
                    "SongTitle": "無辜",
                    "SongID": "VHyh6JL2RDU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=VHyh6JL2RDU&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=VHyh6JL2RDU&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "曹格",
                    "ArtistID": "UCUvbtTS_ngEj8QRuzjCiFfQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCUvbtTS_ngEj8QRuzjCiFfQ",
                    "ArtistUrl": "https://youtube.com/channel/UCUvbtTS_ngEj8QRuzjCiFfQ",
                    "time": "6:26",
                    "second": 386
                },
                {
                    "SongTitle": "吳克群 - 為你寫詩 KTV",
                    "SongID": "ML1R6wl_dlE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ML1R6wl_dlE&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=ML1R6wl_dlE&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "superhinghing",
                    "ArtistID": "UCCtG_DjrwfIsQEcEqhXRgwg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCCtG_DjrwfIsQEcEqhXRgwg",
                    "ArtistUrl": "https://youtube.com/channel/UCCtG_DjrwfIsQEcEqhXRgwg",
                    "time": "4:59",
                    "second": 299
                },
                {
                    "SongTitle": "獨家記憶",
                    "SongID": "K4i7UfFSr8k",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=K4i7UfFSr8k&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=K4i7UfFSr8k&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "陳小春",
                    "ArtistID": "UCF2B6uuN0HV8jmlxx9e4BpQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCF2B6uuN0HV8jmlxx9e4BpQ",
                    "ArtistUrl": "https://youtube.com/channel/UCF2B6uuN0HV8jmlxx9e4BpQ",
                    "time": "5:05",
                    "second": 305
                },
                {
                    "SongTitle": "累格",
                    "SongID": "0QJo4FmFgis",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=0QJo4FmFgis&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=0QJo4FmFgis&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "戴愛玲",
                    "ArtistID": "UChrZ-zEgQcYPnWq78uVJmhA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UChrZ-zEgQcYPnWq78uVJmhA",
                    "ArtistUrl": "https://youtube.com/channel/UChrZ-zEgQcYPnWq78uVJmhA",
                    "time": "5:31",
                    "second": 331
                },
                {
                    "SongTitle": "下一個天亮",
                    "SongID": "AEUmLttrY5s",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=AEUmLttrY5s&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=AEUmLttrY5s&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "郭靜",
                    "ArtistID": "UCYYhiWcofKhHQuqYD7BUoRw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCYYhiWcofKhHQuqYD7BUoRw",
                    "ArtistUrl": "https://youtube.com/channel/UCYYhiWcofKhHQuqYD7BUoRw",
                    "time": "5:15",
                    "second": 315
                },
                {
                    "SongTitle": "收藏",
                    "SongID": "UG459pAsokE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=UG459pAsokE&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=UG459pAsokE&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "蕭敬騰",
                    "ArtistID": "UCvjGf4upqUNaqi524A5AHIw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCvjGf4upqUNaqi524A5AHIw",
                    "ArtistUrl": "https://youtube.com/channel/UCvjGf4upqUNaqi524A5AHIw",
                    "time": "4:55",
                    "second": 295
                },
                {
                    "SongTitle": "王子的新衣",
                    "SongID": "CGfZNAOkpkk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=CGfZNAOkpkk&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=CGfZNAOkpkk&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "蕭敬騰",
                    "ArtistID": "UCvjGf4upqUNaqi524A5AHIw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCvjGf4upqUNaqi524A5AHIw",
                    "ArtistUrl": "https://youtube.com/channel/UCvjGf4upqUNaqi524A5AHIw",
                    "time": "4:28",
                    "second": 268
                },
                {
                    "SongTitle": "南拳媽媽 - 下雨天",
                    "SongID": "nXCm67L4qAU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=nXCm67L4qAU&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=nXCm67L4qAU&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "yanfunc1",
                    "ArtistID": "UCA3HhIJMHSYqWuIwJDUp21w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCA3HhIJMHSYqWuIwJDUp21w",
                    "ArtistUrl": "https://youtube.com/channel/UCA3HhIJMHSYqWuIwJDUp21w",
                    "time": "4:21",
                    "second": 261
                },
                {
                    "SongTitle": "稻香",
                    "SongID": "sHD_z90ZKV0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=sHD_z90ZKV0&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=sHD_z90ZKV0&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "3:44",
                    "second": 224
                },
                {
                    "SongTitle": "說好的幸福呢",
                    "SongID": "mLFhTFiX0uM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=mLFhTFiX0uM&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=mLFhTFiX0uM&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:17",
                    "second": 257
                },
                {
                    "SongTitle": "Heartbeat",
                    "SongID": "w41gqTFYh08",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=w41gqTFYh08&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=w41gqTFYh08&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "王力宏",
                    "ArtistID": "UCSirtpIlKNCvnrTN4i0GFvw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCSirtpIlKNCvnrTN4i0GFvw",
                    "ArtistUrl": "https://youtube.com/channel/UCSirtpIlKNCvnrTN4i0GFvw",
                    "time": "4:20",
                    "second": 260
                },
                {
                    "SongTitle": "搞笑",
                    "SongID": "F-GdoIzuWfo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=F-GdoIzuWfo&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=F-GdoIzuWfo&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "羅志祥",
                    "ArtistID": "UC4_QhSjjcXMO2mxZbu-8oFA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC4_QhSjjcXMO2mxZbu-8oFA",
                    "ArtistUrl": "https://youtube.com/channel/UC4_QhSjjcXMO2mxZbu-8oFA",
                    "time": "5:35",
                    "second": 335
                },
                {
                    "SongTitle": "沒有如果",
                    "SongID": "O4qcGzWfDsE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=O4qcGzWfDsE&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=O4qcGzWfDsE&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "梁靜茹",
                    "ArtistID": "UC8viexI7VBM6p632pCfTWRg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC8viexI7VBM6p632pCfTWRg",
                    "ArtistUrl": "https://youtube.com/channel/UC8viexI7VBM6p632pCfTWRg",
                    "time": "4:29",
                    "second": 269
                },
                {
                    "SongTitle": "空港",
                    "SongID": "eTBqP_C5UQI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=eTBqP_C5UQI&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=eTBqP_C5UQI&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "戴愛玲",
                    "ArtistID": "UChrZ-zEgQcYPnWq78uVJmhA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UChrZ-zEgQcYPnWq78uVJmhA",
                    "ArtistUrl": "https://youtube.com/channel/UChrZ-zEgQcYPnWq78uVJmhA",
                    "time": "5:02",
                    "second": 302
                },
                {
                    "SongTitle": "妥協 蔡依林 完整 MV Jolin Tsai (Compromise)",
                    "SongID": "K311Pa8mF_I",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=K311Pa8mF_I&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=K311Pa8mF_I&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "LookHereO_O",
                    "ArtistID": "UCvF4XQG5m7Wgt5ZcRZu41Ng",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCvF4XQG5m7Wgt5ZcRZu41Ng",
                    "ArtistUrl": "https://youtube.com/channel/UCvF4XQG5m7Wgt5ZcRZu41Ng",
                    "time": "4:23",
                    "second": 263
                },
                {
                    "SongTitle": "我知道",
                    "SongID": "GhMktBrHk9I",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=GhMktBrHk9I&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=GhMktBrHk9I&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "By2",
                    "ArtistID": "UCgLxgn3V4O8qXKpz3gxN-CQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCgLxgn3V4O8qXKpz3gxN-CQ",
                    "ArtistUrl": "https://youtube.com/channel/UCgLxgn3V4O8qXKpz3gxN-CQ",
                    "time": "4:55",
                    "second": 295
                },
                {
                    "SongTitle": "又圓了的月亮",
                    "SongID": "OfZfw3S_ZEk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=OfZfw3S_ZEk&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=OfZfw3S_ZEk&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "郭采潔",
                    "ArtistID": "UCfjQjYOdrpwkLNLJv1np5Pw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCfjQjYOdrpwkLNLJv1np5Pw",
                    "ArtistUrl": "https://youtube.com/channel/UCfjQjYOdrpwkLNLJv1np5Pw",
                    "time": "4:56",
                    "second": 296
                },
                {
                    "SongTitle": "如果我變成回憶",
                    "SongID": "FGsnxTkWZCU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=FGsnxTkWZCU&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=FGsnxTkWZCU&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "呂建中",
                    "ArtistID": "UCDS0OcKRmAOKy4IuetXieEg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCDS0OcKRmAOKy4IuetXieEg",
                    "ArtistUrl": "https://youtube.com/channel/UCDS0OcKRmAOKy4IuetXieEg",
                    "time": "5:15",
                    "second": 315
                },
                {
                    "SongTitle": "在樹上唱歌",
                    "SongID": "yCq3RLCn2i0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=yCq3RLCn2i0&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=yCq3RLCn2i0&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "郭靜",
                    "ArtistID": "UCYYhiWcofKhHQuqYD7BUoRw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCYYhiWcofKhHQuqYD7BUoRw",
                    "ArtistUrl": "https://youtube.com/channel/UCYYhiWcofKhHQuqYD7BUoRw",
                    "time": "4:01",
                    "second": 241
                },
                {
                    "SongTitle": "心牆",
                    "SongID": "VhCRokYVF1I",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=VhCRokYVF1I&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=VhCRokYVF1I&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "郭靜",
                    "ArtistID": "UCYYhiWcofKhHQuqYD7BUoRw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCYYhiWcofKhHQuqYD7BUoRw",
                    "ArtistUrl": "https://youtube.com/channel/UCYYhiWcofKhHQuqYD7BUoRw",
                    "time": "3:53",
                    "second": 233
                },
                {
                    "SongTitle": "王妃",
                    "SongID": "qnDlH_S4Fak",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=qnDlH_S4Fak&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=qnDlH_S4Fak&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "蕭敬騰",
                    "ArtistID": "UCvjGf4upqUNaqi524A5AHIw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCvjGf4upqUNaqi524A5AHIw",
                    "ArtistUrl": "https://youtube.com/channel/UCvjGf4upqUNaqi524A5AHIw",
                    "time": "3:40",
                    "second": 220
                },
                {
                    "SongTitle": "善男信女",
                    "SongID": "vnDlhgK8cAY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=vnDlhgK8cAY&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=vnDlhgK8cAY&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "蕭敬騰",
                    "ArtistID": "UCvjGf4upqUNaqi524A5AHIw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCvjGf4upqUNaqi524A5AHIw",
                    "ArtistUrl": "https://youtube.com/channel/UCvjGf4upqUNaqi524A5AHIw",
                    "time": "5:27",
                    "second": 327
                },
                {
                    "SongTitle": "想知道現在你好不好",
                    "SongID": "XYFTQ9tfvKw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=XYFTQ9tfvKw&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=XYFTQ9tfvKw&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "范瑋琪",
                    "ArtistID": "UC49ijorxlIXpZRAC6wEQYWQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC49ijorxlIXpZRAC6wEQYWQ",
                    "ArtistUrl": "https://youtube.com/channel/UC49ijorxlIXpZRAC6wEQYWQ",
                    "time": "4:04",
                    "second": 244
                },
                {
                    "SongTitle": "方大同-紅豆MV",
                    "SongID": "3nG--h_EJyc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=3nG--h_EJyc&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=3nG--h_EJyc&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "華納音樂 Warner Music Taiwan",
                    "ArtistID": "UCStpPtoeQUYII1Jsbl0qf8A",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCStpPtoeQUYII1Jsbl0qf8A",
                    "ArtistUrl": "https://youtube.com/channel/UCStpPtoeQUYII1Jsbl0qf8A",
                    "time": "4:08",
                    "second": 248
                },
                {
                    "SongTitle": "灰色的彩虹",
                    "SongID": "i66vTkylqCg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=i66vTkylqCg&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=i66vTkylqCg&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "范瑋琪",
                    "ArtistID": "UC49ijorxlIXpZRAC6wEQYWQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC49ijorxlIXpZRAC6wEQYWQ",
                    "ArtistUrl": "https://youtube.com/channel/UC49ijorxlIXpZRAC6wEQYWQ",
                    "time": "5:50",
                    "second": 350
                },
                {
                    "SongTitle": "白白的",
                    "SongID": "Dhpx6sAkd3w",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Dhpx6sAkd3w&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=Dhpx6sAkd3w&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "張韶涵",
                    "ArtistID": "UCKeK5Xj-iCfLOZvMDm3aIkw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCKeK5Xj-iCfLOZvMDm3aIkw",
                    "ArtistUrl": "https://youtube.com/channel/UCKeK5Xj-iCfLOZvMDm3aIkw",
                    "time": "4:20",
                    "second": 260
                },
                {
                    "SongTitle": "看得最遠的地方",
                    "SongID": "RdRsVog0y2w",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=RdRsVog0y2w&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=RdRsVog0y2w&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "張韶涵",
                    "ArtistID": "UCKeK5Xj-iCfLOZvMDm3aIkw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCKeK5Xj-iCfLOZvMDm3aIkw",
                    "ArtistUrl": "https://youtube.com/channel/UCKeK5Xj-iCfLOZvMDm3aIkw",
                    "time": "4:09",
                    "second": 249
                },
                {
                    "SongTitle": "說謊",
                    "SongID": "ftfJRzW0MPo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ftfJRzW0MPo&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=ftfJRzW0MPo&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "林宥嘉",
                    "ArtistID": "UC8VIeph9z_a5jHiHxqFjLPg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC8VIeph9z_a5jHiHxqFjLPg",
                    "ArtistUrl": "https://youtube.com/channel/UC8VIeph9z_a5jHiHxqFjLPg",
                    "time": "4:45",
                    "second": 285
                },
                {
                    "SongTitle": "新不了情",
                    "SongID": "LVgZ80p1fdA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=LVgZ80p1fdA&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=LVgZ80p1fdA&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "蕭敬騰",
                    "ArtistID": "UCvjGf4upqUNaqi524A5AHIw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCvjGf4upqUNaqi524A5AHIw",
                    "ArtistUrl": "https://youtube.com/channel/UCvjGf4upqUNaqi524A5AHIw",
                    "time": "4:28",
                    "second": 268
                },
                {
                    "SongTitle": "無言花",
                    "SongID": "ZEWUdqHLA_0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ZEWUdqHLA_0&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=ZEWUdqHLA_0&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "蕭敬騰",
                    "ArtistID": "UCvjGf4upqUNaqi524A5AHIw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCvjGf4upqUNaqi524A5AHIw",
                    "ArtistUrl": "https://youtube.com/channel/UCvjGf4upqUNaqi524A5AHIw",
                    "time": "4:30",
                    "second": 270
                },
                {
                    "SongTitle": "雨愛",
                    "SongID": "oec9R5ypf-o",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=oec9R5ypf-o&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=oec9R5ypf-o&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "楊丞琳",
                    "ArtistID": "UC0WDze0vAMrLxULTWMlSuRA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC0WDze0vAMrLxULTWMlSuRA",
                    "ArtistUrl": "https://youtube.com/channel/UC0WDze0vAMrLxULTWMlSuRA",
                    "time": "4:43",
                    "second": 283
                },
                {
                    "SongTitle": "庾澄慶 Harlem Yu - 無盡透明的思念 (官方版MV)",
                    "SongID": "6yuTwzOjjxw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=6yuTwzOjjxw&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=6yuTwzOjjxw&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "庾澄慶",
                    "ArtistID": "UC93ziw5QSSY8Gyacz-YGTlA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC93ziw5QSSY8Gyacz-YGTlA",
                    "ArtistUrl": "https://youtube.com/channel/UC93ziw5QSSY8Gyacz-YGTlA",
                    "time": "5:03",
                    "second": 303
                },
                {
                    "SongTitle": "愛不單行",
                    "SongID": "iBrOFd1wDuQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=iBrOFd1wDuQ&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=iBrOFd1wDuQ&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "羅志祥",
                    "ArtistID": "UC4_QhSjjcXMO2mxZbu-8oFA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC4_QhSjjcXMO2mxZbu-8oFA",
                    "ArtistUrl": "https://youtube.com/channel/UC4_QhSjjcXMO2mxZbu-8oFA",
                    "time": "4:41",
                    "second": 281
                },
                {
                    "SongTitle": "沒那麼簡單",
                    "SongID": "rmPHuvQoh0g",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=rmPHuvQoh0g&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=rmPHuvQoh0g&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "黃小琥",
                    "ArtistID": "UCV6FKRsG3xal52heBj_XWkA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCV6FKRsG3xal52heBj_XWkA",
                    "ArtistUrl": "https://youtube.com/channel/UCV6FKRsG3xal52heBj_XWkA",
                    "time": "5:05",
                    "second": 305
                },
                {
                    "SongTitle": "現在我很幸福",
                    "SongID": "8VpeFjdTex8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=8VpeFjdTex8&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=8VpeFjdTex8&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "A-Lin",
                    "ArtistID": "UCh8MAQTB0y4JMTROjINKenA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCh8MAQTB0y4JMTROjINKenA",
                    "ArtistUrl": "https://youtube.com/channel/UCh8MAQTB0y4JMTROjINKenA",
                    "time": "4:01",
                    "second": 241
                },
                {
                    "SongTitle": "我們沒有在一起",
                    "SongID": "CfYG8Q3ZpMA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=CfYG8Q3ZpMA&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=CfYG8Q3ZpMA&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "劉若英",
                    "ArtistID": "UCWY-I1axwr3X9YiouSwHf5Q",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCWY-I1axwr3X9YiouSwHf5Q",
                    "ArtistUrl": "https://youtube.com/channel/UCWY-I1axwr3X9YiouSwHf5Q",
                    "time": "4:50",
                    "second": 290
                },
                {
                    "SongTitle": "我不想念",
                    "SongID": "4r2GjbkMHYM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=4r2GjbkMHYM&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=4r2GjbkMHYM&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "劉若英",
                    "ArtistID": "UCWY-I1axwr3X9YiouSwHf5Q",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCWY-I1axwr3X9YiouSwHf5Q",
                    "ArtistUrl": "https://youtube.com/channel/UCWY-I1axwr3X9YiouSwHf5Q",
                    "time": "6:42",
                    "second": 402
                },
                {
                    "SongTitle": "Encore LaLa",
                    "SongID": "xaUvtK0sgdE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=xaUvtK0sgdE&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=xaUvtK0sgdE&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "郭靜",
                    "ArtistID": "UCYYhiWcofKhHQuqYD7BUoRw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCYYhiWcofKhHQuqYD7BUoRw",
                    "ArtistUrl": "https://youtube.com/channel/UCYYhiWcofKhHQuqYD7BUoRw",
                    "time": "3:07",
                    "second": 187
                },
                {
                    "SongTitle": "嫁妝",
                    "SongID": "4qDb6Cs-TvA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=4qDb6Cs-TvA&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=4qDb6Cs-TvA&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "郭靜",
                    "ArtistID": "UCYYhiWcofKhHQuqYD7BUoRw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCYYhiWcofKhHQuqYD7BUoRw",
                    "ArtistUrl": "https://youtube.com/channel/UCYYhiWcofKhHQuqYD7BUoRw",
                    "time": "3:58",
                    "second": 238
                },
                {
                    "SongTitle": "說了再見",
                    "SongID": "KKsioz-zaZY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=KKsioz-zaZY&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=KKsioz-zaZY&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "周杰倫",
                    "ArtistID": "UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "ArtistUrl": "https://youtube.com/channel/UCL2MDNdwEtV6aYUgNjFQGZA",
                    "time": "4:48",
                    "second": 288
                },
                {
                    "SongTitle": "聊天",
                    "SongID": "u-mMRBrSl2Q",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=u-mMRBrSl2Q&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=u-mMRBrSl2Q&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "郭靜",
                    "ArtistID": "UCYYhiWcofKhHQuqYD7BUoRw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCYYhiWcofKhHQuqYD7BUoRw",
                    "ArtistUrl": "https://youtube.com/channel/UCYYhiWcofKhHQuqYD7BUoRw",
                    "time": "4:13",
                    "second": 253
                },
                {
                    "SongTitle": "因為愛",
                    "SongID": "d7YJ_fOcOks",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=d7YJ_fOcOks&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=d7YJ_fOcOks&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "韋禮安",
                    "ArtistID": "UCRRM_02oKgCCZO359HnMUnQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCRRM_02oKgCCZO359HnMUnQ",
                    "ArtistUrl": "https://youtube.com/channel/UCRRM_02oKgCCZO359HnMUnQ",
                    "time": "4:03",
                    "second": 243
                },
                {
                    "SongTitle": "壞了",
                    "SongID": "jyXesgwUDrY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=jyXesgwUDrY&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=jyXesgwUDrY&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "張芸京",
                    "ArtistID": "UCKUd0BGkQ6Q8pkArjy3GCRA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCKUd0BGkQ6Q8pkArjy3GCRA",
                    "ArtistUrl": "https://youtube.com/channel/UCKUd0BGkQ6Q8pkArjy3GCRA",
                    "time": "3:43",
                    "second": 223
                },
                {
                    "SongTitle": "童話 (洛克先生Live版)",
                    "SongID": "Id5vRFfsV5w",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Id5vRFfsV5w&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=Id5vRFfsV5w&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "蕭敬騰",
                    "ArtistID": "UCvjGf4upqUNaqi524A5AHIw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCvjGf4upqUNaqi524A5AHIw",
                    "ArtistUrl": "https://youtube.com/channel/UCvjGf4upqUNaqi524A5AHIw",
                    "time": "2:00",
                    "second": 120
                },
                {
                    "SongTitle": "愛情選項",
                    "SongID": "36dbeZjn5WM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=36dbeZjn5WM&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=36dbeZjn5WM&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "張芸京",
                    "ArtistID": "UCKUd0BGkQ6Q8pkArjy3GCRA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCKUd0BGkQ6Q8pkArjy3GCRA",
                    "ArtistUrl": "https://youtube.com/channel/UCKUd0BGkQ6Q8pkArjy3GCRA",
                    "time": "3:55",
                    "second": 235
                },
                {
                    "SongTitle": "韩庚 - My Logo",
                    "SongID": "VyzmnUwO0r4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=VyzmnUwO0r4&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=VyzmnUwO0r4&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "乐华娱乐 YH Entertainment",
                    "ArtistID": "UCiFqm8xNW7R0cSbL3vqZ4EA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiFqm8xNW7R0cSbL3vqZ4EA",
                    "ArtistUrl": "https://youtube.com/channel/UCiFqm8xNW7R0cSbL3vqZ4EA",
                    "time": "3:21",
                    "second": 201
                },
                {
                    "SongTitle": "洋蔥",
                    "SongID": "T-XFIPKmhww",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=T-XFIPKmhww&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=T-XFIPKmhww&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "丁噹",
                    "ArtistID": "UCATB6fk4_-ySg0CzlQFHLaQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCATB6fk4_-ySg0CzlQFHLaQ",
                    "ArtistUrl": "https://youtube.com/channel/UCATB6fk4_-ySg0CzlQFHLaQ",
                    "time": "5:15",
                    "second": 315
                },
                {
                    "SongTitle": "寂寞寂寞就好",
                    "SongID": "DyFIzKYQQYE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=DyFIzKYQQYE&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "SongUrl": "https://youtube.com/watch?v=DyFIzKYQQYE&list=PL7IO3f3GVf2ATWar-6UB5vjvke4idTHB6",
                    "Artist": "田馥甄",
                    "ArtistID": "UCGkj4uoWx_1BA2tF9Q-9Y6w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCGkj4uoWx_1BA2tF9Q-9Y6w",
                    "ArtistUrl": "https://youtube.com/channel/UCGkj4uoWx_1BA2tF9Q-9Y6w",
                    "time": "4:40",
                    "second": 280
                }
            ]
        }
    ];
    return { data };
});
