export default defineEventHandler((event) => {
    const data = [
        {
            "ListName": "甜約翰",
            "SongList": [
                {
                    "SongTitle": "失蹤人口",
                    "SongID": "xkdwTbBZW7c",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=xkdwTbBZW7c&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "SongUrl": "https://youtube.com/watch?v=xkdwTbBZW7c&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "Artist": "甜約翰 Sweet John",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "5:26",
                    "second": 326
                },
                {
                    "SongTitle": "留給你的我從未",
                    "SongID": "wbOVyx1gZ3I",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=wbOVyx1gZ3I&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "SongUrl": "https://youtube.com/watch?v=wbOVyx1gZ3I&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "Artist": "甜約翰 Sweet John",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "4:19",
                    "second": 259
                },
                {
                    "SongTitle": "降雨機率",
                    "SongID": "KCNIScKsJqg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=KCNIScKsJqg&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "SongUrl": "https://youtube.com/watch?v=KCNIScKsJqg&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "Artist": "甜約翰 Sweet John",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "4:03",
                    "second": 243
                },
                {
                    "SongTitle": "Come from Away",
                    "SongID": "bIYQc6xalwA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=bIYQc6xalwA&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "SongUrl": "https://youtube.com/watch?v=bIYQc6xalwA&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "Artist": "甜約翰",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "4:03",
                    "second": 243
                },
                {
                    "SongTitle": "不小心愛上你 ft. 魏如萱 waa wei (合作演出：魏如萱和魏如萱 waa wei)",
                    "SongID": "3Czet0VO890",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=3Czet0VO890&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "SongUrl": "https://youtube.com/watch?v=3Czet0VO890&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "Artist": "甜約翰 Sweet John",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "4:00",
                    "second": 240
                },
                {
                    "SongTitle": "安全範圍",
                    "SongID": "IhKMtzaAHxA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=IhKMtzaAHxA&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "SongUrl": "https://youtube.com/watch?v=IhKMtzaAHxA&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "Artist": "甜約翰 Sweet John",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "3:52",
                    "second": 232
                },
                {
                    "SongTitle": "Dear",
                    "SongID": "qnoLk6tsgt0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=qnoLk6tsgt0&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "SongUrl": "https://youtube.com/watch?v=qnoLk6tsgt0&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "Artist": "甜約翰 Sweet John",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "4:24",
                    "second": 264
                },
                {
                    "SongTitle": "日晷",
                    "SongID": "VK99L43vl0c",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=VK99L43vl0c&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "SongUrl": "https://youtube.com/watch?v=VK99L43vl0c&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "Artist": "甜約翰 Sweet John",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "4:09",
                    "second": 249
                },
                {
                    "SongTitle": "後遺症",
                    "SongID": "pxYVABWlV_o",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=pxYVABWlV_o&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "SongUrl": "https://youtube.com/watch?v=pxYVABWlV_o&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "Artist": "甜約翰 Sweet John",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "3:31",
                    "second": 211
                },
                {
                    "SongTitle": "Angelina",
                    "SongID": "urP9NYKO75E",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=urP9NYKO75E&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "SongUrl": "https://youtube.com/watch?v=urP9NYKO75E&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "Artist": "甜約翰 Sweet John",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "3:51",
                    "second": 231
                },
                {
                    "SongTitle": "In Mind",
                    "SongID": "5ClvyHgjxFU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=5ClvyHgjxFU&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "SongUrl": "https://youtube.com/watch?v=5ClvyHgjxFU&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "Artist": "甜約翰 Sweet John",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "1:14",
                    "second": 74
                },
                {
                    "SongTitle": "戀人觀影須知",
                    "SongID": "PgIQ-PZvlV8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=PgIQ-PZvlV8&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "SongUrl": "https://youtube.com/watch?v=PgIQ-PZvlV8&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "Artist": "甜約翰 Sweet John",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "4:45",
                    "second": 285
                },
                {
                    "SongTitle": "親吻了再摸索",
                    "SongID": "RSddiUXnIfE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=RSddiUXnIfE&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "SongUrl": "https://youtube.com/watch?v=RSddiUXnIfE&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "Artist": "甜約翰 Sweet John",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "3:42",
                    "second": 222
                },
                {
                    "SongTitle": "但你知道吧",
                    "SongID": "K01CZ0TA-Ls",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=K01CZ0TA-Ls&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "SongUrl": "https://youtube.com/watch?v=K01CZ0TA-Ls&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "Artist": "甜約翰 Sweet John",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "3:21",
                    "second": 201
                },
                {
                    "SongTitle": "敏感話題",
                    "SongID": "Rr_fmlE8ZFU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Rr_fmlE8ZFU&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "SongUrl": "https://youtube.com/watch?v=Rr_fmlE8ZFU&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "Artist": "甜約翰 Sweet John",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "3:56",
                    "second": 236
                },
                {
                    "SongTitle": "出眾",
                    "SongID": "mMgLDFgvN-Y",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=mMgLDFgvN-Y&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "SongUrl": "https://youtube.com/watch?v=mMgLDFgvN-Y&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "Artist": "甜約翰 Sweet John",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "3:00",
                    "second": 180
                },
                {
                    "SongTitle": "語言",
                    "SongID": "JcaNFRgZ4M8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=JcaNFRgZ4M8&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "SongUrl": "https://youtube.com/watch?v=JcaNFRgZ4M8&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "Artist": "甜約翰 Sweet John",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "4:13",
                    "second": 253
                },
                {
                    "SongTitle": "容易厭倦的時刻",
                    "SongID": "k0YsbbRe7b4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=k0YsbbRe7b4&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "SongUrl": "https://youtube.com/watch?v=k0YsbbRe7b4&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "Artist": "甜約翰 Sweet John",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "4:59",
                    "second": 299
                },
                {
                    "SongTitle": "Daze of CityWalk",
                    "SongID": "-Sa92uGZx0k",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=-Sa92uGZx0k&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "SongUrl": "https://youtube.com/watch?v=-Sa92uGZx0k&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "Artist": "甜約翰",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "3:49",
                    "second": 229
                },
                {
                    "SongTitle": "Window Seat",
                    "SongID": "3jt1RFCZBcI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=3jt1RFCZBcI&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "SongUrl": "https://youtube.com/watch?v=3jt1RFCZBcI&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "Artist": "甜約翰",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "5:02",
                    "second": 302
                },
                {
                    "SongTitle": "Until You",
                    "SongID": "H3fd5fZj3Ys",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=H3fd5fZj3Ys&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "SongUrl": "https://youtube.com/watch?v=H3fd5fZj3Ys&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "Artist": "甜約翰",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "4:21",
                    "second": 261
                },
                {
                    "SongTitle": "Sami",
                    "SongID": "kNvtnmN5r_Q",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=kNvtnmN5r_Q&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "SongUrl": "https://youtube.com/watch?v=kNvtnmN5r_Q&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "Artist": "甜約翰",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "4:40",
                    "second": 280
                },
                {
                    "SongTitle": "See, You",
                    "SongID": "Uf3A6n1yAbQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Uf3A6n1yAbQ&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "SongUrl": "https://youtube.com/watch?v=Uf3A6n1yAbQ&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "Artist": "甜約翰",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "4:35",
                    "second": 275
                },
                {
                    "SongTitle": "Blank Page",
                    "SongID": "53fB76kr0nE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=53fB76kr0nE&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "SongUrl": "https://youtube.com/watch?v=53fB76kr0nE&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "Artist": "甜約翰",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "4:10",
                    "second": 250
                },
                {
                    "SongTitle": "Neon Stream",
                    "SongID": "KleykaDn9q0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=KleykaDn9q0&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "SongUrl": "https://youtube.com/watch?v=KleykaDn9q0&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "Artist": "甜約翰",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "5:31",
                    "second": 331
                },
                {
                    "SongTitle": "Appendix",
                    "SongID": "QsnePRCQ0EI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=QsnePRCQ0EI&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "SongUrl": "https://youtube.com/watch?v=QsnePRCQ0EI&list=PL3qm_8TRqiefiqyDJgzRAzW73_bG9vAFf",
                    "Artist": "甜約翰",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "1:44",
                    "second": 104
                },
            ]
        }
    ]
    return { data };
});
