export default defineEventHandler((event) => {
    const data = [
        {
            "ListName": "臺灣獨立樂團",
            "SongList": [
                {
                    "SongTitle": "告五人 Accusefive 【披星戴月的想你】Official Music Video",
                    "SongID": "VpwAq7hiij0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=VpwAq7hiij0&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=VpwAq7hiij0&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "告五人",
                    "ArtistID": "UC2lbjBep5vvd-Spo0oGn97g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC2lbjBep5vvd-Spo0oGn97g",
                    "ArtistUrl": "https://youtube.com/channel/UC2lbjBep5vvd-Spo0oGn97g",
                    "time": "7:46",
                    "second": 466
                },
                {
                    "SongTitle": "告五人 Accusefive 【披星戴月的想你】Official Music Video",
                    "SongID": "VpwAq7hiij0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=VpwAq7hiij0&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=VpwAq7hiij0&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "告五人",
                    "ArtistID": "UC2lbjBep5vvd-Spo0oGn97g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC2lbjBep5vvd-Spo0oGn97g",
                    "ArtistUrl": "https://youtube.com/channel/UC2lbjBep5vvd-Spo0oGn97g",
                    "time": "7:46",
                    "second": 466
                },
                {
                    "SongTitle": "Undercurrent",
                    "SongID": "Roxj9OR6ufk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Roxj9OR6ufk&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=Roxj9OR6ufk&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "拍謝少年",
                    "ArtistID": "UC_tHjk8qVxTq8wo9p5F4cbA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC_tHjk8qVxTq8wo9p5F4cbA",
                    "ArtistUrl": "https://youtube.com/channel/UC_tHjk8qVxTq8wo9p5F4cbA",
                    "time": "7:30",
                    "second": 450
                },
                {
                    "SongTitle": "deca joins | 海浪【Official Music Video】",
                    "SongID": "FonjL7DQAUQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=FonjL7DQAUQ&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=FonjL7DQAUQ&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "Deca Joins",
                    "ArtistID": "UCFGk4hg7Du-TCUV0FRHF-PA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCFGk4hg7Du-TCUV0FRHF-PA",
                    "ArtistUrl": "https://youtube.com/channel/UCFGk4hg7Du-TCUV0FRHF-PA",
                    "time": "5:31",
                    "second": 331
                },
                {
                    "SongTitle": "Hello Nico〈花〉MV",
                    "SongID": "BlblBvpVgjE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=BlblBvpVgjE&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=BlblBvpVgjE&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "黑市音樂",
                    "ArtistID": "UC7MMGaCyQGmuIWq8zvpHkgQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7MMGaCyQGmuIWq8zvpHkgQ",
                    "ArtistUrl": "https://youtube.com/channel/UC7MMGaCyQGmuIWq8zvpHkgQ",
                    "time": "5:55",
                    "second": 355
                },
                {
                    "SongTitle": "VH (Vast & Hazy) 【與浪之間 Waves】 Official Music Video",
                    "SongID": "10DHUqSVu6I",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=10DHUqSVu6I&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=10DHUqSVu6I&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "添翼音樂 TEAM EAR MUSIC",
                    "ArtistID": "UC9-SkdRRsaABoNvYiacFh_w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC9-SkdRRsaABoNvYiacFh_w",
                    "ArtistUrl": "https://youtube.com/channel/UC9-SkdRRsaABoNvYiacFh_w",
                    "time": "5:23",
                    "second": 323
                },
                {
                    "SongTitle": "我愛你,卻不能拯救你",
                    "SongID": "RucWamnU6Ic",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=RucWamnU6Ic&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=RucWamnU6Ic&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "好樂團",
                    "ArtistID": "UCbNspVIs5kbxKbzg2oB880g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCbNspVIs5kbxKbzg2oB880g",
                    "ArtistUrl": "https://youtube.com/channel/UCbNspVIs5kbxKbzg2oB880g",
                    "time": "6:20",
                    "second": 380
                },
                {
                    "SongTitle": "愛在夏天",
                    "SongID": "_zv8Y94eLYI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=_zv8Y94eLYI&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=_zv8Y94eLYI&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "告五人",
                    "ArtistID": "UC2lbjBep5vvd-Spo0oGn97g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC2lbjBep5vvd-Spo0oGn97g",
                    "ArtistUrl": "https://youtube.com/channel/UC2lbjBep5vvd-Spo0oGn97g",
                    "time": "6:38",
                    "second": 398
                },
                {
                    "SongTitle": "紅",
                    "SongID": "9WEYFqCUze8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=9WEYFqCUze8&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=9WEYFqCUze8&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "告五人",
                    "ArtistID": "UC2lbjBep5vvd-Spo0oGn97g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC2lbjBep5vvd-Spo0oGn97g",
                    "ArtistUrl": "https://youtube.com/channel/UC2lbjBep5vvd-Spo0oGn97g",
                    "time": "6:05",
                    "second": 365
                },
                {
                    "SongTitle": "迷霧之子",
                    "SongID": "LnJEaPnVmz4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=LnJEaPnVmz4&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=LnJEaPnVmz4&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "告五人",
                    "ArtistID": "UC2lbjBep5vvd-Spo0oGn97g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC2lbjBep5vvd-Spo0oGn97g",
                    "ArtistUrl": "https://youtube.com/channel/UC2lbjBep5vvd-Spo0oGn97g",
                    "time": "6:14",
                    "second": 374
                },
                {
                    "SongTitle": "1976_方向感_ [Official MV]",
                    "SongID": "KJ_JQtJNgdE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=KJ_JQtJNgdE&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=KJ_JQtJNgdE&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "相知音樂 B’tween Music",
                    "ArtistID": "UCTn2cDYFfL7cP4rSX6qRzfQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCTn2cDYFfL7cP4rSX6qRzfQ",
                    "ArtistUrl": "https://youtube.com/channel/UCTn2cDYFfL7cP4rSX6qRzfQ",
                    "time": "6:00",
                    "second": 360
                },
                {
                    "SongTitle": "Tizzy Bac - 淺色的那條 / 維克多的玫瑰 EP",
                    "SongID": "9EvntzDT3zc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=9EvntzDT3zc&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=9EvntzDT3zc&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "DANNIX",
                    "ArtistID": "UChkefESqdF-Sq6kHcxqwimg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UChkefESqdF-Sq6kHcxqwimg",
                    "ArtistUrl": "https://youtube.com/channel/UChkefESqdF-Sq6kHcxqwimg",
                    "time": "6:06",
                    "second": 366
                },
                {
                    "SongTitle": "安平之光",
                    "SongID": "ZrpZB8-VBD0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ZrpZB8-VBD0&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=ZrpZB8-VBD0&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "イルカポリス 海豚刑警",
                    "ArtistID": "UCOjS7H2XrIjcPJvzKb5_9nA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCOjS7H2XrIjcPJvzKb5_9nA",
                    "ArtistUrl": "https://youtube.com/channel/UCOjS7H2XrIjcPJvzKb5_9nA",
                    "time": "4:56",
                    "second": 296
                },
                {
                    "SongTitle": "1976摩登少年",
                    "SongID": "A3mziAIKXgk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=A3mziAIKXgk&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=A3mziAIKXgk&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "Sodagreen",
                    "ArtistID": "UC9uXzDXfMs8FNfKqCj9gY2g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC9uXzDXfMs8FNfKqCj9gY2g",
                    "ArtistUrl": "https://youtube.com/channel/UC9uXzDXfMs8FNfKqCj9gY2g",
                    "time": "6:46",
                    "second": 406
                },
                {
                    "SongTitle": "Our Shame 凹與山 - 理查 Richard（Official Video）",
                    "SongID": "PORWzNz9o90",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=PORWzNz9o90&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=PORWzNz9o90&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "凹與山",
                    "ArtistID": "UCIlrL3HXzxs6EMlX_cJRPKg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCIlrL3HXzxs6EMlX_cJRPKg",
                    "ArtistUrl": "https://youtube.com/channel/UCIlrL3HXzxs6EMlX_cJRPKg",
                    "time": "4:27",
                    "second": 267
                },
                {
                    "SongTitle": "Lost and Found 失物招領 - 放不放131011@PIPE",
                    "SongID": "9M0qeEmtUY4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=9M0qeEmtUY4&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=9M0qeEmtUY4&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "失物招領",
                    "ArtistID": "UC9KkSTUeJF7P2UxXlXemnMA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC9KkSTUeJF7P2UxXlXemnMA",
                    "ArtistUrl": "https://youtube.com/channel/UC9KkSTUeJF7P2UxXlXemnMA",
                    "time": "4:48",
                    "second": 288
                },
                {
                    "SongTitle": "【好樂團 GoodBand】－我們一樣可惜 Demo",
                    "SongID": "ixx8yGG4AS4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ixx8yGG4AS4&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=ixx8yGG4AS4&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "好樂團",
                    "ArtistID": "UCbNspVIs5kbxKbzg2oB880g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCbNspVIs5kbxKbzg2oB880g",
                    "ArtistUrl": "https://youtube.com/channel/UCbNspVIs5kbxKbzg2oB880g",
                    "time": "7:14",
                    "second": 434
                },
                {
                    "SongTitle": "Teens Edge",
                    "SongID": "NbNPJr_0tqA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=NbNPJr_0tqA&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=NbNPJr_0tqA&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "老王樂隊",
                    "ArtistID": "UCdxpW3sUpUGJIwKhHam5bhQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCdxpW3sUpUGJIwKhHam5bhQ",
                    "ArtistUrl": "https://youtube.com/channel/UCdxpW3sUpUGJIwKhHam5bhQ",
                    "time": "5:55",
                    "second": 355
                },
                {
                    "SongTitle": "你要不要吃哈密瓜",
                    "SongID": "TRDV0xw3j4Y",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=TRDV0xw3j4Y&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=TRDV0xw3j4Y&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "告五人",
                    "ArtistID": "UC2lbjBep5vvd-Spo0oGn97g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC2lbjBep5vvd-Spo0oGn97g",
                    "ArtistUrl": "https://youtube.com/channel/UC2lbjBep5vvd-Spo0oGn97g",
                    "time": "5:33",
                    "second": 333
                },
                {
                    "SongTitle": "法蘭西多士",
                    "SongID": "Chua3NCdFGA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Chua3NCdFGA&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=Chua3NCdFGA&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "告五人",
                    "ArtistID": "UC2lbjBep5vvd-Spo0oGn97g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC2lbjBep5vvd-Spo0oGn97g",
                    "ArtistUrl": "https://youtube.com/channel/UC2lbjBep5vvd-Spo0oGn97g",
                    "time": "4:36",
                    "second": 276
                },
                {
                    "SongTitle": "貝克小姐Miss Bac. - 嘿，凌晨三點還醒著的人",
                    "SongID": "5A7tbE6hAoA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=5A7tbE6hAoA&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=5A7tbE6hAoA&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "貝克小姐Miss Bac.",
                    "ArtistID": "UCM2k3vI6hT0MyaT8EcmK_yw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCM2k3vI6hT0MyaT8EcmK_yw",
                    "ArtistUrl": "https://youtube.com/channel/UCM2k3vI6hT0MyaT8EcmK_yw",
                    "time": "4:35",
                    "second": 275
                },
                {
                    "SongTitle": "那我懂你意思了 - 所以我停下來",
                    "SongID": "Gp6XKEE8B2E",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Gp6XKEE8B2E&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=Gp6XKEE8B2E&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "svcollectionTV",
                    "ArtistID": "UCa0__drsYchGcyijzZtTjqw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCa0__drsYchGcyijzZtTjqw",
                    "ArtistUrl": "https://youtube.com/channel/UCa0__drsYchGcyijzZtTjqw",
                    "time": "3:30",
                    "second": 210
                },
                {
                    "SongTitle": "那我懂你意思了 - 沒有人在乎你在乎的事 [Official Music Video]",
                    "SongID": "UX2uQyHaCUk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=UX2uQyHaCUk&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=UX2uQyHaCUk&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "那我懂你意思了",
                    "ArtistID": "UCSNoaYGQHso9aws3uXGT8Ew",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCSNoaYGQHso9aws3uXGT8Ew",
                    "ArtistUrl": "https://youtube.com/channel/UCSNoaYGQHso9aws3uXGT8Ew",
                    "time": "3:01",
                    "second": 181
                },
                {
                    "SongTitle": "熱烈（demo）/ Frandé , 法蘭黛樂團",
                    "SongID": "udz9mETS6UE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=udz9mETS6UE&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=udz9mETS6UE&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "fchen5211",
                    "ArtistID": "UCUoxJdZ_YH-QkSBxmWjvIIA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCUoxJdZ_YH-QkSBxmWjvIIA",
                    "ArtistUrl": "https://youtube.com/channel/UCUoxJdZ_YH-QkSBxmWjvIIA",
                    "time": "5:05",
                    "second": 305
                },
                {
                    "SongTitle": "南瓜妮歌迷俱樂部 - 微光",
                    "SongID": "oFD5GelrE1M",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=oFD5GelrE1M&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=oFD5GelrE1M&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "shoegazM",
                    "ArtistID": "UCHFrYpB89jALKxdC0lDywLQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCHFrYpB89jALKxdC0lDywLQ",
                    "ArtistUrl": "https://youtube.com/channel/UCHFrYpB89jALKxdC0lDywLQ",
                    "time": "3:35",
                    "second": 215
                },
                {
                    "SongTitle": "米兒",
                    "SongID": "nVjVpX3gRWk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=nVjVpX3gRWk&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=nVjVpX3gRWk&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "Bisiugroup",
                    "ArtistID": "UC9fwTdQyoeDFhOhNN3CQDlg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC9fwTdQyoeDFhOhNN3CQDlg",
                    "ArtistUrl": "https://youtube.com/channel/UC9fwTdQyoeDFhOhNN3CQDlg",
                    "time": "5:25",
                    "second": 325
                },
                {
                    "SongTitle": "象牙舟",
                    "SongID": "i-QqAvMCwCM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=i-QqAvMCwCM&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=i-QqAvMCwCM&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "傻子與白痴",
                    "ArtistID": "UCerJW-mhyVBS3G-j0wZaCyA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCerJW-mhyVBS3G-j0wZaCyA",
                    "ArtistUrl": "https://youtube.com/channel/UCerJW-mhyVBS3G-j0wZaCyA",
                    "time": "5:03",
                    "second": 303
                },
                {
                    "SongTitle": "5:10a.m.",
                    "SongID": "-oDRzgmYHms",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=-oDRzgmYHms&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=-oDRzgmYHms&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "傻子與白痴",
                    "ArtistID": "UCerJW-mhyVBS3G-j0wZaCyA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCerJW-mhyVBS3G-j0wZaCyA",
                    "ArtistUrl": "https://youtube.com/channel/UCerJW-mhyVBS3G-j0wZaCyA",
                    "time": "4:20",
                    "second": 260
                },
                {
                    "SongTitle": "1976 不加糖",
                    "SongID": "gDjQNQgg3Ug",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=gDjQNQgg3Ug&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=gDjQNQgg3Ug&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "b09504022",
                    "ArtistID": "UCQQjNglN2yTrPPy99C_1vdw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCQQjNglN2yTrPPy99C_1vdw",
                    "ArtistUrl": "https://youtube.com/channel/UCQQjNglN2yTrPPy99C_1vdw",
                    "time": "8:15",
                    "second": 495
                },
                {
                    "SongTitle": "3小湯 Triple t  - 11月4日",
                    "SongID": "Cl7VMh3wKxc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Cl7VMh3wKxc&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=Cl7VMh3wKxc&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "3小湯",
                    "ArtistID": "UCVLe2NIkrUC1TCfzW5dBosQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCVLe2NIkrUC1TCfzW5dBosQ",
                    "ArtistUrl": "https://youtube.com/channel/UCVLe2NIkrUC1TCfzW5dBosQ",
                    "time": "5:06",
                    "second": 306
                },
                {
                    "SongTitle": "deca joins | 浴室【Official Music Video】",
                    "SongID": "kZecE9AeELI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=kZecE9AeELI&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=kZecE9AeELI&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "Deca Joins",
                    "ArtistID": "UCFGk4hg7Du-TCUV0FRHF-PA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCFGk4hg7Du-TCUV0FRHF-PA",
                    "ArtistUrl": "https://youtube.com/channel/UCFGk4hg7Du-TCUV0FRHF-PA",
                    "time": "4:40",
                    "second": 280
                },
                {
                    "SongTitle": "DSPS「我會不會又睡到下午了 Sleep till Afternoon」FULL EP",
                    "SongID": "z9mH-OZ2B-Y",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=z9mH-OZ2B-Y&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=z9mH-OZ2B-Y&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "DSPS",
                    "ArtistID": "UCcQsz2boxIXHKoZweIzMymw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCcQsz2boxIXHKoZweIzMymw",
                    "ArtistUrl": "https://youtube.com/channel/UCcQsz2boxIXHKoZweIzMymw",
                    "time": "12:16",
                    "second": 736
                },
                {
                    "SongTitle": "Empty ORio－當被世界遺棄 It’s Not A Big Deal Official Lyric Video",
                    "SongID": "WQCYLpl23D4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=WQCYLpl23D4&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=WQCYLpl23D4&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "火氣音樂 FIRE ON MUSIC",
                    "ArtistID": "UC_qPyZDMq3KNok5UpBM3Xkw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC_qPyZDMq3KNok5UpBM3Xkw",
                    "ArtistUrl": "https://youtube.com/channel/UC_qPyZDMq3KNok5UpBM3Xkw",
                    "time": "4:03",
                    "second": 243
                },
                {
                    "SongTitle": "死宝貝",
                    "SongID": "L_jnT1I05qY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=L_jnT1I05qY&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=L_jnT1I05qY&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "I Mean Us",
                    "ArtistID": "UCFUrKtg79mvMlUjAtat-qfA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCFUrKtg79mvMlUjAtat-qfA",
                    "ArtistUrl": "https://youtube.com/channel/UCFUrKtg79mvMlUjAtat-qfA",
                    "time": "3:57",
                    "second": 237
                },
                {
                    "SongTitle": "Søulмaтe",
                    "SongID": "AgrfgqV1lAs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=AgrfgqV1lAs&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=AgrfgqV1lAs&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "I Mean Us",
                    "ArtistID": "UCFUrKtg79mvMlUjAtat-qfA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCFUrKtg79mvMlUjAtat-qfA",
                    "ArtistUrl": "https://youtube.com/channel/UCFUrKtg79mvMlUjAtat-qfA",
                    "time": "6:44",
                    "second": 404
                },
                {
                    "SongTitle": "我的夜晚是不是你的白天",
                    "SongID": "lkSMbg_QE9g",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=lkSMbg_QE9g&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=lkSMbg_QE9g&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "Limi",
                    "ArtistID": "UCOmf3vCpffMU5lmzSxMoXqA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCOmf3vCpffMU5lmzSxMoXqA",
                    "ArtistUrl": "https://youtube.com/channel/UCOmf3vCpffMU5lmzSxMoXqA",
                    "time": "3:59",
                    "second": 239
                },
                {
                    "SongTitle": "LYRA - 夢幻花 Mugenbana | Official Music Video 官方音樂錄影帶",
                    "SongID": "kGhM9ReqQoE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=kGhM9ReqQoE&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=kGhM9ReqQoE&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "LYRA",
                    "ArtistID": "UCdzqoZSVP3jgYff7EBnMtOA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCdzqoZSVP3jgYff7EBnMtOA",
                    "ArtistUrl": "https://youtube.com/channel/UCdzqoZSVP3jgYff7EBnMtOA",
                    "time": "5:30",
                    "second": 330
                },
                {
                    "SongTitle": "MOJO-我在想你的時候睡著了",
                    "SongID": "AZsYcG7sFAU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=AZsYcG7sFAU&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=AZsYcG7sFAU&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "lesliev",
                    "ArtistID": "UCDP_i5N1zL7Oxw8JIh3He2g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCDP_i5N1zL7Oxw8JIh3He2g",
                    "ArtistUrl": "https://youtube.com/channel/UCDP_i5N1zL7Oxw8JIh3He2g",
                    "time": "4:06",
                    "second": 246
                },
                {
                    "SongTitle": "愛與和平",
                    "SongID": "gon-kSOO-JI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=gon-kSOO-JI&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=gon-kSOO-JI&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "Mr.",
                    "ArtistID": "UCkKkyiHpyWKbYKRXDsEAauw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCkKkyiHpyWKbYKRXDsEAauw",
                    "ArtistUrl": "https://youtube.com/channel/UCkKkyiHpyWKbYKRXDsEAauw",
                    "time": "5:56",
                    "second": 356
                },
                {
                    "SongTitle": "STAYCOOL-大雨、大禹",
                    "SongID": "V44WQnZljkg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=V44WQnZljkg&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=V44WQnZljkg&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "chen0428",
                    "ArtistID": "UCDMKR7GMKxfVY8x4Q7aL1Ag",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCDMKR7GMKxfVY8x4Q7aL1Ag",
                    "ArtistUrl": "https://youtube.com/channel/UCDMKR7GMKxfVY8x4Q7aL1Ag",
                    "time": "4:01",
                    "second": 241
                },
                {
                    "SongTitle": "Tizzy Bac - 婚禮歌手 MV",
                    "SongID": "uD6A8jd3tac",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=uD6A8jd3tac&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=uD6A8jd3tac&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "Tizzy Bac",
                    "ArtistID": "UC3od9rPepMwiZry10oBObEA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC3od9rPepMwiZry10oBObEA",
                    "ArtistUrl": "https://youtube.com/channel/UC3od9rPepMwiZry10oBObEA",
                    "time": "5:26",
                    "second": 326
                },
                {
                    "SongTitle": "Tizzy Bac - 我不小心",
                    "SongID": "O0dvTI9LxDE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=O0dvTI9LxDE&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=O0dvTI9LxDE&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "dichia",
                    "ArtistID": "UCE_pFtKd0w39OuSKd1Mwa7w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCE_pFtKd0w39OuSKd1Mwa7w",
                    "ArtistUrl": "https://youtube.com/channel/UCE_pFtKd0w39OuSKd1Mwa7w",
                    "time": "5:40",
                    "second": 340
                },
                {
                    "SongTitle": "The People I Love",
                    "SongID": "GGhfyFrxHv8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=GGhfyFrxHv8&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=GGhfyFrxHv8&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "Tizzy Bac",
                    "ArtistID": "UC3od9rPepMwiZry10oBObEA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC3od9rPepMwiZry10oBObEA",
                    "ArtistUrl": "https://youtube.com/channel/UC3od9rPepMwiZry10oBObEA",
                    "time": "5:35",
                    "second": 335
                },
                {
                    "SongTitle": "Tizzy Bac - 查理布朗與露西",
                    "SongID": "eCjLLXV-noY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=eCjLLXV-noY&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=eCjLLXV-noY&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "YuHsuan Lin",
                    "ArtistID": "UCASEluYe0D0LUgLdIDtadaw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCASEluYe0D0LUgLdIDtadaw",
                    "ArtistUrl": "https://youtube.com/channel/UCASEluYe0D0LUgLdIDtadaw",
                    "time": "6:27",
                    "second": 387
                },
                {
                    "SongTitle": "世界盡頭",
                    "SongID": "aI-pG_xEnmk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=aI-pG_xEnmk&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=aI-pG_xEnmk&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "TRASH",
                    "ArtistID": "UCcm5ExAhZ0DbfUEdSUhMQ1w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCcm5ExAhZ0DbfUEdSUhMQ1w",
                    "ArtistUrl": "https://youtube.com/channel/UCcm5ExAhZ0DbfUEdSUhMQ1w",
                    "time": "7:29",
                    "second": 449
                },
                {
                    "SongTitle": "Stars of the Night",
                    "SongID": "dUWvqjefEd4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=dUWvqjefEd4&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=dUWvqjefEd4&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "TRASH",
                    "ArtistID": "UCcm5ExAhZ0DbfUEdSUhMQ1w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCcm5ExAhZ0DbfUEdSUhMQ1w",
                    "ArtistUrl": "https://youtube.com/channel/UCcm5ExAhZ0DbfUEdSUhMQ1w",
                    "time": "5:20",
                    "second": 320
                },
                {
                    "SongTitle": "VH (Vast & Hazy) 【求救訊號 I'm Not OK】Official Music Video",
                    "SongID": "0vv149qqciw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=0vv149qqciw&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=0vv149qqciw&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "添翼音樂 TEAM EAR MUSIC",
                    "ArtistID": "UC9-SkdRRsaABoNvYiacFh_w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC9-SkdRRsaABoNvYiacFh_w",
                    "ArtistUrl": "https://youtube.com/channel/UC9-SkdRRsaABoNvYiacFh_w",
                    "time": "5:06",
                    "second": 306
                },
                {
                    "SongTitle": "VH (Vast & Hazy) 【下次見 Perfect Time】Official Lyrics Video  ( 電視劇《 月村歡迎你 》插曲)",
                    "SongID": "B8vdGsASiI0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=B8vdGsASiI0&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=B8vdGsASiI0&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "添翼音樂 TEAM EAR MUSIC",
                    "ArtistID": "UC9-SkdRRsaABoNvYiacFh_w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC9-SkdRRsaABoNvYiacFh_w",
                    "ArtistUrl": "https://youtube.com/channel/UC9-SkdRRsaABoNvYiacFh_w",
                    "time": "4:54",
                    "second": 294
                },
                {
                    "SongTitle": "Vast & Hazy【食人夢 The City is Eating Me Alive】Official Lyrics Video",
                    "SongID": "_mcdnRHrXCQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=_mcdnRHrXCQ&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=_mcdnRHrXCQ&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "Vast & Hazy",
                    "ArtistID": "UC--1YrYgBtfK5ktB3B8cbCw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC--1YrYgBtfK5ktB3B8cbCw",
                    "ArtistUrl": "https://youtube.com/channel/UC--1YrYgBtfK5ktB3B8cbCw",
                    "time": "4:37",
                    "second": 277
                },
                {
                    "SongTitle": "Vising《 長大以後 》Lyric Video",
                    "SongID": "Elb9-GHqxfY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Elb9-GHqxfY&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=Elb9-GHqxfY&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "雙下巴Indie Music",
                    "ArtistID": "UCFwjMT3zjVLCIVtAU4PGZHQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCFwjMT3zjVLCIVtAU4PGZHQ",
                    "ArtistUrl": "https://youtube.com/channel/UCFwjMT3zjVLCIVtAU4PGZHQ",
                    "time": "5:13",
                    "second": 313
                },
                {
                    "SongTitle": "無法度按捺",
                    "SongID": "yRNia0_tbgY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=yRNia0_tbgY&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=yRNia0_tbgY&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "Why Not?",
                    "ArtistID": "UCQGQ2KA7OBz7NTx9x7wmQBA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCQGQ2KA7OBz7NTx9x7wmQBA",
                    "ArtistUrl": "https://youtube.com/channel/UCQGQ2KA7OBz7NTx9x7wmQBA",
                    "time": "5:46",
                    "second": 346
                },
                {
                    "SongTitle": "孔雀眼 JADE EYES【VIVIAN】歌詞 MV",
                    "SongID": "rMYct5ZSERc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=rMYct5ZSERc&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=rMYct5ZSERc&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "黑市音樂",
                    "ArtistID": "UC7MMGaCyQGmuIWq8zvpHkgQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7MMGaCyQGmuIWq8zvpHkgQ",
                    "ArtistUrl": "https://youtube.com/channel/UC7MMGaCyQGmuIWq8zvpHkgQ",
                    "time": "3:35",
                    "second": 215
                },
                {
                    "SongTitle": "水水Mizu98 - 她Gucciㄉ時候眼淚總是Prada PradaㄉDior(Official Audio)(Original Ver.)",
                    "SongID": "VR2sfNabfC8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=VR2sfNabfC8&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=VR2sfNabfC8&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "Mizu98",
                    "ArtistID": "UCJJFwbHVKG6oHmJIzPzi7mA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCJJFwbHVKG6oHmJIzPzi7mA",
                    "ArtistUrl": "https://youtube.com/channel/UCJJFwbHVKG6oHmJIzPzi7mA",
                    "time": "3:30",
                    "second": 210
                },
                {
                    "SongTitle": "四分衛 backquarter / 項鍊 Necklace",
                    "SongID": "wsLsZSlx9Zs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=wsLsZSlx9Zs&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=wsLsZSlx9Zs&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "chatenoire",
                    "ArtistID": "UCgv8NjcCqcVQIWaD-bMuqYw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCgv8NjcCqcVQIWaD-bMuqYw",
                    "ArtistUrl": "https://youtube.com/channel/UCgv8NjcCqcVQIWaD-bMuqYw",
                    "time": "4:24",
                    "second": 264
                },
                {
                    "SongTitle": "四分衛 (Quarterback) - 魔毯 Official Music Video",
                    "SongID": "f1zWh9MBDFY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=f1zWh9MBDFY&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=f1zWh9MBDFY&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "阿爾發音樂",
                    "ArtistID": "UCirguiAzkqU24_-h1zafCcA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCirguiAzkqU24_-h1zafCcA",
                    "ArtistUrl": "https://youtube.com/channel/UCirguiAzkqU24_-h1zafCcA",
                    "time": "6:14",
                    "second": 374
                },
                {
                    "SongTitle": "石頭",
                    "SongID": "ZHW28MSdPbo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ZHW28MSdPbo&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=ZHW28MSdPbo&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "生命樹",
                    "ArtistID": "UCx7VxSPUw58c3FJggUTl-QQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCx7VxSPUw58c3FJggUTl-QQ",
                    "ArtistUrl": "https://youtube.com/channel/UCx7VxSPUw58c3FJggUTl-QQ",
                    "time": "4:45",
                    "second": 285
                },
                {
                    "SongTitle": "白鐵仔Pehthiha - 鯨魚",
                    "SongID": "CnOcMl1I7n0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=CnOcMl1I7n0&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=CnOcMl1I7n0&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "白鐵仔Pehthiha",
                    "ArtistID": "UCcRfzMzJ7-_RnF0Wr6fHXxQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCcRfzMzJ7-_RnF0Wr6fHXxQ",
                    "ArtistUrl": "https://youtube.com/channel/UCcRfzMzJ7-_RnF0Wr6fHXxQ",
                    "time": "4:27",
                    "second": 267
                },
                {
                    "SongTitle": "星夜裡的人",
                    "SongID": "RnsVmZDQaJA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=RnsVmZDQaJA&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=RnsVmZDQaJA&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "先知瑪莉",
                    "ArtistID": "UCZf35BAgdTIqHyok9tF8rIA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCZf35BAgdTIqHyok9tF8rIA",
                    "ArtistUrl": "https://youtube.com/channel/UCZf35BAgdTIqHyok9tF8rIA",
                    "time": "5:18",
                    "second": 318
                },
                {
                    "SongTitle": "Mary See the Future - 多雨的城市",
                    "SongID": "GgZaIqusssA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=GgZaIqusssA&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=GgZaIqusssA&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "Mary See the Future / 先知瑪莉",
                    "ArtistID": "UC1pEfc4TXyAQ8jak1KTTU1A",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC1pEfc4TXyAQ8jak1KTTU1A",
                    "ArtistUrl": "https://youtube.com/channel/UC1pEfc4TXyAQ8jak1KTTU1A",
                    "time": "6:03",
                    "second": 363
                },
                {
                    "SongTitle": "Lucid Dream",
                    "SongID": "kuo2a2OW1FQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=kuo2a2OW1FQ&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=kuo2a2OW1FQ&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "先知瑪莉",
                    "ArtistID": "UCZf35BAgdTIqHyok9tF8rIA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCZf35BAgdTIqHyok9tF8rIA",
                    "ArtistUrl": "https://youtube.com/channel/UCZf35BAgdTIqHyok9tF8rIA",
                    "time": "6:02",
                    "second": 362
                },
                {
                    "SongTitle": "Cheer",
                    "SongID": "FHFWlckPR-E",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=FHFWlckPR-E&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=FHFWlckPR-E&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "先知瑪莉",
                    "ArtistID": "UCZf35BAgdTIqHyok9tF8rIA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCZf35BAgdTIqHyok9tF8rIA",
                    "ArtistUrl": "https://youtube.com/channel/UCZf35BAgdTIqHyok9tF8rIA",
                    "time": "5:57",
                    "second": 357
                },
                {
                    "SongTitle": "Mary See the Future-11. 醉難寫的歌",
                    "SongID": "HqKsIExFKCE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=HqKsIExFKCE&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=HqKsIExFKCE&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "lindy00623",
                    "ArtistID": "UC-3RrwU6K_h4q33XMunoctQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC-3RrwU6K_h4q33XMunoctQ",
                    "ArtistUrl": "https://youtube.com/channel/UC-3RrwU6K_h4q33XMunoctQ",
                    "time": "6:26",
                    "second": 386
                },
                {
                    "SongTitle": "icyball 冰球樂團 - 響起 (Official Video)",
                    "SongID": "FHIOYQ36fjQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=FHIOYQ36fjQ&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=FHIOYQ36fjQ&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "icyball 冰球樂團",
                    "ArtistID": "UC02wW27zWTA1nr9Rinf9_aw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC02wW27zWTA1nr9Rinf9_aw",
                    "ArtistUrl": "https://youtube.com/channel/UC02wW27zWTA1nr9Rinf9_aw",
                    "time": "5:40",
                    "second": 340
                },
                {
                    "SongTitle": "Dear John",
                    "SongID": "ktUAPy_cLCA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ktUAPy_cLCA&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=ktUAPy_cLCA&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "回聲樂團",
                    "ArtistID": "UCjrAC0x3X20gSSELuPWJqAQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCjrAC0x3X20gSSELuPWJqAQ",
                    "ArtistUrl": "https://youtube.com/channel/UCjrAC0x3X20gSSELuPWJqAQ",
                    "time": "4:28",
                    "second": 268
                },
                {
                    "SongTitle": "蒸發",
                    "SongID": "s09oSv2NZpE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=s09oSv2NZpE&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=s09oSv2NZpE&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "好樂團",
                    "ArtistID": "UCbNspVIs5kbxKbzg2oB880g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCbNspVIs5kbxKbzg2oB880g",
                    "ArtistUrl": "https://youtube.com/channel/UCbNspVIs5kbxKbzg2oB880g",
                    "time": "8:10",
                    "second": 490
                },
                {
                    "SongTitle": "好樂團 GoodBand ─《我把我的青春給你》Official Music Video",
                    "SongID": "9MMIB61e6sM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=9MMIB61e6sM&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=9MMIB61e6sM&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "好樂團",
                    "ArtistID": "UCbNspVIs5kbxKbzg2oB880g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCbNspVIs5kbxKbzg2oB880g",
                    "ArtistUrl": "https://youtube.com/channel/UCbNspVIs5kbxKbzg2oB880g",
                    "time": "4:13",
                    "second": 253
                },
                {
                    "SongTitle": "陪你的貓睡午覺",
                    "SongID": "MVXmY3dwono",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=MVXmY3dwono&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=MVXmY3dwono&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "好樂團",
                    "ArtistID": "UCbNspVIs5kbxKbzg2oB880g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCbNspVIs5kbxKbzg2oB880g",
                    "ArtistUrl": "https://youtube.com/channel/UCbNspVIs5kbxKbzg2oB880g",
                    "time": "3:45",
                    "second": 225
                },
                {
                    "SongTitle": "2013/01/09 UNI可樂 宇宙人 神秘河流unplugged版",
                    "SongID": "nJxvutl3EYk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=nJxvutl3EYk&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=nJxvutl3EYk&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "Cece Lee",
                    "ArtistID": "UCEHSqlNtGYn4ixvaELQBc2w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCEHSqlNtGYn4ixvaELQBc2w",
                    "ArtistUrl": "https://youtube.com/channel/UCEHSqlNtGYn4ixvaELQBc2w",
                    "time": "2:13",
                    "second": 133
                },
                {
                    "SongTitle": "不難過--HAVE SENSE有感覺樂團【官方完整版】",
                    "SongID": "9QM4HwCi5XI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=9QM4HwCi5XI&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=9QM4HwCi5XI&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "有感覺",
                    "ArtistID": "UCMiGuqTq8LFYeKnn1OTLdRA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCMiGuqTq8LFYeKnn1OTLdRA",
                    "ArtistUrl": "https://youtube.com/channel/UCMiGuqTq8LFYeKnn1OTLdRA",
                    "time": "4:31",
                    "second": 271
                },
                {
                    "SongTitle": "老王樂隊-安久-2019大港開唱",
                    "SongID": "dhQXCE3u2dM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=dhQXCE3u2dM&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=dhQXCE3u2dM&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "小羅",
                    "ArtistID": "UCJD8U_SgrfNxfYnbpjZiVLQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCJD8U_SgrfNxfYnbpjZiVLQ",
                    "ArtistUrl": "https://youtube.com/channel/UCJD8U_SgrfNxfYnbpjZiVLQ",
                    "time": "5:21",
                    "second": 321
                },
                {
                    "SongTitle": "再等一下就天亮了",
                    "SongID": "5GTGOYEdPIk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=5GTGOYEdPIk&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=5GTGOYEdPIk&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "老王樂隊",
                    "ArtistID": "UCdxpW3sUpUGJIwKhHam5bhQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCdxpW3sUpUGJIwKhHam5bhQ",
                    "ArtistUrl": "https://youtube.com/channel/UCdxpW3sUpUGJIwKhHam5bhQ",
                    "time": "4:24",
                    "second": 264
                },
                {
                    "SongTitle": "我對自己開了一槍",
                    "SongID": "Ro29toKIJZc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Ro29toKIJZc&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=Ro29toKIJZc&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "佛跳牆",
                    "ArtistID": "UCDUFxGQYrCV0c-B0V13vgrw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCDUFxGQYrCV0c-B0V13vgrw",
                    "ArtistUrl": "https://youtube.com/channel/UCDUFxGQYrCV0c-B0V13vgrw",
                    "time": "4:27",
                    "second": 267
                },
                {
                    "SongTitle": "告五人/Accusefive  在這座城市遺失了你 歌詞Lyrics   與你相遇 是在一個單純美好的世界",
                    "SongID": "lWLHG_mcDw4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=lWLHG_mcDw4&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=lWLHG_mcDw4&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "葉婷🌸",
                    "ArtistID": "UCDpjBG3rk7nquTNQDnPKW8g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCDpjBG3rk7nquTNQDnPKW8g",
                    "ArtistUrl": "https://youtube.com/channel/UCDpjBG3rk7nquTNQDnPKW8g",
                    "time": "5:49",
                    "second": 349
                },
                {
                    "SongTitle": "愛人錯過",
                    "SongID": "6D79CYTxvOM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=6D79CYTxvOM&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=6D79CYTxvOM&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "告五人",
                    "ArtistID": "UC2lbjBep5vvd-Spo0oGn97g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC2lbjBep5vvd-Spo0oGn97g",
                    "ArtistUrl": "https://youtube.com/channel/UC2lbjBep5vvd-Spo0oGn97g",
                    "time": "5:18",
                    "second": 318
                },
                {
                    "SongTitle": "Theseus 忒修斯《 If we were sparking stars 如果我們都是繁星 》Lyric Video",
                    "SongID": "ql6TrFwXvH8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ql6TrFwXvH8&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=ql6TrFwXvH8&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "雙下巴Indie Music",
                    "ArtistID": "UCFwjMT3zjVLCIVtAU4PGZHQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCFwjMT3zjVLCIVtAU4PGZHQ",
                    "ArtistUrl": "https://youtube.com/channel/UCFwjMT3zjVLCIVtAU4PGZHQ",
                    "time": "5:20",
                    "second": 320
                },
                {
                    "SongTitle": "全世界我最喜歡你(可是你都不知道)",
                    "SongID": "3uIbahu_S6s",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=3uIbahu_S6s&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=3uIbahu_S6s&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "Come On! Bay Bay!",
                    "ArtistID": "UCZl3-OXSbGbFz43Hd1_YfHg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCZl3-OXSbGbFz43Hd1_YfHg",
                    "ArtistUrl": "https://youtube.com/channel/UCZl3-OXSbGbFz43Hd1_YfHg",
                    "time": "5:18",
                    "second": 318
                },
                {
                    "SongTitle": "魚",
                    "SongID": "Dnz-BTz9eDU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Dnz-BTz9eDU&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=Dnz-BTz9eDU&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "怕胖團",
                    "ArtistID": "UCkL6sVmiH6egCouMEPuVu2w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCkL6sVmiH6egCouMEPuVu2w",
                    "ArtistUrl": "https://youtube.com/channel/UCkL6sVmiH6egCouMEPuVu2w",
                    "time": "4:46",
                    "second": 286
                },
                {
                    "SongTitle": "嘟 嘟 嘟 嘟 嘟",
                    "SongID": "nkyheC0N9ZU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=nkyheC0N9ZU&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=nkyheC0N9ZU&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "怕胖團",
                    "ArtistID": "UCkL6sVmiH6egCouMEPuVu2w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCkL6sVmiH6egCouMEPuVu2w",
                    "ArtistUrl": "https://youtube.com/channel/UCkL6sVmiH6egCouMEPuVu2w",
                    "time": "5:27",
                    "second": 327
                },
                {
                    "SongTitle": "怕胖團-媽媽的筆記本",
                    "SongID": "x2OaApDM8rw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=x2OaApDM8rw&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=x2OaApDM8rw&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "chen0428",
                    "ArtistID": "UCDMKR7GMKxfVY8x4Q7aL1Ag",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCDMKR7GMKxfVY8x4Q7aL1Ag",
                    "ArtistUrl": "https://youtube.com/channel/UCDMKR7GMKxfVY8x4Q7aL1Ag",
                    "time": "4:12",
                    "second": 252
                },
                {
                    "SongTitle": "當你在最需要的時候",
                    "SongID": "EXM3c3Ie4io",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=EXM3c3Ie4io&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=EXM3c3Ie4io&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "怕胖團",
                    "ArtistID": "UCkL6sVmiH6egCouMEPuVu2w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCkL6sVmiH6egCouMEPuVu2w",
                    "ArtistUrl": "https://youtube.com/channel/UCkL6sVmiH6egCouMEPuVu2w",
                    "time": "4:10",
                    "second": 250
                },
                {
                    "SongTitle": "房東的貓- 斑馬 斑馬",
                    "SongID": "vcncUq1Jc2M",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=vcncUq1Jc2M&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=vcncUq1Jc2M&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "RAD",
                    "ArtistID": "UCvG9j3VDUDga903lSjwej7Q",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCvG9j3VDUDga903lSjwej7Q",
                    "ArtistUrl": "https://youtube.com/channel/UCvG9j3VDUDga903lSjwej7Q",
                    "time": "4:12",
                    "second": 252
                },
                {
                    "SongTitle": "【HD】房東的貓 - 美好事物 (2017) [歌詞字幕][完整高清音質] The Landlord's Cat - Good things (2017)",
                    "SongID": "YYb1rjmMn98",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=YYb1rjmMn98&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=YYb1rjmMn98&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "BELLA PING MUSIC CHANNEL",
                    "ArtistID": "UCc0vR4YlrUprAX_AMylgOvg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCc0vR4YlrUprAX_AMylgOvg",
                    "ArtistUrl": "https://youtube.com/channel/UCc0vR4YlrUprAX_AMylgOvg",
                    "time": "4:15",
                    "second": 255
                },
                {
                    "SongTitle": "【HD】房東的貓 - 往往 [歌詞字幕][完整高清音質] ♫ The Landlord's Cat - Often",
                    "SongID": "i9yd9LbAyeE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=i9yd9LbAyeE&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=i9yd9LbAyeE&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "BELLA PING MUSIC CHANNEL",
                    "ArtistID": "UCc0vR4YlrUprAX_AMylgOvg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCc0vR4YlrUprAX_AMylgOvg",
                    "ArtistUrl": "https://youtube.com/channel/UCc0vR4YlrUprAX_AMylgOvg",
                    "time": "4:41",
                    "second": 281
                },
                {
                    "SongTitle": "房東的貓《你是我最愚蠢的一次浪漫 》Lyric Video",
                    "SongID": "DHMx_B9-zdY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=DHMx_B9-zdY&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=DHMx_B9-zdY&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "雙下巴Indie Music",
                    "ArtistID": "UCFwjMT3zjVLCIVtAU4PGZHQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCFwjMT3zjVLCIVtAU4PGZHQ",
                    "ArtistUrl": "https://youtube.com/channel/UCFwjMT3zjVLCIVtAU4PGZHQ",
                    "time": "3:32",
                    "second": 212
                },
                {
                    "SongTitle": "拍謝少年 Sorry Youth －骨力走傱 Running On (Live in 詹記麻辣火鍋-新莊總店)",
                    "SongID": "_ymz7g8gP54",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=_ymz7g8gP54&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=_ymz7g8gP54&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "拍謝少年",
                    "ArtistID": "UCThJUmGlTv48y8vdnAPOJSg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCThJUmGlTv48y8vdnAPOJSg",
                    "ArtistUrl": "https://youtube.com/channel/UCThJUmGlTv48y8vdnAPOJSg",
                    "time": "5:43",
                    "second": 343
                },
                {
                    "SongTitle": "旺福 Won Fu《我當你空氣 You Are My Air》 Official Music Video",
                    "SongID": "1hKkAM-ADDU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=1hKkAM-ADDU&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=1hKkAM-ADDU&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "旺福 WONFU",
                    "ArtistID": "UCZvQ_io8J1qHHkTDl31fCcA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCZvQ_io8J1qHHkTDl31fCcA",
                    "ArtistUrl": "https://youtube.com/channel/UCZvQ_io8J1qHHkTDl31fCcA",
                    "time": "3:56",
                    "second": 236
                },
                {
                    "SongTitle": "Frandé 法蘭黛樂團/特別",
                    "SongID": "XYOTu6lOSI0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=XYOTu6lOSI0&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=XYOTu6lOSI0&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "SMW",
                    "ArtistID": "UCCJUtLSQXeGxAFXsw6wHrhg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCCJUtLSQXeGxAFXsw6wHrhg",
                    "ArtistUrl": "https://youtube.com/channel/UCCJUtLSQXeGxAFXsw6wHrhg",
                    "time": "4:11",
                    "second": 251
                },
                {
                    "SongTitle": "愛人心",
                    "SongID": "5VjyxFytcu0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=5VjyxFytcu0&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=5VjyxFytcu0&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "法蘭黛樂團",
                    "ArtistID": "UCplLIKDD6xphLPvE7qvqApg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCplLIKDD6xphLPvE7qvqApg",
                    "ArtistUrl": "https://youtube.com/channel/UCplLIKDD6xphLPvE7qvqApg",
                    "time": "5:11",
                    "second": 311
                },
                {
                    "SongTitle": "Frandé法蘭黛《受寵若驚》Official Lyric Video",
                    "SongID": "wXM9x2UAeX8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=wXM9x2UAeX8&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=wXM9x2UAeX8&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "非常棒 Fusion Bomb",
                    "ArtistID": "UCiH8eJQ3bkmSilf2wC0lijQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiH8eJQ3bkmSilf2wC0lijQ",
                    "ArtistUrl": "https://youtube.com/channel/UCiH8eJQ3bkmSilf2wC0lijQ",
                    "time": "4:52",
                    "second": 292
                },
                {
                    "SongTitle": "Frandé法蘭黛《一時脆弱》Official MV - 【他們在畢業的前一天爆炸Ⅱ】片頭曲",
                    "SongID": "N9D0il0O_EM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=N9D0il0O_EM&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=N9D0il0O_EM&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "非常棒 Fusion Bomb",
                    "ArtistID": "UCiH8eJQ3bkmSilf2wC0lijQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiH8eJQ3bkmSilf2wC0lijQ",
                    "ArtistUrl": "https://youtube.com/channel/UCiH8eJQ3bkmSilf2wC0lijQ",
                    "time": "4:51",
                    "second": 291
                },
                {
                    "SongTitle": "Frandé 法蘭黛樂團 首張專輯【05.Every Word】",
                    "SongID": "7LkczhAU4VY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=7LkczhAU4VY&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=7LkczhAU4VY&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "許大雅",
                    "ArtistID": "UCX7i14Q64NFBP_xAKOHWBgg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCX7i14Q64NFBP_xAKOHWBgg",
                    "ArtistUrl": "https://youtube.com/channel/UCX7i14Q64NFBP_xAKOHWBgg",
                    "time": "4:26",
                    "second": 266
                },
                {
                    "SongTitle": "非人物種 - 擺渡人 PV / Inhuman band - Boat man",
                    "SongID": "M6MrFl3bePE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=M6MrFl3bePE&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=M6MrFl3bePE&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "SHAMEPRODUCTION",
                    "ArtistID": "UCptgMpJqncNMGJn5LXltZiQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCptgMpJqncNMGJn5LXltZiQ",
                    "ArtistUrl": "https://youtube.com/channel/UCptgMpJqncNMGJn5LXltZiQ",
                    "time": "4:16",
                    "second": 256
                },
                {
                    "SongTitle": "南西肯恩 - 蒙毅將軍",
                    "SongID": "1kM4-o4c-qY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=1kM4-o4c-qY&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=1kM4-o4c-qY&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "Xii_u",
                    "ArtistID": "UCTWxp0E4geReA08qcVyNMgg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCTWxp0E4geReA08qcVyNMgg",
                    "ArtistUrl": "https://youtube.com/channel/UCTWxp0E4geReA08qcVyNMgg",
                    "time": "4:39",
                    "second": 279
                },
                {
                    "SongTitle": "捲菸",
                    "SongID": "S4JLJVVjevI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=S4JLJVVjevI&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=S4JLJVVjevI&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "Bisiugroup",
                    "ArtistID": "UC9fwTdQyoeDFhOhNN3CQDlg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC9fwTdQyoeDFhOhNN3CQDlg",
                    "ArtistUrl": "https://youtube.com/channel/UC9fwTdQyoeDFhOhNN3CQDlg",
                    "time": "3:58",
                    "second": 238
                },
                {
                    "SongTitle": "我要你愛",
                    "SongID": "ouQwJj1V2pE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ouQwJj1V2pE&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=ouQwJj1V2pE&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "Bisiugroup",
                    "ArtistID": "UC9fwTdQyoeDFhOhNN3CQDlg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC9fwTdQyoeDFhOhNN3CQDlg",
                    "ArtistUrl": "https://youtube.com/channel/UC9fwTdQyoeDFhOhNN3CQDlg",
                    "time": "4:17",
                    "second": 257
                },
                {
                    "SongTitle": "小老婆",
                    "SongID": "Tt7vKpe_1NI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Tt7vKpe_1NI&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=Tt7vKpe_1NI&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "Bisiugroup",
                    "ArtistID": "UC9fwTdQyoeDFhOhNN3CQDlg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC9fwTdQyoeDFhOhNN3CQDlg",
                    "ArtistUrl": "https://youtube.com/channel/UC9fwTdQyoeDFhOhNN3CQDlg",
                    "time": "6:13",
                    "second": 373
                },
                {
                    "SongTitle": "日常",
                    "SongID": "_vGN_dFtAQI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=_vGN_dFtAQI&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=_vGN_dFtAQI&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "茄子蛋",
                    "ArtistID": "UChQoPspEw6hGSwQQDOLpeqg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UChQoPspEw6hGSwQQDOLpeqg",
                    "ArtistUrl": "https://youtube.com/channel/UChQoPspEw6hGSwQQDOLpeqg",
                    "time": "4:38",
                    "second": 278
                },
                {
                    "SongTitle": "這款自作多情",
                    "SongID": "UocMW7BG0ls",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=UocMW7BG0ls&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "SongUrl": "https://youtube.com/watch?v=UocMW7BG0ls&list=PLaK9WqR_bQp_TCopXnlSoB4_-MGk3lpFk",
                    "Artist": "茄子蛋",
                    "ArtistID": "UChQoPspEw6hGSwQQDOLpeqg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UChQoPspEw6hGSwQQDOLpeqg",
                    "ArtistUrl": "https://youtube.com/channel/UChQoPspEw6hGSwQQDOLpeqg",
                    "time": "6:36",
                    "second": 396
                }
            ]
        }
    ];
    return { data };
});
