export default defineEventHandler((event) => {
    const data = [
        {
            "ListName": "抖音熱門歌曲2023",
            "SongList": [
                {
                    "SongTitle": "梧彤Vickie - 我會等（女版）『我會等枯樹生出芽 開出新的花，我會等一場雨落下 把回憶都沖刷，再與你一起去看外面世界 到底有多大。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "4Qq82Q2Tscw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=4Qq82Q2Tscw&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=4Qq82Q2Tscw&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "3:16",
                    "second": 196
                },
                {
                    "SongTitle": "梧彤Vickie - 我會等（女版）『我會等枯樹生出芽 開出新的花，我會等一場雨落下 把回憶都沖刷，再與你一起去看外面世界 到底有多大。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "4Qq82Q2Tscw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=4Qq82Q2Tscw&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=4Qq82Q2Tscw&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "3:16",
                    "second": 196
                },
                {
                    "SongTitle": "向云端 - 小霞/海洋Bo   动态歌词/Lyrics",
                    "SongID": "sokq7y4Go8E",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=sokq7y4Go8E&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=sokq7y4Go8E&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "Getrichi",
                    "ArtistID": "UChQQ0rtFBQXfQyfLNVizVYA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UChQQ0rtFBQXfQyfLNVizVYA",
                    "ArtistUrl": "https://youtube.com/channel/UChQQ0rtFBQXfQyfLNVizVYA",
                    "time": "4:12",
                    "second": 252
                },
                {
                    "SongTitle": "一隻白羊 - 說給海聽「我把愛你說給海聽 明知道大海不會應」【動態歌詞/PinyinLyrics】♪",
                    "SongID": "FIsUzRwVegs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=FIsUzRwVegs&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=FIsUzRwVegs&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "ORT Music",
                    "ArtistID": "UCi5GyXtmy8Tl-YAvcMhxXwg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCi5GyXtmy8Tl-YAvcMhxXwg",
                    "ArtistUrl": "https://youtube.com/channel/UCi5GyXtmy8Tl-YAvcMhxXwg",
                    "time": "3:04",
                    "second": 184
                },
                {
                    "SongTitle": "豆芽魚 - 小海「被雨淋濕的公車站台 只想你的末班車不要到來」【動態歌詞/PinyinLyrics】♪",
                    "SongID": "liIxyDXOeMM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=liIxyDXOeMM&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=liIxyDXOeMM&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "ORT Music",
                    "ArtistID": "UCi5GyXtmy8Tl-YAvcMhxXwg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCi5GyXtmy8Tl-YAvcMhxXwg",
                    "ArtistUrl": "https://youtube.com/channel/UCi5GyXtmy8Tl-YAvcMhxXwg",
                    "time": "2:52",
                    "second": 172
                },
                {
                    "SongTitle": "虎妹Huu / 承桓 - 做自己的光「做自己的光 不需要多亮 曾受過的傷 會長出翅膀」【動態歌詞/PinyinLyrics】♪",
                    "SongID": "4iS47Q3AZqc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=4iS47Q3AZqc&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=4iS47Q3AZqc&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "ORT Music",
                    "ArtistID": "UCi5GyXtmy8Tl-YAvcMhxXwg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCi5GyXtmy8Tl-YAvcMhxXwg",
                    "ArtistUrl": "https://youtube.com/channel/UCi5GyXtmy8Tl-YAvcMhxXwg",
                    "time": "4:27",
                    "second": 267
                },
                {
                    "SongTitle": "旺仔小喬 -  如果愛忘了「如果愛忘了 淚不想落下 那些幸福啊 讓她替我到達」【動態歌詞】♪",
                    "SongID": "RNgjMja3ceI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=RNgjMja3ceI&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=RNgjMja3ceI&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4Leaf Music",
                    "ArtistID": "UCAyByk4DJ9rRlRB1cs1seMQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCAyByk4DJ9rRlRB1cs1seMQ",
                    "ArtistUrl": "https://youtube.com/channel/UCAyByk4DJ9rRlRB1cs1seMQ",
                    "time": "3:44",
                    "second": 224
                },
                {
                    "SongTitle": "Lil笑笑 - 山茶花讀不懂白玫瑰「山茶花 讀不懂白玫瑰 北山的風吹不到南山尾」【動態歌詞/PinyinLyrics】♪",
                    "SongID": "qMnvbZQXKG8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=qMnvbZQXKG8&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=qMnvbZQXKG8&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "ORT Music",
                    "ArtistID": "UCi5GyXtmy8Tl-YAvcMhxXwg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCi5GyXtmy8Tl-YAvcMhxXwg",
                    "ArtistUrl": "https://youtube.com/channel/UCi5GyXtmy8Tl-YAvcMhxXwg",
                    "time": "3:21",
                    "second": 201
                },
                {
                    "SongTitle": "覆予 - 從你的世界消失『我終於哭著決定從你的世界消失，給你的另外一位騰出重要的位置。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "Jvi3v5jc-nU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Jvi3v5jc-nU&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=Jvi3v5jc-nU&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "3:54",
                    "second": 234
                },
                {
                    "SongTitle": "毒藥 - 後來才懂『以為深愛過 過往點滴你會捨不得，後來才懂 感情不能強求勒索。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "_E053v0V4js",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=_E053v0V4js&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=_E053v0V4js&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "3:59",
                    "second": 239
                },
                {
                    "SongTitle": "KKECHO / 那奇沃夫 - 苦咖啡·唯一「BABY 你就是我的唯一 兩個世界都變形」【動態歌詞/PinyinLyrics】♪",
                    "SongID": "8vTsI1rIDQw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=8vTsI1rIDQw&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=8vTsI1rIDQw&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "ORT Music",
                    "ArtistID": "UCi5GyXtmy8Tl-YAvcMhxXwg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCi5GyXtmy8Tl-YAvcMhxXwg",
                    "ArtistUrl": "https://youtube.com/channel/UCi5GyXtmy8Tl-YAvcMhxXwg",
                    "time": "2:59",
                    "second": 179
                },
                {
                    "SongTitle": "嘿人李逵Noisemakers - 寶貝在幹嘛『寶貝在幹嘛～木啊在嗎 睡了嘛？寶貝在幹嘛 為啥沒回話。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "6BynBGqjCUQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=6BynBGqjCUQ&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=6BynBGqjCUQ&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "2:21",
                    "second": 141
                },
                {
                    "SongTitle": "陳小滿 - 愛是獎勵還是懲罰『後來他下雨的時候會在誰的傘下，總在等時間把想念沖刷 等幾個冬夏。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "2Wf0ECuNCLQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=2Wf0ECuNCLQ&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=2Wf0ECuNCLQ&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "3:13",
                    "second": 193
                },
                {
                    "SongTitle": "徐婧菀Voniya - 偏離『像太陽月亮的交替靠近就偏離，像黑夜白天的交替總是在遠離。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "hM57zhd9etE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=hM57zhd9etE&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=hM57zhd9etE&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "3:55",
                    "second": 235
                },
                {
                    "SongTitle": "王理文 - 現在的他『可現在的他 牽著誰回家，說著同樣 對我說的話。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "Hhjd9JZ9xJ0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Hhjd9JZ9xJ0&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=Hhjd9JZ9xJ0&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "3:06",
                    "second": 186
                },
                {
                    "SongTitle": "溫婉之 - 前男友『你的身份已改變，這前男友的標籤 想你是種夢魘。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "iRbEDqqEckk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=iRbEDqqEckk&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=iRbEDqqEckk&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "3:33",
                    "second": 213
                },
                {
                    "SongTitle": "毒藥 - 季節更替『你冷暖不定就好像季節更替，我曾經也很憧憬 與你夢中的婚禮。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "jYK3O1Y3m1E",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=jYK3O1Y3m1E&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=jYK3O1Y3m1E&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "4:25",
                    "second": 265
                },
                {
                    "SongTitle": "en - 一直很安靜·2023『給你的愛一直很安靜，來交換你偶爾給的關心，明明是三個人的電影，我卻始終不能有姓名。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "9apxVjMDtS8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=9apxVjMDtS8&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=9apxVjMDtS8&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "3:27",
                    "second": 207
                },
                {
                    "SongTitle": "丁芙妮 - 過『就當我只是路過 經過 錯過，反正你從沒來過 愛過也不必難過。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "xkYrl9yeUgg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=xkYrl9yeUgg&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=xkYrl9yeUgg&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "4:11",
                    "second": 251
                },
                {
                    "SongTitle": "周思涵 - 你明明說你很愛我『你明明說你很愛我，卻在危機四伏的世界讓我流離失所。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "OaixDtqQO0w",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=OaixDtqQO0w&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=OaixDtqQO0w&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "4:21",
                    "second": 261
                },
                {
                    "SongTitle": "Joysaaaa - 忘不掉的星『忘不掉的人像是星星，到了晚上才顯得特別清晰。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "b-shcFHs3xI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=b-shcFHs3xI&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=b-shcFHs3xI&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "4:20",
                    "second": 260
                },
                {
                    "SongTitle": "en - 別說對不起『錯事你都做了 對不起別說了，憑什麼你心安理得。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "8vORax09-Vw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=8vORax09-Vw&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=8vORax09-Vw&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "3:39",
                    "second": 219
                },
                {
                    "SongTitle": "張遠 - 你放下了嗎『想問問後來的你 全都放下了嗎，過去受的傷 是否還隱隱作響。』【高音質|動態歌詞Lyrics】♫ ·《照亮你》電視劇插曲",
                    "SongID": "jN2F4j_xtCk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=jN2F4j_xtCk&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=jN2F4j_xtCk&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "4:38",
                    "second": 278
                },
                {
                    "SongTitle": "任然 - 可最後『記得這一分鐘的撕心裂肺的對你說再見和珍重，往事不說是害怕眼淚不灑脫。』【動態歌詞MV】",
                    "SongID": "24y_4Rnc7n4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=24y_4Rnc7n4&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=24y_4Rnc7n4&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "YunShang-Music",
                    "ArtistID": "UCrWNEmqwt4iTmqhhI7Caeyw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCrWNEmqwt4iTmqhhI7Caeyw",
                    "ArtistUrl": "https://youtube.com/channel/UCrWNEmqwt4iTmqhhI7Caeyw",
                    "time": "4:45",
                    "second": 285
                },
                {
                    "SongTitle": "听悲伤的情歌 (戏腔)",
                    "SongID": "qxtUvs72uV0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=qxtUvs72uV0&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=qxtUvs72uV0&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "苏星婕",
                    "ArtistID": "UCiWiBtnOsEnQBG2kjitiATA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiWiBtnOsEnQBG2kjitiATA",
                    "ArtistUrl": "https://youtube.com/channel/UCiWiBtnOsEnQBG2kjitiATA",
                    "time": "3:17",
                    "second": 197
                },
                {
                    "SongTitle": "en - 別說對不起『錯事你都做了 對不起別說了，憑什麼你心安理得。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "LTDeisQqNoo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=LTDeisQqNoo&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=LTDeisQqNoo&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "3:25",
                    "second": 205
                },
                {
                    "SongTitle": "盧盧快閉嘴 - 字字句句『他字字未提喜歡你，你句句都是我願意，他一句寂寞時候的回應 你卻激動不已。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "dys9KC9hM9U",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=dys9KC9hM9U&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=dys9KC9hM9U&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "3:21",
                    "second": 201
                },
                {
                    "SongTitle": "胡66 - 都怪我【動態歌詞】「我怎麼忘也忘不掉 偽裝我從沒受過傷」♪",
                    "SongID": "vsl6k1C4QH0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=vsl6k1C4QH0&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=vsl6k1C4QH0&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "Angelic Music World",
                    "ArtistID": "UC_ol0nA8RUpyRTleAcu8JVw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC_ol0nA8RUpyRTleAcu8JVw",
                    "ArtistUrl": "https://youtube.com/channel/UC_ol0nA8RUpyRTleAcu8JVw",
                    "time": "5:06",
                    "second": 306
                },
                {
                    "SongTitle": "明天你好 Hello Tomorrow [牛奶咖啡] - Chinese, Pinyin & English Translation 歌词英文翻译",
                    "SongID": "bM34yBjOJqQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=bM34yBjOJqQ&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=bM34yBjOJqQ&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "Tempest Jun",
                    "ArtistID": "UCjwC73J7V3KSXaDrPKH-qow",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCjwC73J7V3KSXaDrPKH-qow",
                    "ArtistUrl": "https://youtube.com/channel/UCjwC73J7V3KSXaDrPKH-qow",
                    "time": "4:28",
                    "second": 268
                },
                {
                    "SongTitle": "落空-印子月 【有一颗紧紧依靠着你的心一瞬间落空】",
                    "SongID": "wwmvbKnlkTc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=wwmvbKnlkTc&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=wwmvbKnlkTc&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "Douyin Song 抖音歌曲",
                    "ArtistID": "UC3yJv3RaNvU2FJeppRz9zYw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC3yJv3RaNvU2FJeppRz9zYw",
                    "ArtistUrl": "https://youtube.com/channel/UC3yJv3RaNvU2FJeppRz9zYw",
                    "time": "3:53",
                    "second": 233
                },
                {
                    "SongTitle": "Soul - 空城『這城市那麼空 Alone』【動態歌詞Lyrics】",
                    "SongID": "CzHfHFq1Imo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=CzHfHFq1Imo&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=CzHfHFq1Imo&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "Modern Song Collection",
                    "ArtistID": "UCmZtOkU1etCAXtuX7DUESCg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCmZtOkU1etCAXtuX7DUESCg",
                    "ArtistUrl": "https://youtube.com/channel/UCmZtOkU1etCAXtuX7DUESCg",
                    "time": "4:36",
                    "second": 276
                },
                {
                    "SongTitle": "Ssweetxin_ -  出賣（emo 版「你的多情出賣我的愛情 賠了我的命我賣了一個世界卻換來灰燼」【動態歌詞】♪",
                    "SongID": "Os9sV8VBmdM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Os9sV8VBmdM&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=Os9sV8VBmdM&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4Leaf Music",
                    "ArtistID": "UCAyByk4DJ9rRlRB1cs1seMQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCAyByk4DJ9rRlRB1cs1seMQ",
                    "ArtistUrl": "https://youtube.com/channel/UCAyByk4DJ9rRlRB1cs1seMQ",
                    "time": "3:41",
                    "second": 221
                },
                {
                    "SongTitle": "Capper Ft. 羅言 - 雪 Distance『心甘情願囚禁在深淵 舔舐著傷口和刀尖』【動態歌詞】",
                    "SongID": "oIZHzFt1okQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=oIZHzFt1okQ&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=oIZHzFt1okQ&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "Music in the Air",
                    "ArtistID": "UC2nVDqJIlWfFkDaYHWs7ZQQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC2nVDqJIlWfFkDaYHWs7ZQQ",
                    "ArtistUrl": "https://youtube.com/channel/UC2nVDqJIlWfFkDaYHWs7ZQQ",
                    "time": "2:46",
                    "second": 166
                },
                {
                    "SongTitle": "h3R3 - 我又想你了『你知不知道我又想你了，你知不知道我有多難過。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "_aROJVRjc6k",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=_aROJVRjc6k&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=_aROJVRjc6k&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "2:46",
                    "second": 166
                },
                {
                    "SongTitle": "旺仔小喬 - 桃花諾「一寸土一年木一花一樹一貪圖 情是種愛偏開在迷途」【動態歌詞/PinyinLyrics】♪",
                    "SongID": "FKN1k6B02VM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=FKN1k6B02VM&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=FKN1k6B02VM&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "ORT Music",
                    "ArtistID": "UCi5GyXtmy8Tl-YAvcMhxXwg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCi5GyXtmy8Tl-YAvcMhxXwg",
                    "ArtistUrl": "https://youtube.com/channel/UCi5GyXtmy8Tl-YAvcMhxXwg",
                    "time": "3:32",
                    "second": 212
                },
                {
                    "SongTitle": "佤咖啡",
                    "SongID": "LhOrBkQoXPk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=LhOrBkQoXPk&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=LhOrBkQoXPk&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "王云宏",
                    "ArtistID": "UC23Zd0U4z51LyyiEWymebVA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC23Zd0U4z51LyyiEWymebVA",
                    "ArtistUrl": "https://youtube.com/channel/UC23Zd0U4z51LyyiEWymebVA",
                    "time": "2:29",
                    "second": 149
                },
                {
                    "SongTitle": "en - 奉勸『我多愛你不只是怦然心動 我無數次奉勸自己承諾別太放縱』【Lyrics Video】",
                    "SongID": "gbVAMWmPDwk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=gbVAMWmPDwk&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=gbVAMWmPDwk&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "EN",
                    "ArtistID": "UCWZcppoG4hMl99xgxRSDgdw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCWZcppoG4hMl99xgxRSDgdw",
                    "ArtistUrl": "https://youtube.com/channel/UCWZcppoG4hMl99xgxRSDgdw",
                    "time": "4:15",
                    "second": 255
                },
                {
                    "SongTitle": "陳村長 - 愛怎麼了『怎麼我 比想像中脆弱得多』【Lyrics Video】",
                    "SongID": "yjf2Doys0nk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=yjf2Doys0nk&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=yjf2Doys0nk&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "陈村长",
                    "ArtistID": "UCb9GVGtxhyxJlwnFjH0qEAw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCb9GVGtxhyxJlwnFjH0qEAw",
                    "ArtistUrl": "https://youtube.com/channel/UCb9GVGtxhyxJlwnFjH0qEAw",
                    "time": "4:00",
                    "second": 240
                },
                {
                    "SongTitle": "雪 Distance (合作演出：罗言)",
                    "SongID": "NCuVko5Hw6w",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=NCuVko5Hw6w&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=NCuVko5Hw6w&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "Capper",
                    "ArtistID": "UCe6tJ55jn8FY8Haix83KjuA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCe6tJ55jn8FY8Haix83KjuA",
                    "ArtistUrl": "https://youtube.com/channel/UCe6tJ55jn8FY8Haix83KjuA",
                    "time": "2:46",
                    "second": 166
                },
                {
                    "SongTitle": "周林楓 - 忘了『你怎麼忘了 你先說的愛我，抽屜裡放著你送的音樂盒，是不是快樂全被你帶走了。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "1xPm8Tb36uw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=1xPm8Tb36uw&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=1xPm8Tb36uw&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "3:01",
                    "second": 181
                },
                {
                    "SongTitle": "戚薇 - 如果愛忘了『那些幸福啊 讓她替我到達』【動態歌詞Lyrics】",
                    "SongID": "5n6d-BTMznc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=5n6d-BTMznc&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=5n6d-BTMznc&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "RT Music",
                    "ArtistID": "UCZLjOr_udSt0oe5jT-3jl1Q",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCZLjOr_udSt0oe5jT-3jl1Q",
                    "ArtistUrl": "https://youtube.com/channel/UCZLjOr_udSt0oe5jT-3jl1Q",
                    "time": "4:00",
                    "second": 240
                },
                {
                    "SongTitle": "承桓 - 我會等「我會等枯樹生出芽 開出新的花 等著陽光刺破黑暗 第一縷朝霞」【動態歌詞/PinyinLyrics】♪",
                    "SongID": "yaNPy3xKw1M",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=yaNPy3xKw1M&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=yaNPy3xKw1M&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "ORT Music",
                    "ArtistID": "UCi5GyXtmy8Tl-YAvcMhxXwg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCi5GyXtmy8Tl-YAvcMhxXwg",
                    "ArtistUrl": "https://youtube.com/channel/UCi5GyXtmy8Tl-YAvcMhxXwg",
                    "time": "3:17",
                    "second": 197
                },
                {
                    "SongTitle": "汪蘇瀧 - 耿《最好的我們》電影畢業季主題曲「就笑一笑吧 擦一擦眼淚吧」【動態歌詞】♪",
                    "SongID": "zfzO5g1MwpA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=zfzO5g1MwpA&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=zfzO5g1MwpA&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "Angelic Music World",
                    "ArtistID": "UC_ol0nA8RUpyRTleAcu8JVw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC_ol0nA8RUpyRTleAcu8JVw",
                    "ArtistUrl": "https://youtube.com/channel/UC_ol0nA8RUpyRTleAcu8JVw",
                    "time": "4:31",
                    "second": 271
                },
                {
                    "SongTitle": "cici_ - 遺憾也值得「若你感覺累了 一回頭是我」【動態歌詞】♪",
                    "SongID": "7QvoIC4ACr8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=7QvoIC4ACr8&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=7QvoIC4ACr8&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4Leaf Music",
                    "ArtistID": "UCAyByk4DJ9rRlRB1cs1seMQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCAyByk4DJ9rRlRB1cs1seMQ",
                    "ArtistUrl": "https://youtube.com/channel/UCAyByk4DJ9rRlRB1cs1seMQ",
                    "time": "4:22",
                    "second": 262
                },
                {
                    "SongTitle": "吴东旭 - 差點 （吉他男聲版)「我差點就 我差點就碰到夜空的星 可天亮了」【動態歌詞】♪",
                    "SongID": "tHtEkGM9hLQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=tHtEkGM9hLQ&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=tHtEkGM9hLQ&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4Leaf Music",
                    "ArtistID": "UCAyByk4DJ9rRlRB1cs1seMQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCAyByk4DJ9rRlRB1cs1seMQ",
                    "ArtistUrl": "https://youtube.com/channel/UCAyByk4DJ9rRlRB1cs1seMQ",
                    "time": "3:07",
                    "second": 187
                },
                {
                    "SongTitle": "盧盧快閉嘴 - 就讓這大雨全都落下（原唱：容祖兒）『就讓這大雨全都落下，就讓你看不見我臉上的掙扎。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "RySDNNHFII0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=RySDNNHFII0&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=RySDNNHFII0&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "3:53",
                    "second": 233
                },
                {
                    "SongTitle": "容祖兒 - 就讓這大雨全都落下『經歷的美好都要付一點代價，會後悔嗎？會懷念嗎？對你都不痛不癢吧。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "hHC208KAZLo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=hHC208KAZLo&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=hHC208KAZLo&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "4:15",
                    "second": 255
                },
                {
                    "SongTitle": "就让这大雨全都落下-汪苏泷「就让这大雨全都落下，就让你看不见我脸上的挣扎」【动态歌词Lyrics】",
                    "SongID": "i6DhhSGlS1k",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=i6DhhSGlS1k&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=i6DhhSGlS1k&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "Ys Music",
                    "ArtistID": "UC2cjFacHfyHHBpofkwpDPCg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC2cjFacHfyHHBpofkwpDPCg",
                    "ArtistUrl": "https://youtube.com/channel/UC2cjFacHfyHHBpofkwpDPCg",
                    "time": "4:07",
                    "second": 247
                },
                {
                    "SongTitle": "我会等-承桓 【我会等枯树生出芽，开出新的花。等着阳光刺破黑暗，第一缕朝霞。我会等一场雨落下，把回忆都冲刷。再与你一起去看外面世界 ，到底多大。】［动态歌词］",
                    "SongID": "lQm8WYSdVYs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=lQm8WYSdVYs&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=lQm8WYSdVYs&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "KING Music Channel",
                    "ArtistID": "UCHAxtBn7Q8gTJfVusJp1eWQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCHAxtBn7Q8gTJfVusJp1eWQ",
                    "ArtistUrl": "https://youtube.com/channel/UCHAxtBn7Q8gTJfVusJp1eWQ",
                    "time": "3:16",
                    "second": 196
                },
                {
                    "SongTitle": "戴羽彤 - 騙子 (原唱:文夫)『我不過一笑了之，你那蓄謀已久的轉身離開。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "UoPRTkK5KG4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=UoPRTkK5KG4&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=UoPRTkK5KG4&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "3:32",
                    "second": 212
                },
                {
                    "SongTitle": "Dior大穎 - 你愛他勝過愛自己『你要走出夢境，在現實中清醒。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "trAnn4UhISQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=trAnn4UhISQ&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=trAnn4UhISQ&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "4:01",
                    "second": 241
                },
                {
                    "SongTitle": "虞正兒 - 怎麼遇見你『你是遙不可及的寵愛，我卻像個小孩在期待。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "fbt395QeHho",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=fbt395QeHho&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=fbt395QeHho&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "5:01",
                    "second": 301
                },
                {
                    "SongTitle": "袁小葳 - 走散『過去滴滴點點 真的讓人好懷念，現在隱隱約約 還在記憶浮現。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "UnGoLpwgL1Y",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=UnGoLpwgL1Y&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=UnGoLpwgL1Y&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "4:22",
                    "second": 262
                },
                {
                    "SongTitle": "你的上好佳 - 貪得無厭『我不看破 是誰說迷離又撲朔，太多承諾 輕輕一觸就破。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "PBG1PyZN5mQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=PBG1PyZN5mQ&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=PBG1PyZN5mQ&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "3:32",
                    "second": 212
                },
                {
                    "SongTitle": "iam迪娜 - 倒數分秒『我數著遞減的分秒，你不愛我卻逃不掉。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "oeNHtcjHAtY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=oeNHtcjHAtY&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=oeNHtcjHAtY&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "3:19",
                    "second": 199
                },
                {
                    "SongTitle": "王理文 - 事到如今『關掉手機 丟掉聯繫，刪掉回憶 不留痕跡。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "Jav6Ang2FW4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Jav6Ang2FW4&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=Jav6Ang2FW4&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "3:49",
                    "second": 229
                },
                {
                    "SongTitle": "胡66 - 無愛『愛是我太寂寞難耐 所以才，選擇性想起你的不好不壞。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "0LkLjPsvYW8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=0LkLjPsvYW8&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=0LkLjPsvYW8&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "3:35",
                    "second": 215
                },
                {
                    "SongTitle": "羊羊 - 現在我『現在我早就學會你要的懂事，現在我早就成為你愛的樣子。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "qwsu88G96sA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=qwsu88G96sA&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=qwsu88G96sA&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "3:15",
                    "second": 195
                },
                {
                    "SongTitle": "程響 - 萬物可期『可惜 你不經意留下的輪廓，我卻需要用一生去描摹。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "KwBVgLcyejg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=KwBVgLcyejg&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=KwBVgLcyejg&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "3:46",
                    "second": 226
                },
                {
                    "SongTitle": "范茹 - 總有人適合『總有人適合你的我的不同性格，身處在不鬱不歡中愛著。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "x-VnlYoreEg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=x-VnlYoreEg&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=x-VnlYoreEg&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "4:04",
                    "second": 244
                },
                {
                    "SongTitle": "曲肖冰 -  誰「在你眼中我是誰 你想我代替誰」【動態歌詞】♪",
                    "SongID": "Ccr8t6-qTZo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Ccr8t6-qTZo&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=Ccr8t6-qTZo&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4Leaf Music",
                    "ArtistID": "UCAyByk4DJ9rRlRB1cs1seMQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCAyByk4DJ9rRlRB1cs1seMQ",
                    "ArtistUrl": "https://youtube.com/channel/UCAyByk4DJ9rRlRB1cs1seMQ",
                    "time": "4:39",
                    "second": 279
                },
                {
                    "SongTitle": "于冬然 - 可是我『可是我 那麼的想他 那麼的愛他，也沒辦法改變他愛她。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "yYwzWE_4RNo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=yYwzWE_4RNo&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=yYwzWE_4RNo&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "3:41",
                    "second": 221
                },
                {
                    "SongTitle": "郭正正＆Old crab - 你的眼睛像星星《動態歌詞 Lyrics》｜【原曲：Quang Hùng MasterD - Dễ Đến Dễ Đi】",
                    "SongID": "_uTLcvuAXzg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=_uTLcvuAXzg&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=_uTLcvuAXzg&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "薇真 Wei Chen",
                    "ArtistID": "UCD-_2Z0SEPqhvVedYFaSqIw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCD-_2Z0SEPqhvVedYFaSqIw",
                    "ArtistUrl": "https://youtube.com/channel/UCD-_2Z0SEPqhvVedYFaSqIw",
                    "time": "3:58",
                    "second": 238
                },
                {
                    "SongTitle": "小阿七 - 致最愛的人『走過的春秋冬夏 是你啊 都是你的影子啊，我要怎麼忘了你啊。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "RSGM7MvalSI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=RSGM7MvalSI&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=RSGM7MvalSI&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "4:01",
                    "second": 241
                },
                {
                    "SongTitle": "Joysaaaa - 深海幻境『愛遺落的空寂深邃的像海底，我沉溺在記憶像芳香幻境裡。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "Zz_mfdhgobU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Zz_mfdhgobU&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=Zz_mfdhgobU&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "3:13",
                    "second": 193
                },
                {
                    "SongTitle": "Joysaaaa - 後來你『後來我看見的背影 怎麼每一個都像你，突然消失了 只留我一個人承受。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "M4MQqhZzkMs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=M4MQqhZzkMs&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=M4MQqhZzkMs&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "3:55",
                    "second": 235
                },
                {
                    "SongTitle": "陳子晴 - 你說『如果時間能撫平傷害 請將我的心歸還，別讓我一個人 沉入深海。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "311Y0i21MAA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=311Y0i21MAA&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=311Y0i21MAA&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "4:05",
                    "second": 245
                },
                {
                    "SongTitle": "嗜好",
                    "SongID": "ieRo8uFQtrU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ieRo8uFQtrU&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=ieRo8uFQtrU&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "顏人中",
                    "ArtistID": "UCdvWnFIweL33aDdJpLxq1qg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCdvWnFIweL33aDdJpLxq1qg",
                    "ArtistUrl": "https://youtube.com/channel/UCdvWnFIweL33aDdJpLxq1qg",
                    "time": "4:52",
                    "second": 292
                },
                {
                    "SongTitle": "寂寞烟火",
                    "SongID": "cuVUv5qw5-c",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=cuVUv5qw5-c&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=cuVUv5qw5-c&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "蓝心羽",
                    "ArtistID": "UCcbQ1t6cFg7doupQCOKMNbA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCcbQ1t6cFg7doupQCOKMNbA",
                    "ArtistUrl": "https://youtube.com/channel/UCcbQ1t6cFg7doupQCOKMNbA",
                    "time": "4:21",
                    "second": 261
                },
                {
                    "SongTitle": "烏梅子醬",
                    "SongID": "IKMaaO9QtKw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=IKMaaO9QtKw&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=IKMaaO9QtKw&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "李榮浩",
                    "ArtistID": "UCLZ9hbBmb_5mEclHVY5yOBg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCLZ9hbBmb_5mEclHVY5yOBg",
                    "ArtistUrl": "https://youtube.com/channel/UCLZ9hbBmb_5mEclHVY5yOBg",
                    "time": "4:19",
                    "second": 259
                },
                {
                    "SongTitle": "就让这大雨全都落下",
                    "SongID": "hujJIBWwpaM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=hujJIBWwpaM&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=hujJIBWwpaM&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "容祖兒",
                    "ArtistID": "UCuuUXO877z7K1_c37-vWsUg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCuuUXO877z7K1_c37-vWsUg",
                    "ArtistUrl": "https://youtube.com/channel/UCuuUXO877z7K1_c37-vWsUg",
                    "time": "4:22",
                    "second": 262
                },
                {
                    "SongTitle": "途 Journey",
                    "SongID": "XRH1nR-RL_s",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=XRH1nR-RL_s&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=XRH1nR-RL_s&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "張哲瀚",
                    "ArtistID": "UCXChf-z0jATjI547232mIVw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCXChf-z0jATjI547232mIVw",
                    "ArtistUrl": "https://youtube.com/channel/UCXChf-z0jATjI547232mIVw",
                    "time": "4:01",
                    "second": 241
                },
                {
                    "SongTitle": "顏人中 - 假裝沒變過【動態歌詞】「心早已被掏空 我沒資格難過」♪",
                    "SongID": "RZ3A-ovTMA4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=RZ3A-ovTMA4&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=RZ3A-ovTMA4&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "Angelic Music World",
                    "ArtistID": "UC_ol0nA8RUpyRTleAcu8JVw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC_ol0nA8RUpyRTleAcu8JVw",
                    "ArtistUrl": "https://youtube.com/channel/UC_ol0nA8RUpyRTleAcu8JVw",
                    "time": "4:22",
                    "second": 262
                },
                {
                    "SongTitle": "菲道爾 - 人生起起落落落落落 【动态歌词】🎶我好嗎 我不好 現在需要你的一個擁抱你不在 我身邊的時候我沒了依靠🎶",
                    "SongID": "VPUqWmGaEkg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=VPUqWmGaEkg&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=VPUqWmGaEkg&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "GC MuSic",
                    "ArtistID": "UCr_KcJHNfQgBWkaGseT6rEg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCr_KcJHNfQgBWkaGseT6rEg",
                    "ArtistUrl": "https://youtube.com/channel/UCr_KcJHNfQgBWkaGseT6rEg",
                    "time": "4:18",
                    "second": 258
                },
                {
                    "SongTitle": "鄭潤澤 - 平行線『有一種傷口 不能喊痛，陪伴是僅存的擁有。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "qKRAUYHiAos",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=qKRAUYHiAos&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=qKRAUYHiAos&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "4:27",
                    "second": 267
                },
                {
                    "SongTitle": "Joysaaaa - 危險關係『你和我之間的關係 飄忽不定，隨時可能被迫抽離。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "3JONdkiKoq0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=3JONdkiKoq0&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=3JONdkiKoq0&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "3:37",
                    "second": 217
                },
                {
                    "SongTitle": "范茹 - 別問我好不好『其實我過的不好 拼了命的微笑，失眠的夜到底多難熬。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "-Lgy-BLmvtg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=-Lgy-BLmvtg&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=-Lgy-BLmvtg&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "4:05",
                    "second": 245
                },
                {
                    "SongTitle": "李飄飄 - 真的不快樂「可是媽媽 我好像沒有避風港」【動態歌詞】♪",
                    "SongID": "euSYJ_LSuzk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=euSYJ_LSuzk&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=euSYJ_LSuzk&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4Leaf Music",
                    "ArtistID": "UCAyByk4DJ9rRlRB1cs1seMQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCAyByk4DJ9rRlRB1cs1seMQ",
                    "ArtistUrl": "https://youtube.com/channel/UCAyByk4DJ9rRlRB1cs1seMQ",
                    "time": "3:32",
                    "second": 212
                },
                {
                    "SongTitle": "羊羊 - 真的不快樂「可是媽媽 我好像沒有避風港」【動態歌詞】♪",
                    "SongID": "PWDz28MOMgs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=PWDz28MOMgs&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=PWDz28MOMgs&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4Leaf Music",
                    "ArtistID": "UCAyByk4DJ9rRlRB1cs1seMQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCAyByk4DJ9rRlRB1cs1seMQ",
                    "ArtistUrl": "https://youtube.com/channel/UCAyByk4DJ9rRlRB1cs1seMQ",
                    "time": "3:37",
                    "second": 217
                },
                {
                    "SongTitle": "于冬然 - 捨不得又如何(原唱:彈棉花的小花)『我捨不得可又能如何，我明知道不會有結果。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "xm3IfVN2pJw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=xm3IfVN2pJw&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=xm3IfVN2pJw&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "3:48",
                    "second": 228
                },
                {
                    "SongTitle": "Joysaaaa - 眼淚的形容詞『愛過你是浪漫的事 卻成為我一生的刺，後來你成為了眼淚的形容詞。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "9qe_lpzIZI4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=9qe_lpzIZI4&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=9qe_lpzIZI4&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "3:48",
                    "second": 228
                },
                {
                    "SongTitle": "張葉蕾 - 藏『你始終藏在我的心間，藏在每首歌的琴鍵。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "N0IxtI2D4jQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=N0IxtI2D4jQ&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=N0IxtI2D4jQ&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "3:40",
                    "second": 220
                },
                {
                    "SongTitle": "王澤科 - 願某人『願某人你要幸福，當你有了真正的歸宿 我一定把你埋在心底不哭。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "pE6IYGiDu3w",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=pE6IYGiDu3w&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=pE6IYGiDu3w&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "4:06",
                    "second": 246
                },
                {
                    "SongTitle": "羊羊 - 忙著「我忙著愛你抽空生活，你忙著生活抽空愛我」【動態歌詞/pīn yīn gē cí】",
                    "SongID": "ngGLHHNvH-M",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ngGLHHNvH-M&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=ngGLHHNvH-M&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "WCY Music Studio",
                    "ArtistID": "UCpJSxn5cpzs4_0CMisQ-xKw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCpJSxn5cpzs4_0CMisQ-xKw",
                    "ArtistUrl": "https://youtube.com/channel/UCpJSxn5cpzs4_0CMisQ-xKw",
                    "time": "3:39",
                    "second": 219
                },
                {
                    "SongTitle": "Joysaaaa - 你不會懂『你不懂因為我愛你才要離開，你不懂最是喜歡偏偏要釋懷。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "wR6cDIk51jI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=wR6cDIk51jI&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=wR6cDIk51jI&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "3:55",
                    "second": 235
                },
                {
                    "SongTitle": "顏人中 - 嗜好【動態歌詞】「像囚禁人的監牢 我要關多久才能夠釋放」♪",
                    "SongID": "e864DX_KWNo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=e864DX_KWNo&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=e864DX_KWNo&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "Angelic Music World",
                    "ArtistID": "UC_ol0nA8RUpyRTleAcu8JVw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC_ol0nA8RUpyRTleAcu8JVw",
                    "ArtistUrl": "https://youtube.com/channel/UC_ol0nA8RUpyRTleAcu8JVw",
                    "time": "4:44",
                    "second": 284
                },
                {
                    "SongTitle": "覆予 - 等霧散去『他會去穿越風雨擁抱你，披星戴月奔向你。』【動態歌詞Lyrics】",
                    "SongID": "fJ3FdEo04LA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=fJ3FdEo04LA&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=fJ3FdEo04LA&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "3:48",
                    "second": 228
                },
                {
                    "SongTitle": "顏人中 - 晚安『迂回一句晚安，多情人卻自找難堪』【中文動態歌詞Lycris】完整版",
                    "SongID": "FcyP7sIeWaE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=FcyP7sIeWaE&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=FcyP7sIeWaE&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "Bunny 小兔 Music Channel",
                    "ArtistID": "UCFtqvt1K-TfxdP_-9YW4HKg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCFtqvt1K-TfxdP_-9YW4HKg",
                    "ArtistUrl": "https://youtube.com/channel/UCFtqvt1K-TfxdP_-9YW4HKg",
                    "time": "4:49",
                    "second": 289
                },
                {
                    "SongTitle": "虎二 Tiger Wang - 原來 Turns Out『原來我們的起點，是放開彼此走遠。』【動態歌詞Lyrics】",
                    "SongID": "Dp7qwj89e3s",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Dp7qwj89e3s&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=Dp7qwj89e3s&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "5:12",
                    "second": 312
                },
                {
                    "SongTitle": "我最親愛的 - 王韵 - 『超高无损音質』【動態歌詞Lyrics】",
                    "SongID": "KfL-_YF18Tg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=KfL-_YF18Tg&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=KfL-_YF18Tg&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "POP MusicChannel",
                    "ArtistID": "UC4XXsZW-Fi1vamPVGfDenlA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC4XXsZW-Fi1vamPVGfDenlA",
                    "ArtistUrl": "https://youtube.com/channel/UC4XXsZW-Fi1vamPVGfDenlA",
                    "time": "4:41",
                    "second": 281
                },
                {
                    "SongTitle": "星野 - 晚風告白『我遇見很多人卻只想和你慢慢周旋，完全對的感覺在 心動蔓延。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "VIRQg8d8HvM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=VIRQg8d8HvM&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=VIRQg8d8HvM&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "3:54",
                    "second": 234
                },
                {
                    "SongTitle": "仗着",
                    "SongID": "LbOAYgfEAxM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=LbOAYgfEAxM&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=LbOAYgfEAxM&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "陈壹千",
                    "ArtistID": "UCIWKHCm0JUOBrrO1x-RQ9Ng",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCIWKHCm0JUOBrrO1x-RQ9Ng",
                    "ArtistUrl": "https://youtube.com/channel/UCIWKHCm0JUOBrrO1x-RQ9Ng",
                    "time": "3:46",
                    "second": 226
                },
                {
                    "SongTitle": "陳壹千 - 仗着『你就仗著我對你 那麼愛 那麼好，所以你才面對我 那麼驕傲。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "s2CJv-wxs4k",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=s2CJv-wxs4k&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=s2CJv-wxs4k&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "3:39",
                    "second": 219
                },
                {
                    "SongTitle": "王晴 - 無人可及『你無人可及 無人可替，我眼裡都是你。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "1iBUda3i2us",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=1iBUda3i2us&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=1iBUda3i2us&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "4:51",
                    "second": 291
                },
                {
                    "SongTitle": "趙乃吉 - 各奔東西『我們結局 安安靜靜，就連心動的人都像你。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "u0XUNFylvW0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=u0XUNFylvW0&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=u0XUNFylvW0&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "4:19",
                    "second": 259
                },
                {
                    "SongTitle": "我太笨- 錘娜麗莎《是不是我太笨给不了你最渴望的安稳》【动态歌词】#我太笨 #錘娜麗莎",
                    "SongID": "9j-v2txXWjA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=9j-v2txXWjA&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=9j-v2txXWjA&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "YUELike Music Channel",
                    "ArtistID": "UCcgihA-702v-o_IH7b0SXOA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCcgihA-702v-o_IH7b0SXOA",
                    "ArtistUrl": "https://youtube.com/channel/UCcgihA-702v-o_IH7b0SXOA",
                    "time": "3:47",
                    "second": 227
                },
                {
                    "SongTitle": "Tizzy T - 100「我想要陪在你的周围，跟你爱到一百岁」(4k Video)【動態歌詞/pīn yīn gē cí】#TizzyT #100 #動態歌詞",
                    "SongID": "g3qZYZf_iFk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=g3qZYZf_iFk&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=g3qZYZf_iFk&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "WCY Music Studio",
                    "ArtistID": "UCpJSxn5cpzs4_0CMisQ-xKw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCpJSxn5cpzs4_0CMisQ-xKw",
                    "ArtistUrl": "https://youtube.com/channel/UCpJSxn5cpzs4_0CMisQ-xKw",
                    "time": "3:47",
                    "second": 227
                },
                {
                    "SongTitle": "闭文思 - 像你一样",
                    "SongID": "BZr8KRrs0Z8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=BZr8KRrs0Z8&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=BZr8KRrs0Z8&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "GPC Entertainment Channel",
                    "ArtistID": "UCR0KBVJPTE34pJABdcVjFSg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCR0KBVJPTE34pJABdcVjFSg",
                    "ArtistUrl": "https://youtube.com/channel/UCR0KBVJPTE34pJABdcVjFSg",
                    "time": "3:32",
                    "second": 212
                },
                {
                    "SongTitle": "金海心 - 愛似水仙『就不會開在你的窗前』【動態歌詞Lyrics】",
                    "SongID": "yPfcoo6uvFY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=yPfcoo6uvFY&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=yPfcoo6uvFY&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "Bomb Pop",
                    "ArtistID": "UCBhfXHb5jvYn8XK6KPc9sug",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCBhfXHb5jvYn8XK6KPc9sug",
                    "ArtistUrl": "https://youtube.com/channel/UCBhfXHb5jvYn8XK6KPc9sug",
                    "time": "4:08",
                    "second": 248
                },
                {
                    "SongTitle": "于冬然 - 怪我沒出息『多少次說要放棄我該如何決定，孤獨夜裡想念著你。』【高音質|動態歌詞Lyrics】♫",
                    "SongID": "TOzvHDs4z7U",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=TOzvHDs4z7U&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=TOzvHDs4z7U&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "4K Music Make",
                    "ArtistID": "UCiQKucVFHucBp11xTdROjlw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "ArtistUrl": "https://youtube.com/channel/UCiQKucVFHucBp11xTdROjlw",
                    "time": "3:54",
                    "second": 234
                },
                {
                    "SongTitle": "余佳運 - 九月底『每當你又想起 我們的曾經，我還在原地 等你你你你你。』【動態歌詞Lyrics】",
                    "SongID": "JtMFR5dozQY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=JtMFR5dozQY&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "SongUrl": "https://youtube.com/watch?v=JtMFR5dozQY&list=PLUD2d-pqyvT6_ztf31hx-5SsUUvY5UsQn",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "4:18",
                    "second": 258
                }
            ]
        }
    ];
    return { data };
});
