export default defineEventHandler((event) => {
    const data = [
        {
            "ListName": "Billie Eilish",
            "SongList": [
                {
                    "SongTitle": "COPYCAT",
                    "SongID": "rdKK3OMyLxs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=rdKK3OMyLxs&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=rdKK3OMyLxs&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "怪奇比莉",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "3:15",
                    "second": 195
                },
                {
                    "SongTitle": "COPYCAT",
                    "SongID": "rdKK3OMyLxs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=rdKK3OMyLxs&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=rdKK3OMyLxs&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "怪奇比莉",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "3:15",
                    "second": 195
                },
                {
                    "SongTitle": "idontwannabeyouanymore",
                    "SongID": "MDedqBwm-yI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=MDedqBwm-yI&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=MDedqBwm-yI&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "怪奇比莉",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "3:24",
                    "second": 204
                },
                {
                    "SongTitle": "my boy",
                    "SongID": "EmMZDOupR68",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=EmMZDOupR68&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=EmMZDOupR68&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "怪奇比莉",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "2:51",
                    "second": 171
                },
                {
                    "SongTitle": "watch",
                    "SongID": "V47CAl52Tdo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=V47CAl52Tdo&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=V47CAl52Tdo&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "怪奇比莉",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "2:58",
                    "second": 178
                },
                {
                    "SongTitle": "party favor",
                    "SongID": "ADZalnqEyx0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ADZalnqEyx0&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=ADZalnqEyx0&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "怪奇比莉",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "3:25",
                    "second": 205
                },
                {
                    "SongTitle": "bellyache",
                    "SongID": "Vg18eeEugOQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Vg18eeEugOQ&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=Vg18eeEugOQ&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "怪奇比莉",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "3:00",
                    "second": 180
                },
                {
                    "SongTitle": "ocean eyes",
                    "SongID": "3IUqoyTxEU8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=3IUqoyTxEU8&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=3IUqoyTxEU8&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "怪奇比莉",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "3:21",
                    "second": 201
                },
                {
                    "SongTitle": "hostage",
                    "SongID": "4B7gJMPOYWk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=4B7gJMPOYWk&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=4B7gJMPOYWk&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "怪奇比莉",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "3:50",
                    "second": 230
                },
                {
                    "SongTitle": "&burn",
                    "SongID": "z8sLTkmdPG4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=z8sLTkmdPG4&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=z8sLTkmdPG4&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "Billie Eilish",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "3:00",
                    "second": 180
                },
                {
                    "SongTitle": "!!!!!!!",
                    "SongID": "XJBUWZsT38c",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=XJBUWZsT38c&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=XJBUWZsT38c&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "怪奇比莉",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "0:14",
                    "second": 14
                },
                {
                    "SongTitle": "bad guy",
                    "SongID": "ZD6rXLXZOEI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ZD6rXLXZOEI&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=ZD6rXLXZOEI&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "怪奇比莉",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "3:15",
                    "second": 195
                },
                {
                    "SongTitle": "xanny",
                    "SongID": "GbjwfQG_N_Y",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=GbjwfQG_N_Y&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=GbjwfQG_N_Y&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "怪奇比莉",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "4:04",
                    "second": 244
                },
                {
                    "SongTitle": "you should see me in a crown",
                    "SongID": "K6xBwcQTGac",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=K6xBwcQTGac&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=K6xBwcQTGac&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "怪奇比莉",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "3:01",
                    "second": 181
                },
                {
                    "SongTitle": "all the good girls go to hell",
                    "SongID": "s_IwrqvM618",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=s_IwrqvM618&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=s_IwrqvM618&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "怪奇比莉",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "2:49",
                    "second": 169
                },
                {
                    "SongTitle": "wish you were gay",
                    "SongID": "z0_zOC20jbM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=z0_zOC20jbM&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=z0_zOC20jbM&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "怪奇比莉",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "3:42",
                    "second": 222
                },
                {
                    "SongTitle": "when the party's over",
                    "SongID": "5DcrRJI_H04",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=5DcrRJI_H04&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=5DcrRJI_H04&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "怪奇比莉",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "3:17",
                    "second": 197
                },
                {
                    "SongTitle": "8",
                    "SongID": "OZYd9JxithE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=OZYd9JxithE&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=OZYd9JxithE&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "怪奇比莉",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "2:54",
                    "second": 174
                },
                {
                    "SongTitle": "my strange addiction",
                    "SongID": "k1ATPhkVWi0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=k1ATPhkVWi0&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=k1ATPhkVWi0&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "怪奇比莉",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "3:00",
                    "second": 180
                },
                {
                    "SongTitle": "bury a friend",
                    "SongID": "YFervpMG_sM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=YFervpMG_sM&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=YFervpMG_sM&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "怪奇比莉",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "3:14",
                    "second": 194
                },
                {
                    "SongTitle": "ilomilo",
                    "SongID": "lH1F6m3slrQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=lH1F6m3slrQ&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=lH1F6m3slrQ&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "怪奇比莉",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "2:37",
                    "second": 157
                },
                {
                    "SongTitle": "listen before i go",
                    "SongID": "P4z1O3miesI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=P4z1O3miesI&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=P4z1O3miesI&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "怪奇比莉",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "4:03",
                    "second": 243
                },
                {
                    "SongTitle": "i love you",
                    "SongID": "WiinVuzh4DA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=WiinVuzh4DA&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=WiinVuzh4DA&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "怪奇比莉",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "4:52",
                    "second": 292
                },
                {
                    "SongTitle": "goodbye",
                    "SongID": "vciZvVJyNYU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=vciZvVJyNYU&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=vciZvVJyNYU&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "怪奇比莉",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "2:00",
                    "second": 120
                },
                {
                    "SongTitle": "Getting Older",
                    "SongID": "0YyEE_aO2TY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=0YyEE_aO2TY&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=0YyEE_aO2TY&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "Billie Eilish",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "4:05",
                    "second": 245
                },
                {
                    "SongTitle": "I Didn't Change My Number",
                    "SongID": "VAwGfL7Kyhk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=VAwGfL7Kyhk&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=VAwGfL7Kyhk&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "Billie Eilish",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "2:39",
                    "second": 159
                },
                {
                    "SongTitle": "Billie Bossa Nova",
                    "SongID": "4RGkfHOHH7w",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=4RGkfHOHH7w&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=4RGkfHOHH7w&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "Billie Eilish",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "3:17",
                    "second": 197
                },
                {
                    "SongTitle": "my future",
                    "SongID": "BKznMmrEXzU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=BKznMmrEXzU&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=BKznMmrEXzU&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "Billie Eilish",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "3:31",
                    "second": 211
                },
                {
                    "SongTitle": "Oxytocin",
                    "SongID": "YdCTcHnPCD0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=YdCTcHnPCD0&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=YdCTcHnPCD0&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "Billie Eilish",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "3:31",
                    "second": 211
                },
                {
                    "SongTitle": "GOLDWING",
                    "SongID": "WMtcapmjgo0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=WMtcapmjgo0&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=WMtcapmjgo0&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "Billie Eilish",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "2:32",
                    "second": 152
                },
                {
                    "SongTitle": "Lost Cause",
                    "SongID": "vRNxAzAr_-4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=vRNxAzAr_-4&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=vRNxAzAr_-4&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "Billie Eilish",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "3:33",
                    "second": 213
                },
                {
                    "SongTitle": "Halley's Comet",
                    "SongID": "gV9IVwRWvqA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=gV9IVwRWvqA&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=gV9IVwRWvqA&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "Billie Eilish",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "3:55",
                    "second": 235
                },
                {
                    "SongTitle": "Not My Responsibility",
                    "SongID": "4HfbgDLUmpk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=4HfbgDLUmpk&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=4HfbgDLUmpk&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "Billie Eilish",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "3:48",
                    "second": 228
                },
                {
                    "SongTitle": "OverHeated",
                    "SongID": "5H4apmLEEUM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=5H4apmLEEUM&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=5H4apmLEEUM&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "Billie Eilish",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "3:35",
                    "second": 215
                },
                {
                    "SongTitle": "Everybody Dies",
                    "SongID": "6iqh3QOFEjg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=6iqh3QOFEjg&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=6iqh3QOFEjg&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "Billie Eilish",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "3:27",
                    "second": 207
                },
                {
                    "SongTitle": "Your Power",
                    "SongID": "5DEPXcDysro",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=5DEPXcDysro&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=5DEPXcDysro&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "Billie Eilish",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "4:06",
                    "second": 246
                },
                {
                    "SongTitle": "NDA",
                    "SongID": "UmMFlEUflzA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=UmMFlEUflzA&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=UmMFlEUflzA&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "Billie Eilish",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "3:16",
                    "second": 196
                },
                {
                    "SongTitle": "Therefore I Am",
                    "SongID": "2NySuOGEpHk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=2NySuOGEpHk&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=2NySuOGEpHk&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "Billie Eilish",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "2:54",
                    "second": 174
                },
                {
                    "SongTitle": "Happier Than Ever",
                    "SongID": "NSTUVHsb9xw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=NSTUVHsb9xw&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=NSTUVHsb9xw&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "Billie Eilish",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "4:59",
                    "second": 299
                },
                {
                    "SongTitle": "Male Fantasy",
                    "SongID": "TsANEWfyi8E",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=TsANEWfyi8E&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "SongUrl": "https://youtube.com/watch?v=TsANEWfyi8E&list=PL3qm_8TRqiecAZ8nXfzzHo-JBwmHj4xLb",
                    "Artist": "Billie Eilish",
                    "ArtistID": "UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "ArtistUrl": "https://youtube.com/channel/UCERrDZ8oN0U_n9MphMKERcg",
                    "time": "3:15",
                    "second": 195
                }
            ]
        }
    ];
    return { data };
});
