export default defineEventHandler((event) => {
    const data = [
        {
            "ListName": "HYS專屬",
            "SongList": [
                {
                    "SongTitle": "午夜的眼淚",
                    "SongID": "UwS6urklJzA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=UwS6urklJzA&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=UwS6urklJzA&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "鹿洐人",
                    "ArtistID": "UCU9q7802h1He9C1hV0KGC1w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCU9q7802h1He9C1hV0KGC1w",
                    "ArtistUrl": "https://youtube.com/channel/UCU9q7802h1He9C1hV0KGC1w",
                    "time": "4:31",
                    "second": 271
                },
                {
                    "SongTitle": "午夜的眼淚",
                    "SongID": "UwS6urklJzA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=UwS6urklJzA&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=UwS6urklJzA&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "鹿洐人",
                    "ArtistID": "UCU9q7802h1He9C1hV0KGC1w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCU9q7802h1He9C1hV0KGC1w",
                    "ArtistUrl": "https://youtube.com/channel/UCU9q7802h1He9C1hV0KGC1w",
                    "time": "4:31",
                    "second": 271
                },
                {
                    "SongTitle": "給 被世界吞噬的你",
                    "SongID": "-eB3_SNN114",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=-eB3_SNN114&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=-eB3_SNN114&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "鹿洐人",
                    "ArtistID": "UCU9q7802h1He9C1hV0KGC1w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCU9q7802h1He9C1hV0KGC1w",
                    "ArtistUrl": "https://youtube.com/channel/UCU9q7802h1He9C1hV0KGC1w",
                    "time": "5:31",
                    "second": 331
                },
                {
                    "SongTitle": "失蹤人口",
                    "SongID": "djACkCHl3JA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=djACkCHl3JA&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=djACkCHl3JA&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "甜約翰",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "5:26",
                    "second": 326
                },
                {
                    "SongTitle": "留給你的我從未",
                    "SongID": "Q0Nn4TUXH5Y",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Q0Nn4TUXH5Y&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=Q0Nn4TUXH5Y&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "甜約翰",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "4:22",
                    "second": 262
                },
                {
                    "SongTitle": "Rain Onto the One",
                    "SongID": "3UYOS8Pcsks",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=3UYOS8Pcsks&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=3UYOS8Pcsks&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "甜約翰",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "4:17",
                    "second": 257
                },
                {
                    "SongTitle": "山海",
                    "SongID": "j2311FZWoFQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=j2311FZWoFQ&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=j2311FZWoFQ&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "草東沒有派對",
                    "ArtistID": "UC-1kIjeEOX6NkWWKX3Y1W8Q",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC-1kIjeEOX6NkWWKX3Y1W8Q",
                    "ArtistUrl": "https://youtube.com/channel/UC-1kIjeEOX6NkWWKX3Y1W8Q",
                    "time": "5:11",
                    "second": 311
                },
                {
                    "SongTitle": "醜",
                    "SongID": "we9IbnUSBu4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=we9IbnUSBu4&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=we9IbnUSBu4&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "草東沒有派對",
                    "ArtistID": "UC-1kIjeEOX6NkWWKX3Y1W8Q",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC-1kIjeEOX6NkWWKX3Y1W8Q",
                    "ArtistUrl": "https://youtube.com/channel/UC-1kIjeEOX6NkWWKX3Y1W8Q",
                    "time": "1:58",
                    "second": 118
                },
                {
                    "SongTitle": "艾瑪",
                    "SongID": "uUc_05zlRkQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=uUc_05zlRkQ&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=uUc_05zlRkQ&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "草東沒有派對",
                    "ArtistID": "UC-1kIjeEOX6NkWWKX3Y1W8Q",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC-1kIjeEOX6NkWWKX3Y1W8Q",
                    "ArtistUrl": "https://youtube.com/channel/UC-1kIjeEOX6NkWWKX3Y1W8Q",
                    "time": "3:22",
                    "second": 202
                },
                {
                    "SongTitle": "轉身之後",
                    "SongID": "dB0t01rSLGQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=dB0t01rSLGQ&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=dB0t01rSLGQ&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "畢書盡",
                    "ArtistID": "UCo6MSgaUwBLtmcfQ5EHJwLA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCo6MSgaUwBLtmcfQ5EHJwLA",
                    "ArtistUrl": "https://youtube.com/channel/UCo6MSgaUwBLtmcfQ5EHJwLA",
                    "time": "4:08",
                    "second": 248
                },
                {
                    "SongTitle": "Love More",
                    "SongID": "b1E70mAzNwY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=b1E70mAzNwY&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=b1E70mAzNwY&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "畢書盡",
                    "ArtistID": "UCo6MSgaUwBLtmcfQ5EHJwLA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCo6MSgaUwBLtmcfQ5EHJwLA",
                    "ArtistUrl": "https://youtube.com/channel/UCo6MSgaUwBLtmcfQ5EHJwLA",
                    "time": "4:05",
                    "second": 245
                },
                {
                    "SongTitle": "鹿洐人-頌song",
                    "SongID": "ZfzoQeQNVcQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ZfzoQeQNVcQ&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=ZfzoQeQNVcQ&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "盧宜良",
                    "ArtistID": "UCcLpXO-sOHsc2_kceovPhuA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCcLpXO-sOHsc2_kceovPhuA",
                    "ArtistUrl": "https://youtube.com/channel/UCcLpXO-sOHsc2_kceovPhuA",
                    "time": "4:27",
                    "second": 267
                },
                {
                    "SongTitle": "Happier",
                    "SongID": "iWZmdoY1aTE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=iWZmdoY1aTE&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=iWZmdoY1aTE&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "Ed Sheeran",
                    "ArtistID": "UClmXPfaYhXOYsNn_QUyheWQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UClmXPfaYhXOYsNn_QUyheWQ",
                    "ArtistUrl": "https://youtube.com/channel/UClmXPfaYhXOYsNn_QUyheWQ",
                    "time": "3:36",
                    "second": 216
                },
                {
                    "SongTitle": "爛笑話",
                    "SongID": "Qa8H0He1J7w",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Qa8H0He1J7w&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=Qa8H0He1J7w&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "鹿洐人",
                    "ArtistID": "UCU9q7802h1He9C1hV0KGC1w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCU9q7802h1He9C1hV0KGC1w",
                    "ArtistUrl": "https://youtube.com/channel/UCU9q7802h1He9C1hV0KGC1w",
                    "time": "5:59",
                    "second": 359
                },
                {
                    "SongTitle": "一個人",
                    "SongID": "sW_y-yt1IME",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=sW_y-yt1IME&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=sW_y-yt1IME&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "鹿洐人",
                    "ArtistID": "UCU9q7802h1He9C1hV0KGC1w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCU9q7802h1He9C1hV0KGC1w",
                    "ArtistUrl": "https://youtube.com/channel/UCU9q7802h1He9C1hV0KGC1w",
                    "time": "4:00",
                    "second": 240
                },
                {
                    "SongTitle": "positions (official video)",
                    "SongID": "tcYodQoapMg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=tcYodQoapMg&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=tcYodQoapMg&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "Ariana Grande",
                    "ArtistID": "UC0076UMUgEng8HORUw_MYHA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC0076UMUgEng8HORUw_MYHA",
                    "ArtistUrl": "https://youtube.com/channel/UC0076UMUgEng8HORUw_MYHA",
                    "time": "2:58",
                    "second": 178
                },
                {
                    "SongTitle": "大風吹",
                    "SongID": "HqmpIQ9l-uA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=HqmpIQ9l-uA&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=HqmpIQ9l-uA&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "草東沒有派對",
                    "ArtistID": "UC-1kIjeEOX6NkWWKX3Y1W8Q",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC-1kIjeEOX6NkWWKX3Y1W8Q",
                    "ArtistUrl": "https://youtube.com/channel/UC-1kIjeEOX6NkWWKX3Y1W8Q",
                    "time": "4:08",
                    "second": 248
                },
                {
                    "SongTitle": "逆時光的浪",
                    "SongID": "jbtU1rWNbmc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=jbtU1rWNbmc&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=jbtU1rWNbmc&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "畢書盡",
                    "ArtistID": "UCo6MSgaUwBLtmcfQ5EHJwLA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCo6MSgaUwBLtmcfQ5EHJwLA",
                    "ArtistUrl": "https://youtube.com/channel/UCo6MSgaUwBLtmcfQ5EHJwLA",
                    "time": "4:49",
                    "second": 289
                },
                {
                    "SongTitle": "草東沒有派對 - 爛泥",
                    "SongID": "QPY4h-nDIZ8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=QPY4h-nDIZ8&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=QPY4h-nDIZ8&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "Frank Lin",
                    "ArtistID": "UC4_g-kR030ZhzHqTquejdHg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC4_g-kR030ZhzHqTquejdHg",
                    "ArtistUrl": "https://youtube.com/channel/UC4_g-kR030ZhzHqTquejdHg",
                    "time": "2:40",
                    "second": 160
                },
                {
                    "SongTitle": "For You (Fifty Shades Freed)",
                    "SongID": "RQUuqbzQVsY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=RQUuqbzQVsY&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=RQUuqbzQVsY&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "連恩·佩恩",
                    "ArtistID": "UCEcGHupZkoAPFXXQrC2W8rA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCEcGHupZkoAPFXXQrC2W8rA",
                    "ArtistUrl": "https://youtube.com/channel/UCEcGHupZkoAPFXXQrC2W8rA",
                    "time": "4:09",
                    "second": 249
                },
                {
                    "SongTitle": "謝震廷 你的行李 歌詞",
                    "SongID": "CqrLOhoHojs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=CqrLOhoHojs&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=CqrLOhoHojs&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "Star lyric副頻道",
                    "ArtistID": "UC8reu8bU-j1QgFws7KwnXQg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC8reu8bU-j1QgFws7KwnXQg",
                    "ArtistUrl": "https://youtube.com/channel/UC8reu8bU-j1QgFws7KwnXQg",
                    "time": "4:01",
                    "second": 241
                },
                {
                    "SongTitle": "I Don't Care (Live At Abbey Road, 19th June, 2019)",
                    "SongID": "ymjNGjuBCTo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ymjNGjuBCTo&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=ymjNGjuBCTo&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "Ed Sheeran",
                    "ArtistID": "UClmXPfaYhXOYsNn_QUyheWQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UClmXPfaYhXOYsNn_QUyheWQ",
                    "ArtistUrl": "https://youtube.com/channel/UClmXPfaYhXOYsNn_QUyheWQ",
                    "time": "5:30",
                    "second": 330
                },
                {
                    "SongTitle": "法蘭西多士",
                    "SongID": "Chua3NCdFGA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Chua3NCdFGA&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=Chua3NCdFGA&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "告五人",
                    "ArtistID": "UC2lbjBep5vvd-Spo0oGn97g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC2lbjBep5vvd-Spo0oGn97g",
                    "ArtistUrl": "https://youtube.com/channel/UC2lbjBep5vvd-Spo0oGn97g",
                    "time": "4:36",
                    "second": 276
                },
                {
                    "SongTitle": "宇宙人 - 那你呢",
                    "SongID": "ZLNDoylR40A",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ZLNDoylR40A&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=ZLNDoylR40A&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "My little mix",
                    "ArtistID": "UCos_XrPEWgv8IfOiZ_Uo4AA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCos_XrPEWgv8IfOiZ_Uo4AA",
                    "ArtistUrl": "https://youtube.com/channel/UCos_XrPEWgv8IfOiZ_Uo4AA",
                    "time": "4:19",
                    "second": 259
                },
                {
                    "SongTitle": "Let Me Go",
                    "SongID": "FKq1zHu5uGk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=FKq1zHu5uGk&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=FKq1zHu5uGk&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "宇宙人",
                    "ArtistID": "UCWSyWCpk81aAcHlkcADHPeg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCWSyWCpk81aAcHlkcADHPeg",
                    "ArtistUrl": "https://youtube.com/channel/UCWSyWCpk81aAcHlkcADHPeg",
                    "time": "3:21",
                    "second": 201
                },
                {
                    "SongTitle": "WEWE",
                    "SongID": "O9Jn1hN3W40",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=O9Jn1hN3W40&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=O9Jn1hN3W40&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "告五人",
                    "ArtistID": "UC2lbjBep5vvd-Spo0oGn97g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC2lbjBep5vvd-Spo0oGn97g",
                    "ArtistUrl": "https://youtube.com/channel/UC2lbjBep5vvd-Spo0oGn97g",
                    "time": "3:49",
                    "second": 229
                },
                {
                    "SongTitle": "Nothing's the Same",
                    "SongID": "mG3mfZp6llo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=mG3mfZp6llo&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=mG3mfZp6llo&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "傑瑞米·祖克",
                    "ArtistID": "UC4FxRR1ZZcap_CY6fTQUU3g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC4FxRR1ZZcap_CY6fTQUU3g",
                    "ArtistUrl": "https://youtube.com/channel/UC4FxRR1ZZcap_CY6fTQUU3g",
                    "time": "3:31",
                    "second": 211
                },
                {
                    "SongTitle": "this is how you fall in love (Official Music Video)",
                    "SongID": "6qkgVgjN188",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=6qkgVgjN188&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=6qkgVgjN188&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "傑瑞米·祖克",
                    "ArtistID": "UC4FxRR1ZZcap_CY6fTQUU3g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC4FxRR1ZZcap_CY6fTQUU3g",
                    "ArtistUrl": "https://youtube.com/channel/UC4FxRR1ZZcap_CY6fTQUU3g",
                    "time": "2:58",
                    "second": 178
                },
                {
                    "SongTitle": "Jeremy Zucker & Chelsea Cutler - Better Off (Lyric Video)",
                    "SongID": "5tkG8i5oi4s",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=5tkG8i5oi4s&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=5tkG8i5oi4s&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "Aminium Music",
                    "ArtistID": "UCGY2E83PapX47mviakM_IpQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCGY2E83PapX47mviakM_IpQ",
                    "ArtistUrl": "https://youtube.com/channel/UCGY2E83PapX47mviakM_IpQ",
                    "time": "3:15",
                    "second": 195
                },
                {
                    "SongTitle": "Summer Love (Official Video)",
                    "SongID": "bDZc3hiYTi0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=bDZc3hiYTi0&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=bDZc3hiYTi0&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "Austin Mahone",
                    "ArtistID": "UC3yw89JHrCHcJ-CNRrx_1UQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC3yw89JHrCHcJ-CNRrx_1UQ",
                    "ArtistUrl": "https://youtube.com/channel/UC3yw89JHrCHcJ-CNRrx_1UQ",
                    "time": "2:35",
                    "second": 155
                },
                {
                    "SongTitle": "always, i'll care (Lyric Video)",
                    "SongID": "N6SQ9QoSjCI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=N6SQ9QoSjCI&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=N6SQ9QoSjCI&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "Jeremy Zucker",
                    "ArtistID": "UC4FxRR1ZZcap_CY6fTQUU3g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC4FxRR1ZZcap_CY6fTQUU3g",
                    "ArtistUrl": "https://youtube.com/channel/UC4FxRR1ZZcap_CY6fTQUU3g",
                    "time": "2:28",
                    "second": 148
                },
                {
                    "SongTitle": "告五人 Accusefive  與海無關 Beyond The Sea   1hour",
                    "SongID": "nmFKTzJ4ZUY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=nmFKTzJ4ZUY&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=nmFKTzJ4ZUY&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "Endure for 1 hour",
                    "ArtistID": "UCe5mxZXGGRf-egdbTFcvazw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCe5mxZXGGRf-egdbTFcvazw",
                    "ArtistUrl": "https://youtube.com/channel/UCe5mxZXGGRf-egdbTFcvazw",
                    "time": "1:02:08",
                    "second": 62
                },
                {
                    "SongTitle": "你以為",
                    "SongID": "_9Pwge4RIlg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=_9Pwge4RIlg&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=_9Pwge4RIlg&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "宇宙人",
                    "ArtistID": "UCWSyWCpk81aAcHlkcADHPeg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCWSyWCpk81aAcHlkcADHPeg",
                    "ArtistUrl": "https://youtube.com/channel/UCWSyWCpk81aAcHlkcADHPeg",
                    "time": "4:08",
                    "second": 248
                },
                {
                    "SongTitle": "你醜得像是髒話",
                    "SongID": "L1cDgzaKv7g",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=L1cDgzaKv7g&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=L1cDgzaKv7g&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "李友廷",
                    "ArtistID": "UCCOvbhRMeLjqKdwtQccRvkw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCCOvbhRMeLjqKdwtQccRvkw",
                    "ArtistUrl": "https://youtube.com/channel/UCCOvbhRMeLjqKdwtQccRvkw",
                    "time": "4:33",
                    "second": 273
                },
                {
                    "SongTitle": "鄧紫棋 別勉強 歌詞(ft. 周興哲)",
                    "SongID": "O3vlMvP1wfM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=O3vlMvP1wfM&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=O3vlMvP1wfM&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "i3L",
                    "ArtistID": "UCCxoh8WbAeTfHHz6hVq9oUg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCCxoh8WbAeTfHHz6hVq9oUg",
                    "ArtistUrl": "https://youtube.com/channel/UCCxoh8WbAeTfHHz6hVq9oUg",
                    "time": "4:23",
                    "second": 263
                },
                {
                    "SongTitle": "誰",
                    "SongID": "vaWmoDYEJjc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=vaWmoDYEJjc&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=vaWmoDYEJjc&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "李友廷",
                    "ArtistID": "UCCOvbhRMeLjqKdwtQccRvkw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCCOvbhRMeLjqKdwtQccRvkw",
                    "ArtistUrl": "https://youtube.com/channel/UCCOvbhRMeLjqKdwtQccRvkw",
                    "time": "5:13",
                    "second": 313
                },
                {
                    "SongTitle": "如果我們還在一起",
                    "SongID": "opUf-DQvGUI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=opUf-DQvGUI&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=opUf-DQvGUI&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "宇宙人",
                    "ArtistID": "UCWSyWCpk81aAcHlkcADHPeg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCWSyWCpk81aAcHlkcADHPeg",
                    "ArtistUrl": "https://youtube.com/channel/UCWSyWCpk81aAcHlkcADHPeg",
                    "time": "8:21",
                    "second": 501
                },
                {
                    "SongTitle": "comethru (Official Video)",
                    "SongID": "jO2viLEW-1A",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=jO2viLEW-1A&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=jO2viLEW-1A&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "Jeremy Zucker",
                    "ArtistID": "UC4FxRR1ZZcap_CY6fTQUU3g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC4FxRR1ZZcap_CY6fTQUU3g",
                    "ArtistUrl": "https://youtube.com/channel/UC4FxRR1ZZcap_CY6fTQUU3g",
                    "time": "3:01",
                    "second": 181
                },
                {
                    "SongTitle": "Your Love Song",
                    "SongID": "uEq-5sm3i64",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=uEq-5sm3i64&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=uEq-5sm3i64&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "呂建中",
                    "ArtistID": "UCDS0OcKRmAOKy4IuetXieEg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCDS0OcKRmAOKy4IuetXieEg",
                    "ArtistUrl": "https://youtube.com/channel/UCDS0OcKRmAOKy4IuetXieEg",
                    "time": "4:43",
                    "second": 283
                },
                {
                    "SongTitle": "Take Me On",
                    "SongID": "SW9fCIDhJps",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=SW9fCIDhJps&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=SW9fCIDhJps&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "SAya",
                    "ArtistID": "UC2EWZjth4wwP11CUf0DOwTw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC2EWZjth4wwP11CUf0DOwTw",
                    "ArtistUrl": "https://youtube.com/channel/UC2EWZjth4wwP11CUf0DOwTw",
                    "time": "3:43",
                    "second": 223
                },
                {
                    "SongTitle": "Okinawa",
                    "SongID": "KzHOPckFmwc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=KzHOPckFmwc&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=KzHOPckFmwc&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "92914",
                    "ArtistID": "UCsywq73qRVQY0pBqEK6_2RA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCsywq73qRVQY0pBqEK6_2RA",
                    "ArtistUrl": "https://youtube.com/channel/UCsywq73qRVQY0pBqEK6_2RA",
                    "time": "5:49",
                    "second": 349
                },
                {
                    "SongTitle": "NIve ~ How Do I [Lyric]",
                    "SongID": "gK-iPoK5NnY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=gK-iPoK5NnY&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=gK-iPoK5NnY&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "DWLyrics_",
                    "ArtistID": "UC3m9L1cJc6RDH3MHHHGj1kQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC3m9L1cJc6RDH3MHHHGj1kQ",
                    "ArtistUrl": "https://youtube.com/channel/UC3m9L1cJc6RDH3MHHHGj1kQ",
                    "time": "3:38",
                    "second": 218
                },
                {
                    "SongTitle": "Dancing With Your Ghost (Lyric Video)",
                    "SongID": "Qzc_aX8c8g4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Qzc_aX8c8g4&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=Qzc_aX8c8g4&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "Sasha Alex Sloan",
                    "ArtistID": "UCklQuH51vyXV_xBhDKlJvEQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCklQuH51vyXV_xBhDKlJvEQ",
                    "ArtistUrl": "https://youtube.com/channel/UCklQuH51vyXV_xBhDKlJvEQ",
                    "time": "3:20",
                    "second": 200
                },
                {
                    "SongTitle": "周興哲  🎵✨ 終於了解自由 ✨ 現場版 比MV好聽 CCTV “TOP排行榜”",
                    "SongID": "CyzymyiT5vE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=CyzymyiT5vE&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=CyzymyiT5vE&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "TW QQ 太有才",
                    "ArtistID": "UCghbud6WQm1LuvkrMznf4yw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCghbud6WQm1LuvkrMznf4yw",
                    "ArtistUrl": "https://youtube.com/channel/UCghbud6WQm1LuvkrMznf4yw",
                    "time": "5:14",
                    "second": 314
                },
                {
                    "SongTitle": "220306 理想混蛋 _ 平衡木 [2022春浪音樂節・山線]",
                    "SongID": "O_ojqx0ige4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=O_ojqx0ige4&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=O_ojqx0ige4&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "XU3M4WU6",
                    "ArtistID": "UCDbtzuGg2yQ1hpw46j9D92Q",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCDbtzuGg2yQ1hpw46j9D92Q",
                    "ArtistUrl": "https://youtube.com/channel/UCDbtzuGg2yQ1hpw46j9D92Q",
                    "time": "5:04",
                    "second": 304
                },
                {
                    "SongTitle": "Starving (合作演出：捷德)",
                    "SongID": "xwjwCFZpdns",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=xwjwCFZpdns&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=xwjwCFZpdns&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "海莉·史坦菲德",
                    "ArtistID": "UCBNeAoPycNhoRuS01B9Kf5g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCBNeAoPycNhoRuS01B9Kf5g",
                    "ArtistUrl": "https://youtube.com/channel/UCBNeAoPycNhoRuS01B9Kf5g",
                    "time": "3:05",
                    "second": 185
                },
                {
                    "SongTitle": "Rock Bottom (合作演出：DNCE)",
                    "SongID": "liwCttfeJ7E",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=liwCttfeJ7E&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=liwCttfeJ7E&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "海莉·史坦菲德",
                    "ArtistID": "UCBNeAoPycNhoRuS01B9Kf5g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCBNeAoPycNhoRuS01B9Kf5g",
                    "ArtistUrl": "https://youtube.com/channel/UCBNeAoPycNhoRuS01B9Kf5g",
                    "time": "3:38",
                    "second": 218
                },
                {
                    "SongTitle": "I Love You's (Official Video)",
                    "SongID": "afRFR2UNYzI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=afRFR2UNYzI&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=afRFR2UNYzI&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "Hailee Steinfeld",
                    "ArtistID": "UCBNeAoPycNhoRuS01B9Kf5g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCBNeAoPycNhoRuS01B9Kf5g",
                    "ArtistUrl": "https://youtube.com/channel/UCBNeAoPycNhoRuS01B9Kf5g",
                    "time": "3:47",
                    "second": 227
                },
                {
                    "SongTitle": "我睡不著(I Can't Sleep)",
                    "SongID": "m6yOdFkXun4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=m6yOdFkXun4&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=m6yOdFkXun4&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "守夜人",
                    "ArtistID": "UCNxWMqbuXz0ay8OHljSe_Iw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCNxWMqbuXz0ay8OHljSe_Iw",
                    "ArtistUrl": "https://youtube.com/channel/UCNxWMqbuXz0ay8OHljSe_Iw",
                    "time": "4:04",
                    "second": 244
                },
                {
                    "SongTitle": "Dear",
                    "SongID": "eOxmFRTBgao",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=eOxmFRTBgao&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=eOxmFRTBgao&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "甜約翰",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "4:24",
                    "second": 264
                },
                {
                    "SongTitle": "至少我還記得 (天堂的微笑插曲)",
                    "SongID": "jIzOIsQWMfg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=jIzOIsQWMfg&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=jIzOIsQWMfg&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "周興哲",
                    "ArtistID": "UCawsPaLRTeYnWvthH8pepBw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCawsPaLRTeYnWvthH8pepBw",
                    "ArtistUrl": "https://youtube.com/channel/UCawsPaLRTeYnWvthH8pepBw",
                    "time": "5:04",
                    "second": 304
                },
                {
                    "SongTitle": "Say You Won't Let Go",
                    "SongID": "0yW7w8F2TVA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=0yW7w8F2TVA&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=0yW7w8F2TVA&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "James Arthur",
                    "ArtistID": "UCNAbUat5xDtp6FeBphe2V_Q",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCNAbUat5xDtp6FeBphe2V_Q",
                    "ArtistUrl": "https://youtube.com/channel/UCNAbUat5xDtp6FeBphe2V_Q",
                    "time": "3:31",
                    "second": 211
                },
                {
                    "SongTitle": "King of Comedy",
                    "SongID": "ijLLmE_sFkY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ijLLmE_sFkY&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=ijLLmE_sFkY&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "李榮浩",
                    "ArtistID": "UCLZ9hbBmb_5mEclHVY5yOBg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCLZ9hbBmb_5mEclHVY5yOBg",
                    "ArtistUrl": "https://youtube.com/channel/UCLZ9hbBmb_5mEclHVY5yOBg",
                    "time": "4:22",
                    "second": 262
                },
                {
                    "SongTitle": "Blank Page",
                    "SongID": "j2UGBA7CSY4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=j2UGBA7CSY4&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=j2UGBA7CSY4&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "甜約翰",
                    "ArtistID": "UC7xn0mpbaticwKL02M63oNA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "ArtistUrl": "https://youtube.com/channel/UC7xn0mpbaticwKL02M63oNA",
                    "time": "4:11",
                    "second": 251
                },
                {
                    "SongTitle": "Eric周興哲【 離開你以後 Leaving You 】「電影 你的婚禮 插曲」Music Lyrics",
                    "SongID": "SI-ipYcgvgE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=SI-ipYcgvgE&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=SI-ipYcgvgE&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "昭昭不昭 Music Lyrics",
                    "ArtistID": "UCu8MWZyxsobkjTe-AhML5Ew",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCu8MWZyxsobkjTe-AhML5Ew",
                    "ArtistUrl": "https://youtube.com/channel/UCu8MWZyxsobkjTe-AhML5Ew",
                    "time": "5:10",
                    "second": 310
                },
                {
                    "SongTitle": "John Mayer - Slow Dancing In A Burning Room [HD]",
                    "SongID": "ncijv1WCnVk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ncijv1WCnVk&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=ncijv1WCnVk&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "aDOCTORbutWHO",
                    "ArtistID": "UCEWBO6O4DQQPS32iWv7ew0Q",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCEWBO6O4DQQPS32iWv7ew0Q",
                    "ArtistUrl": "https://youtube.com/channel/UCEWBO6O4DQQPS32iWv7ew0Q",
                    "time": "6:20",
                    "second": 380
                },
                {
                    "SongTitle": "Jo Jung Suk (조정석) - ALOHA [아로하] Lyrics/가사 [Han|Rom|Eng] 슬기로운 의사생활 OST Part 3 / Hospital Playlist OST",
                    "SongID": "LIhFZ3zmRKg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=LIhFZ3zmRKg&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=LIhFZ3zmRKg&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "AlphaSubs",
                    "ArtistID": "UCDkKuGZovR6UUYkUgtW0FlQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCDkKuGZovR6UUYkUgtW0FlQ",
                    "ArtistUrl": "https://youtube.com/channel/UCDkKuGZovR6UUYkUgtW0FlQ",
                    "time": "4:11",
                    "second": 251
                },
                {
                    "SongTitle": "The Weeknd & Ariana Grande – Save Your Tears (Live on The 202...",
                    "SongID": "s37x2VSZrLw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=s37x2VSZrLw&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=s37x2VSZrLw&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "雅瑞安娜·格蘭德",
                    "ArtistID": "UC0076UMUgEng8HORUw_MYHA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC0076UMUgEng8HORUw_MYHA",
                    "ArtistUrl": "https://youtube.com/channel/UC0076UMUgEng8HORUw_MYHA",
                    "time": "3:00",
                    "second": 180
                },
                {
                    "SongTitle": "HEIZE (헤이즈) - 'HAPPEN' [헤픈 우연] Color Coded Lyrics/가사 [Han|Rom|Eng]",
                    "SongID": "RyJnp80LZ7c",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=RyJnp80LZ7c&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=RyJnp80LZ7c&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "AlphaSubs",
                    "ArtistID": "UCDkKuGZovR6UUYkUgtW0FlQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCDkKuGZovR6UUYkUgtW0FlQ",
                    "ArtistUrl": "https://youtube.com/channel/UCDkKuGZovR6UUYkUgtW0FlQ",
                    "time": "3:57",
                    "second": 237
                },
                {
                    "SongTitle": "Payphone (合作演出：Wiz Khalifa)",
                    "SongID": "KRaWnd3LJfs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=KRaWnd3LJfs&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=KRaWnd3LJfs&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "Maroon 5",
                    "ArtistID": "UCdFe4KkWwZ_twpo-UECR-Nw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCdFe4KkWwZ_twpo-UECR-Nw",
                    "ArtistUrl": "https://youtube.com/channel/UCdFe4KkWwZ_twpo-UECR-Nw",
                    "time": "4:40",
                    "second": 280
                },
                {
                    "SongTitle": "麋先生 - 麋途 | 樂人Session",
                    "SongID": "QuJSy5N7GHs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=QuJSy5N7GHs&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=QuJSy5N7GHs&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "樂人TV | 華語音樂娛樂影音平台",
                    "ArtistID": "UCBBxttXO0g22qWeS2Hwk82A",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCBBxttXO0g22qWeS2Hwk82A",
                    "ArtistUrl": "https://youtube.com/channel/UCBBxttXO0g22qWeS2Hwk82A",
                    "time": "5:13",
                    "second": 313
                },
                {
                    "SongTitle": "Capital Letters",
                    "SongID": "pj6k-EFxqAI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=pj6k-EFxqAI&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=pj6k-EFxqAI&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "BloodPop",
                    "ArtistID": "UCLpKgsIABP-FwCmTR5JxM2Q",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCLpKgsIABP-FwCmTR5JxM2Q",
                    "ArtistUrl": "https://youtube.com/channel/UCLpKgsIABP-FwCmTR5JxM2Q",
                    "time": "3:51",
                    "second": 231
                },
                {
                    "SongTitle": "Photograph",
                    "SongID": "nSDgHBxUbVQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=nSDgHBxUbVQ&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=nSDgHBxUbVQ&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "Ed Sheeran",
                    "ArtistID": "UClmXPfaYhXOYsNn_QUyheWQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UClmXPfaYhXOYsNn_QUyheWQ",
                    "ArtistUrl": "https://youtube.com/channel/UClmXPfaYhXOYsNn_QUyheWQ",
                    "time": "4:35",
                    "second": 275
                },
                {
                    "SongTitle": "想自由 林宥嘉 (歌词版)",
                    "SongID": "vm_ZnRmQeyE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=vm_ZnRmQeyE&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=vm_ZnRmQeyE&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "GM Lyric",
                    "ArtistID": "UC8wXsgv4k9fGAo8LwE-KwPQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC8wXsgv4k9fGAo8LwE-KwPQ",
                    "ArtistUrl": "https://youtube.com/channel/UC8wXsgv4k9fGAo8LwE-KwPQ",
                    "time": "4:43",
                    "second": 283
                },
                {
                    "SongTitle": "Celebrity",
                    "SongID": "0-q1KafFCLU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=0-q1KafFCLU&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=0-q1KafFCLU&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "IU",
                    "ArtistID": "UCTUR0sVEkD8T5MlSHqgaI_Q",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCTUR0sVEkD8T5MlSHqgaI_Q",
                    "ArtistUrl": "https://youtube.com/channel/UCTUR0sVEkD8T5MlSHqgaI_Q",
                    "time": "3:19",
                    "second": 199
                },
                {
                    "SongTitle": "11:11",
                    "SongID": "ulr0muQKjk0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ulr0muQKjk0&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=ulr0muQKjk0&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "TAEYEON",
                    "ArtistID": "UCwzCuKxyMY_sT7hr1E8G1XA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCwzCuKxyMY_sT7hr1E8G1XA",
                    "ArtistUrl": "https://youtube.com/channel/UCwzCuKxyMY_sT7hr1E8G1XA",
                    "time": "3:51",
                    "second": 231
                },
                {
                    "SongTitle": "Gone",
                    "SongID": "K9_VFxzCuQ0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=K9_VFxzCuQ0&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=K9_VFxzCuQ0&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "ROSÉ",
                    "ArtistID": "UCbpXC82cTLngSiZrysAaE-w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCbpXC82cTLngSiZrysAaE-w",
                    "ArtistUrl": "https://youtube.com/channel/UCbpXC82cTLngSiZrysAaE-w",
                    "time": "3:41",
                    "second": 221
                },
                {
                    "SongTitle": "On The Ground",
                    "SongID": "CKZvWhCqx1s",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=CKZvWhCqx1s&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=CKZvWhCqx1s&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "ROSÉ",
                    "ArtistID": "UCbpXC82cTLngSiZrysAaE-w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCbpXC82cTLngSiZrysAaE-w",
                    "ArtistUrl": "https://youtube.com/channel/UCbpXC82cTLngSiZrysAaE-w",
                    "time": "3:09",
                    "second": 189
                },
                {
                    "SongTitle": "嗜愛動物",
                    "SongID": "4JNb4fiT1VA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=4JNb4fiT1VA&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=4JNb4fiT1VA&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "麋先生",
                    "ArtistID": "UC8-28YYfF3CszynLHSn9Dig",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC8-28YYfF3CszynLHSn9Dig",
                    "ArtistUrl": "https://youtube.com/channel/UC8-28YYfF3CszynLHSn9Dig",
                    "time": "4:45",
                    "second": 285
                },
                {
                    "SongTitle": "Chasing Fire",
                    "SongID": "o-BODsf2T68",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=o-BODsf2T68&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=o-BODsf2T68&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "Lauv",
                    "ArtistID": "UCWjoDY2SXJ5dvcdunWI6mjQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCWjoDY2SXJ5dvcdunWI6mjQ",
                    "ArtistUrl": "https://youtube.com/channel/UCWjoDY2SXJ5dvcdunWI6mjQ",
                    "time": "3:26",
                    "second": 206
                },
                {
                    "SongTitle": "STAY (Official Video)",
                    "SongID": "kTJczUoc26U",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=kTJczUoc26U&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=kTJczUoc26U&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "小賈斯汀",
                    "ArtistID": "UCGvj8kfUV5Q6lzECIrGY19g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCGvj8kfUV5Q6lzECIrGY19g",
                    "ArtistUrl": "https://youtube.com/channel/UCGvj8kfUV5Q6lzECIrGY19g",
                    "time": "2:38",
                    "second": 158
                },
                {
                    "SongTitle": "Epik High(에픽하이) - Rain Song(비 오는 날 듣기 좋은 노래) + Love Love Love (Sketchbook) | KBS WORLD TV 211130",
                    "SongID": "dgU2N-iM6aA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=dgU2N-iM6aA&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=dgU2N-iM6aA&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "KBS WORLD TV",
                    "ArtistID": "UC5BMQOsAB8hKUyHu9KI6yig",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC5BMQOsAB8hKUyHu9KI6yig",
                    "ArtistUrl": "https://youtube.com/channel/UC5BMQOsAB8hKUyHu9KI6yig",
                    "time": "4:19",
                    "second": 259
                },
                {
                    "SongTitle": "長途夜車",
                    "SongID": "c9PEYJdwdwI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=c9PEYJdwdwI&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=c9PEYJdwdwI&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "滅火器樂團",
                    "ArtistID": "UCcny0_3Z2DtcCEYayEcgtPg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCcny0_3Z2DtcCEYayEcgtPg",
                    "ArtistUrl": "https://youtube.com/channel/UCcny0_3Z2DtcCEYayEcgtPg",
                    "time": "3:07",
                    "second": 187
                },
                {
                    "SongTitle": "The A Team",
                    "SongID": "UAWcs5H-qgQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=UAWcs5H-qgQ&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=UAWcs5H-qgQ&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "Ed Sheeran",
                    "ArtistID": "UClmXPfaYhXOYsNn_QUyheWQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UClmXPfaYhXOYsNn_QUyheWQ",
                    "ArtistUrl": "https://youtube.com/channel/UClmXPfaYhXOYsNn_QUyheWQ",
                    "time": "4:50",
                    "second": 290
                },
                {
                    "SongTitle": "PL(피엘) - ICELAND (아이스랜드) / 가사(Lyrics)",
                    "SongID": "2cRYiIxAVO4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=2cRYiIxAVO4&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=2cRYiIxAVO4&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "MPS My Personal Space",
                    "ArtistID": "UCfm5pbkoSfLTKNbYSPqGKIA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCfm5pbkoSfLTKNbYSPqGKIA",
                    "ArtistUrl": "https://youtube.com/channel/UCfm5pbkoSfLTKNbYSPqGKIA",
                    "time": "3:12",
                    "second": 192
                },
                {
                    "SongTitle": "Auburn (HEADACHE. version)",
                    "SongID": "w5JJuNtY0WA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=w5JJuNtY0WA&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=w5JJuNtY0WA&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "Damons year",
                    "ArtistID": "UCH-aM6ae8RUTNtNGwrKI3Fg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCH-aM6ae8RUTNtNGwrKI3Fg",
                    "ArtistUrl": "https://youtube.com/channel/UCH-aM6ae8RUTNtNGwrKI3Fg",
                    "time": "3:05",
                    "second": 185
                },
                {
                    "SongTitle": "I want to be a pillow",
                    "SongID": "MX35zeRKJsE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=MX35zeRKJsE&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=MX35zeRKJsE&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "J_ust",
                    "ArtistID": "UC3OQ1sioUfgQ_8XYGiKQb1A",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC3OQ1sioUfgQ_8XYGiKQb1A",
                    "ArtistUrl": "https://youtube.com/channel/UC3OQ1sioUfgQ_8XYGiKQb1A",
                    "time": "3:44",
                    "second": 224
                },
                {
                    "SongTitle": "ONEWE(원위) - 'Veronica (베로니가의 섬)' Lyrics (Color Coded Han|Rom|Eng)",
                    "SongID": "ouY0GmTv1hc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ouY0GmTv1hc&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=ouY0GmTv1hc&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "Kpop Lyrics",
                    "ArtistID": "UCYVhMojMrMvvarE2bCazqqg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCYVhMojMrMvvarE2bCazqqg",
                    "ArtistUrl": "https://youtube.com/channel/UCYVhMojMrMvvarE2bCazqqg",
                    "time": "3:20",
                    "second": 200
                },
                {
                    "SongTitle": "[I'm LIVE] JUNG Seung-hwan (정승환) & Day & Night",
                    "SongID": "CfcZdRyDALM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=CfcZdRyDALM&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=CfcZdRyDALM&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "I'm LIVE | 아임라이브",
                    "ArtistID": "UC82dHUwrlcpa34I2PmyMYQA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC82dHUwrlcpa34I2PmyMYQA",
                    "ArtistUrl": "https://youtube.com/channel/UC82dHUwrlcpa34I2PmyMYQA",
                    "time": "4:16",
                    "second": 256
                },
                {
                    "SongTitle": "I.F.L.Y.",
                    "SongID": "Xhh3_-JRnDc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Xhh3_-JRnDc&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=Xhh3_-JRnDc&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "巴濟",
                    "ArtistID": "UCoBD_yd06t7kBn1wLGH7nzg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCoBD_yd06t7kBn1wLGH7nzg",
                    "ArtistUrl": "https://youtube.com/channel/UCoBD_yd06t7kBn1wLGH7nzg",
                    "time": "2:47",
                    "second": 167
                },
                {
                    "SongTitle": "Bazzi - Mine [Official Music Video]",
                    "SongID": "Gc71AmT_b2k",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Gc71AmT_b2k&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=Gc71AmT_b2k&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "巴濟",
                    "ArtistID": "UCoBD_yd06t7kBn1wLGH7nzg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCoBD_yd06t7kBn1wLGH7nzg",
                    "ArtistUrl": "https://youtube.com/channel/UCoBD_yd06t7kBn1wLGH7nzg",
                    "time": "2:11",
                    "second": 131
                },
                {
                    "SongTitle": "Friday (合作演出：Jang Yi-jeong of History)",
                    "SongID": "EiVmQZwJhsA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=EiVmQZwJhsA&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=EiVmQZwJhsA&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "IU",
                    "ArtistID": "UCTUR0sVEkD8T5MlSHqgaI_Q",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCTUR0sVEkD8T5MlSHqgaI_Q",
                    "ArtistUrl": "https://youtube.com/channel/UCTUR0sVEkD8T5MlSHqgaI_Q",
                    "time": "3:52",
                    "second": 232
                },
                {
                    "SongTitle": "[JOY RICH] [新歌] 孫盛希 - 恆溫(台劇巷弄裡的那家書店插曲)(完整發行版)",
                    "SongID": "rKwazRQLwo0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=rKwazRQLwo0&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=rKwazRQLwo0&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "JOY RICH",
                    "ArtistID": "UC_B1qG8sCDKGtpTeqZonlCg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC_B1qG8sCDKGtpTeqZonlCg",
                    "ArtistUrl": "https://youtube.com/channel/UC_B1qG8sCDKGtpTeqZonlCg",
                    "time": "4:21",
                    "second": 261
                },
                {
                    "SongTitle": "STAY",
                    "SongID": "FzVR_fymZw4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=FzVR_fymZw4&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=FzVR_fymZw4&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "BLACKPINK",
                    "ArtistID": "UCkbbMCA40i18i7UdjayMPAg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCkbbMCA40i18i7UdjayMPAg",
                    "ArtistUrl": "https://youtube.com/channel/UCkbbMCA40i18i7UdjayMPAg",
                    "time": "4:01",
                    "second": 241
                },
                {
                    "SongTitle": "Astronaut In The Ocean",
                    "SongID": "MEg-oqI9qmw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=MEg-oqI9qmw&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=MEg-oqI9qmw&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "Masked Wolf",
                    "ArtistID": "UCeYiAaXw-aauILPI-jSVi8g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCeYiAaXw-aauILPI-jSVi8g",
                    "ArtistUrl": "https://youtube.com/channel/UCeYiAaXw-aauILPI-jSVi8g",
                    "time": "2:33",
                    "second": 153
                },
                {
                    "SongTitle": "我還想念你",
                    "SongID": "8Wnx0yFpeU8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=8Wnx0yFpeU8&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=8Wnx0yFpeU8&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "畢書盡",
                    "ArtistID": "UCo6MSgaUwBLtmcfQ5EHJwLA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCo6MSgaUwBLtmcfQ5EHJwLA",
                    "ArtistUrl": "https://youtube.com/channel/UCo6MSgaUwBLtmcfQ5EHJwLA",
                    "time": "4:28",
                    "second": 268
                },
                {
                    "SongTitle": "蔡依林 Jolin Tsai《如果我沒有傷口 Vulnerability》Lyric Video",
                    "SongID": "K0W_dKx5ZTs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=K0W_dKx5ZTs&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=K0W_dKx5ZTs&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "wxi zhxne",
                    "ArtistID": "UCD-sXc4VkfeY1UhHnnm3N1A",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCD-sXc4VkfeY1UhHnnm3N1A",
                    "ArtistUrl": "https://youtube.com/channel/UCD-sXc4VkfeY1UhHnnm3N1A",
                    "time": "5:04",
                    "second": 304
                },
                {
                    "SongTitle": "Tank - 如果我變成回憶【歌詞】",
                    "SongID": "zgP_WTBD5oc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=zgP_WTBD5oc&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=zgP_WTBD5oc&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "Yuna Jiang",
                    "ArtistID": "UCAW2scxfdEMwVRAOul0D4zw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCAW2scxfdEMwVRAOul0D4zw",
                    "ArtistUrl": "https://youtube.com/channel/UCAW2scxfdEMwVRAOul0D4zw",
                    "time": "4:51",
                    "second": 291
                },
                {
                    "SongTitle": "我还想她 林俊杰 (歌词版)",
                    "SongID": "J7ahXIrj91k",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=J7ahXIrj91k&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=J7ahXIrj91k&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "GM Lyric",
                    "ArtistID": "UC8wXsgv4k9fGAo8LwE-KwPQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC8wXsgv4k9fGAo8LwE-KwPQ",
                    "ArtistUrl": "https://youtube.com/channel/UC8wXsgv4k9fGAo8LwE-KwPQ",
                    "time": "4:08",
                    "second": 248
                },
                {
                    "SongTitle": "悬日",
                    "SongID": "Nf1C1fSJG_8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Nf1C1fSJG_8&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=Nf1C1fSJG_8&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "田馥甄",
                    "ArtistID": "UCGkj4uoWx_1BA2tF9Q-9Y6w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCGkj4uoWx_1BA2tF9Q-9Y6w",
                    "ArtistUrl": "https://youtube.com/channel/UCGkj4uoWx_1BA2tF9Q-9Y6w",
                    "time": "5:23",
                    "second": 323
                },
                {
                    "SongTitle": "WITHOUT YOU",
                    "SongID": "SJOKlqJho8U",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=SJOKlqJho8U&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=SJOKlqJho8U&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "The Kid Laroi",
                    "ArtistID": "UCof4hiuvv9BPhVCh90QHErw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCof4hiuvv9BPhVCh90QHErw",
                    "ArtistUrl": "https://youtube.com/channel/UCof4hiuvv9BPhVCh90QHErw",
                    "time": "3:03",
                    "second": 183
                },
                {
                    "SongTitle": "Lego House",
                    "SongID": "c4BLVznuWnU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=c4BLVznuWnU&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=c4BLVznuWnU&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "Ed Sheeran",
                    "ArtistID": "UClmXPfaYhXOYsNn_QUyheWQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UClmXPfaYhXOYsNn_QUyheWQ",
                    "ArtistUrl": "https://youtube.com/channel/UClmXPfaYhXOYsNn_QUyheWQ",
                    "time": "4:06",
                    "second": 246
                },
                {
                    "SongTitle": "香味",
                    "SongID": "q61n4Qg7su8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=q61n4Qg7su8&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=q61n4Qg7su8&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "RECall",
                    "ArtistID": "UCX428RyEDwZQHK0Jb62xOBw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCX428RyEDwZQHK0Jb62xOBw",
                    "ArtistUrl": "https://youtube.com/channel/UCX428RyEDwZQHK0Jb62xOBw",
                    "time": "4:35",
                    "second": 275
                },
                {
                    "SongTitle": "Best Part (Audio) (合作演出：Daniel Caesar)",
                    "SongID": "vBy7FaapGRo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=vBy7FaapGRo&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=vBy7FaapGRo&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "Daniel Caesar",
                    "ArtistID": "UCcbtSIy5DlnpVIxW8hIvxBw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCcbtSIy5DlnpVIxW8hIvxBw",
                    "ArtistUrl": "https://youtube.com/channel/UCcbtSIy5DlnpVIxW8hIvxBw",
                    "time": "3:31",
                    "second": 211
                },
                {
                    "SongTitle": "눈의 꽃 1시간 (미안하다,사랑한다 OST) (雪の華) -  박효신",
                    "SongID": "ksqQ0xYuojQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ksqQ0xYuojQ&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=ksqQ0xYuojQ&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "RY SOUND",
                    "ArtistID": "UCJa9Oztjn_ODFEd6DTjmH_w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCJa9Oztjn_ODFEd6DTjmH_w",
                    "ArtistUrl": "https://youtube.com/channel/UCJa9Oztjn_ODFEd6DTjmH_w",
                    "time": "1:01:38",
                    "second": 61
                },
                {
                    "SongTitle": "Modern Loneliness",
                    "SongID": "bDidwMxir4o",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=bDidwMxir4o&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=bDidwMxir4o&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "Lauv",
                    "ArtistID": "UCWjoDY2SXJ5dvcdunWI6mjQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCWjoDY2SXJ5dvcdunWI6mjQ",
                    "ArtistUrl": "https://youtube.com/channel/UCWjoDY2SXJ5dvcdunWI6mjQ",
                    "time": "4:08",
                    "second": 248
                },
                {
                    "SongTitle": "Quit Smoking",
                    "SongID": "V7hJgBcRDwM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=V7hJgBcRDwM&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=V7hJgBcRDwM&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "李榮浩",
                    "ArtistID": "UCLZ9hbBmb_5mEclHVY5yOBg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCLZ9hbBmb_5mEclHVY5yOBg",
                    "ArtistUrl": "https://youtube.com/channel/UCLZ9hbBmb_5mEclHVY5yOBg",
                    "time": "5:19",
                    "second": 319
                },
                {
                    "SongTitle": "Lost Stars",
                    "SongID": "cL4uhaQ58Rk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=cL4uhaQ58Rk&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=cL4uhaQ58Rk&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "亞當·李維",
                    "ArtistID": "UCi-kAl0YSpCJOt7Irwylx6A",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCi-kAl0YSpCJOt7Irwylx6A",
                    "ArtistUrl": "https://youtube.com/channel/UCi-kAl0YSpCJOt7Irwylx6A",
                    "time": "4:35",
                    "second": 275
                },
                {
                    "SongTitle": "Merry Christmas",
                    "SongID": "Q_yuO8UNGmY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Q_yuO8UNGmY&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=Q_yuO8UNGmY&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "Ed Sheeran",
                    "ArtistID": "UClmXPfaYhXOYsNn_QUyheWQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UClmXPfaYhXOYsNn_QUyheWQ",
                    "ArtistUrl": "https://youtube.com/channel/UClmXPfaYhXOYsNn_QUyheWQ",
                    "time": "3:30",
                    "second": 210
                },
                {
                    "SongTitle": "Bad Habits",
                    "SongID": "orJSJGHjBLI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=orJSJGHjBLI&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "SongUrl": "https://youtube.com/watch?v=orJSJGHjBLI&list=PL3qm_8TRqiefEPvL5wvbnrzH3v5F-ZXhk",
                    "Artist": "Ed Sheeran",
                    "ArtistID": "UClmXPfaYhXOYsNn_QUyheWQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UClmXPfaYhXOYsNn_QUyheWQ",
                    "ArtistUrl": "https://youtube.com/channel/UClmXPfaYhXOYsNn_QUyheWQ",
                    "time": "4:01",
                    "second": 241
                }
            ]
        }
    ];
    return { data };
});
