export default defineEventHandler((event) => {
    const data = [
        {
            "ListName": "韓國女團必聽金曲",
            "SongList": [
                {
                    "SongTitle": "ETA",
                    "SongID": "jOTfBlKSQYY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=jOTfBlKSQYY&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=jOTfBlKSQYY&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "NewJeans",
                    "ArtistID": "UCxOqS3cYg4FaHbobICo7nFQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCxOqS3cYg4FaHbobICo7nFQ",
                    "ArtistUrl": "https://youtube.com/channel/UCxOqS3cYg4FaHbobICo7nFQ",
                    "time": "3:37",
                    "second": 217
                },
                {
                    "SongTitle": "ETA",
                    "SongID": "jOTfBlKSQYY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=jOTfBlKSQYY&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=jOTfBlKSQYY&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "NewJeans",
                    "ArtistID": "UCxOqS3cYg4FaHbobICo7nFQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCxOqS3cYg4FaHbobICo7nFQ",
                    "ArtistUrl": "https://youtube.com/channel/UCxOqS3cYg4FaHbobICo7nFQ",
                    "time": "3:37",
                    "second": 217
                },
                {
                    "SongTitle": "Shut Down",
                    "SongID": "POe9SOEKotk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=POe9SOEKotk&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=POe9SOEKotk&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "BLACKPINK",
                    "ArtistID": "UCkbbMCA40i18i7UdjayMPAg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCkbbMCA40i18i7UdjayMPAg",
                    "ArtistUrl": "https://youtube.com/channel/UCkbbMCA40i18i7UdjayMPAg",
                    "time": "3:01",
                    "second": 181
                },
                {
                    "SongTitle": "I AM",
                    "SongID": "6ZUIwj3FgUY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=6ZUIwj3FgUY&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=6ZUIwj3FgUY&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "IVE",
                    "ArtistID": "UC_4Y1QqJr60C5Z7-eQWy-mw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC_4Y1QqJr60C5Z7-eQWy-mw",
                    "ArtistUrl": "https://youtube.com/channel/UC_4Y1QqJr60C5Z7-eQWy-mw",
                    "time": "3:05",
                    "second": 185
                },
                {
                    "SongTitle": "Spicy",
                    "SongID": "Os_heh8vPfs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Os_heh8vPfs&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=Os_heh8vPfs&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "aespa",
                    "ArtistID": "UCEdZAdnnKqbaHOlv8nM6OtA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCEdZAdnnKqbaHOlv8nM6OtA",
                    "ArtistUrl": "https://youtube.com/channel/UCEdZAdnnKqbaHOlv8nM6OtA",
                    "time": "3:25",
                    "second": 205
                },
                {
                    "SongTitle": "UNFORGIVEN (合作演出：奈爾・羅傑斯)",
                    "SongID": "UBURTj20HXI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=UBURTj20HXI&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=UBURTj20HXI&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "LE SSERAFIM",
                    "ArtistID": "UC-clMkTZa7k-FxmNgMjoCgQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC-clMkTZa7k-FxmNgMjoCgQ",
                    "ArtistUrl": "https://youtube.com/channel/UC-clMkTZa7k-FxmNgMjoCgQ",
                    "time": "4:20",
                    "second": 260
                },
                {
                    "SongTitle": "ODD EYE CIRCLE ‘Air Force One' MV | ARTMS",
                    "SongID": "UDxID0_A9x4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=UDxID0_A9x4&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=UDxID0_A9x4&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "Official ARTMS",
                    "ArtistID": "UChXC6ok0LaZIpf-50SIFf0Q",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UChXC6ok0LaZIpf-50SIFf0Q",
                    "ArtistUrl": "https://youtube.com/channel/UChXC6ok0LaZIpf-50SIFf0Q",
                    "time": "3:10",
                    "second": 190
                },
                {
                    "SongTitle": "Nxde",
                    "SongID": "fCO7f0SmrDc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=fCO7f0SmrDc&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=fCO7f0SmrDc&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "(G)I-DLE",
                    "ArtistID": "UCWT2ZfW7d8YI-HinHEVhyCA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCWT2ZfW7d8YI-HinHEVhyCA",
                    "ArtistUrl": "https://youtube.com/channel/UCWT2ZfW7d8YI-HinHEVhyCA",
                    "time": "3:04",
                    "second": 184
                },
                {
                    "SongTitle": "Kill This Love",
                    "SongID": "2S24-y0Ij3Y",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=2S24-y0Ij3Y&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=2S24-y0Ij3Y&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "BLACKPINK",
                    "ArtistID": "UCkbbMCA40i18i7UdjayMPAg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCkbbMCA40i18i7UdjayMPAg",
                    "ArtistUrl": "https://youtube.com/channel/UCkbbMCA40i18i7UdjayMPAg",
                    "time": "3:14",
                    "second": 194
                },
                {
                    "SongTitle": "Kitsch",
                    "SongID": "pG6iaOMV46I",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=pG6iaOMV46I&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=pG6iaOMV46I&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "IVE",
                    "ArtistID": "UC_4Y1QqJr60C5Z7-eQWy-mw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC_4Y1QqJr60C5Z7-eQWy-mw",
                    "ArtistUrl": "https://youtube.com/channel/UC_4Y1QqJr60C5Z7-eQWy-mw",
                    "time": "3:22",
                    "second": 202
                },
                {
                    "SongTitle": "The Feels",
                    "SongID": "f5_wn8mexmM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=f5_wn8mexmM&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=f5_wn8mexmM&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "TWICE",
                    "ArtistID": "UCAq0pFGa2w9SjxOq0ZxKVIw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCAq0pFGa2w9SjxOq0ZxKVIw",
                    "ArtistUrl": "https://youtube.com/channel/UCAq0pFGa2w9SjxOq0ZxKVIw",
                    "time": "3:52",
                    "second": 232
                },
                {
                    "SongTitle": "Eve, Psyche & The Bluebeard's wife",
                    "SongID": "dZs_cLHfnNA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=dZs_cLHfnNA&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=dZs_cLHfnNA&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "LE SSERAFIM",
                    "ArtistID": "UC-clMkTZa7k-FxmNgMjoCgQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC-clMkTZa7k-FxmNgMjoCgQ",
                    "ArtistUrl": "https://youtube.com/channel/UC-clMkTZa7k-FxmNgMjoCgQ",
                    "time": "3:48",
                    "second": 228
                },
                {
                    "SongTitle": "Love Me Like This",
                    "SongID": "EDnwWcFpObo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=EDnwWcFpObo&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=EDnwWcFpObo&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "NMIXX",
                    "ArtistID": "UC_Cx288SDUD9liYn7CiJLAA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC_Cx288SDUD9liYn7CiJLAA",
                    "ArtistUrl": "https://youtube.com/channel/UC_Cx288SDUD9liYn7CiJLAA",
                    "time": "3:32",
                    "second": 212
                },
                {
                    "SongTitle": "TOMBOY",
                    "SongID": "Jh4QFaPmdss",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Jh4QFaPmdss&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=Jh4QFaPmdss&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "(G)I-DLE",
                    "ArtistID": "UCWT2ZfW7d8YI-HinHEVhyCA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCWT2ZfW7d8YI-HinHEVhyCA",
                    "ArtistUrl": "https://youtube.com/channel/UCWT2ZfW7d8YI-HinHEVhyCA",
                    "time": "3:18",
                    "second": 198
                },
                {
                    "SongTitle": "How You Like That",
                    "SongID": "ioNng23DkIM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ioNng23DkIM&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=ioNng23DkIM&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "BLACKPINK",
                    "ArtistID": "UCkbbMCA40i18i7UdjayMPAg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCkbbMCA40i18i7UdjayMPAg",
                    "ArtistUrl": "https://youtube.com/channel/UCkbbMCA40i18i7UdjayMPAg",
                    "time": "3:04",
                    "second": 184
                },
                {
                    "SongTitle": "After LIKE",
                    "SongID": "F0B7HDiY-10",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=F0B7HDiY-10&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=F0B7HDiY-10&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "IVE",
                    "ArtistID": "UC_4Y1QqJr60C5Z7-eQWy-mw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC_4Y1QqJr60C5Z7-eQWy-mw",
                    "ArtistUrl": "https://youtube.com/channel/UC_4Y1QqJr60C5Z7-eQWy-mw",
                    "time": "3:01",
                    "second": 181
                },
                {
                    "SongTitle": "SET ME FREE",
                    "SongID": "w4cTYnOPdNk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=w4cTYnOPdNk&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=w4cTYnOPdNk&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "TWICE",
                    "ArtistID": "UCAq0pFGa2w9SjxOq0ZxKVIw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCAq0pFGa2w9SjxOq0ZxKVIw",
                    "ArtistUrl": "https://youtube.com/channel/UCAq0pFGa2w9SjxOq0ZxKVIw",
                    "time": "3:32",
                    "second": 212
                },
                {
                    "SongTitle": "ANTIFRAGILE",
                    "SongID": "pyf8cbqyfPs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=pyf8cbqyfPs&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=pyf8cbqyfPs&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "LE SSERAFIM",
                    "ArtistID": "UC-clMkTZa7k-FxmNgMjoCgQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC-clMkTZa7k-FxmNgMjoCgQ",
                    "ArtistUrl": "https://youtube.com/channel/UC-clMkTZa7k-FxmNgMjoCgQ",
                    "time": "3:52",
                    "second": 232
                },
                {
                    "SongTitle": "WANNABE",
                    "SongID": "fE2h3lGlOsk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=fE2h3lGlOsk&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=fE2h3lGlOsk&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "ITZY",
                    "ArtistID": "UCTP45_DE3fMLujU8sZ-MBzw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCTP45_DE3fMLujU8sZ-MBzw",
                    "ArtistUrl": "https://youtube.com/channel/UCTP45_DE3fMLujU8sZ-MBzw",
                    "time": "3:39",
                    "second": 219
                },
                {
                    "SongTitle": "Super Shy",
                    "SongID": "wU2siJ2c5TA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=wU2siJ2c5TA&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=wU2siJ2c5TA&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "NewJeans",
                    "ArtistID": "UCxOqS3cYg4FaHbobICo7nFQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCxOqS3cYg4FaHbobICo7nFQ",
                    "ArtistUrl": "https://youtube.com/channel/UCxOqS3cYg4FaHbobICo7nFQ",
                    "time": "2:42",
                    "second": 162
                },
                {
                    "SongTitle": "Ice Cream",
                    "SongID": "vRXZj0DzXIA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=vRXZj0DzXIA&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=vRXZj0DzXIA&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "席琳娜·戈梅茲",
                    "ArtistID": "UCeBYRgPhy8kcRmIGQWKuqdQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCeBYRgPhy8kcRmIGQWKuqdQ",
                    "ArtistUrl": "https://youtube.com/channel/UCeBYRgPhy8kcRmIGQWKuqdQ",
                    "time": "3:03",
                    "second": 183
                },
                {
                    "SongTitle": "Cupid",
                    "SongID": "CcAqoRmQWhA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=CcAqoRmQWhA&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=CcAqoRmQWhA&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "FIFTY FIFTY",
                    "ArtistID": "UCMca81qQN9V3jOe7wyfbvDQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCMca81qQN9V3jOe7wyfbvDQ",
                    "ArtistUrl": "https://youtube.com/channel/UCMca81qQN9V3jOe7wyfbvDQ",
                    "time": "2:55",
                    "second": 175
                },
                {
                    "SongTitle": "Talk that Talk",
                    "SongID": "k6jqx9kZgPM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=k6jqx9kZgPM&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=k6jqx9kZgPM&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "TWICE",
                    "ArtistID": "UCAq0pFGa2w9SjxOq0ZxKVIw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCAq0pFGa2w9SjxOq0ZxKVIw",
                    "ArtistUrl": "https://youtube.com/channel/UCAq0pFGa2w9SjxOq0ZxKVIw",
                    "time": "2:55",
                    "second": 175
                },
                {
                    "SongTitle": "Girls",
                    "SongID": "dYRITmpFbJ4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=dYRITmpFbJ4&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=dYRITmpFbJ4&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "aespa",
                    "ArtistID": "UCEdZAdnnKqbaHOlv8nM6OtA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCEdZAdnnKqbaHOlv8nM6OtA",
                    "ArtistUrl": "https://youtube.com/channel/UCEdZAdnnKqbaHOlv8nM6OtA",
                    "time": "4:29",
                    "second": 269
                },
                {
                    "SongTitle": "SNEAKERS",
                    "SongID": "Hbb5GPxXF1w",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Hbb5GPxXF1w&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=Hbb5GPxXF1w&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "ITZY",
                    "ArtistID": "UCTP45_DE3fMLujU8sZ-MBzw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCTP45_DE3fMLujU8sZ-MBzw",
                    "ArtistUrl": "https://youtube.com/channel/UCTP45_DE3fMLujU8sZ-MBzw",
                    "time": "3:05",
                    "second": 185
                },
                {
                    "SongTitle": "Hate Rodrigo (合作演出：YUQI)",
                    "SongID": "1XIi9ofX2kE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=1XIi9ofX2kE&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=1XIi9ofX2kE&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "YENA",
                    "ArtistID": "UC4mOLela441MNvGJNy6h8bg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC4mOLela441MNvGJNy6h8bg",
                    "ArtistUrl": "https://youtube.com/channel/UC4mOLela441MNvGJNy6h8bg",
                    "time": "3:49",
                    "second": 229
                },
                {
                    "SongTitle": "Lovesick Girls",
                    "SongID": "dyRsYk0LyA8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=dyRsYk0LyA8&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=dyRsYk0LyA8&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "BLACKPINK",
                    "ArtistID": "UCkbbMCA40i18i7UdjayMPAg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCkbbMCA40i18i7UdjayMPAg",
                    "ArtistUrl": "https://youtube.com/channel/UCkbbMCA40i18i7UdjayMPAg",
                    "time": "3:22",
                    "second": 202
                },
                {
                    "SongTitle": "DICE",
                    "SongID": "p1bjnyDqI9k",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=p1bjnyDqI9k&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=p1bjnyDqI9k&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "NMIXX",
                    "ArtistID": "UC_Cx288SDUD9liYn7CiJLAA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC_Cx288SDUD9liYn7CiJLAA",
                    "ArtistUrl": "https://youtube.com/channel/UC_Cx288SDUD9liYn7CiJLAA",
                    "time": "3:19",
                    "second": 199
                },
                {
                    "SongTitle": "FANCY",
                    "SongID": "kOHB85vDuow",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=kOHB85vDuow&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=kOHB85vDuow&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "TWICE",
                    "ArtistID": "UCAq0pFGa2w9SjxOq0ZxKVIw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCAq0pFGa2w9SjxOq0ZxKVIw",
                    "ArtistUrl": "https://youtube.com/channel/UCAq0pFGa2w9SjxOq0ZxKVIw",
                    "time": "3:39",
                    "second": 219
                },
                {
                    "SongTitle": "Next Level",
                    "SongID": "4TWR90KJl84",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=4TWR90KJl84&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=4TWR90KJl84&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "aespa",
                    "ArtistID": "UCEdZAdnnKqbaHOlv8nM6OtA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCEdZAdnnKqbaHOlv8nM6OtA",
                    "ArtistUrl": "https://youtube.com/channel/UCEdZAdnnKqbaHOlv8nM6OtA",
                    "time": "3:56",
                    "second": 236
                },
                {
                    "SongTitle": "LOCO",
                    "SongID": "MjCZfZfucEc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=MjCZfZfucEc&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=MjCZfZfucEc&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "ITZY",
                    "ArtistID": "UCTP45_DE3fMLujU8sZ-MBzw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCTP45_DE3fMLujU8sZ-MBzw",
                    "ArtistUrl": "https://youtube.com/channel/UCTP45_DE3fMLujU8sZ-MBzw",
                    "time": "3:53",
                    "second": 233
                },
                {
                    "SongTitle": "WA DA DA",
                    "SongID": "n0j5NPptyM0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=n0j5NPptyM0&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=n0j5NPptyM0&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "Kep1er",
                    "ArtistID": "UCAKvDuIX3m1AUdPpDSqV_3w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCAKvDuIX3m1AUdPpDSqV_3w",
                    "ArtistUrl": "https://youtube.com/channel/UCAKvDuIX3m1AUdPpDSqV_3w",
                    "time": "3:18",
                    "second": 198
                },
                {
                    "SongTitle": "BOOMBAYAH (KR Ver.)",
                    "SongID": "bwmSjveL3Lc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=bwmSjveL3Lc&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=bwmSjveL3Lc&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "BLACKPINK",
                    "ArtistID": "UCkbbMCA40i18i7UdjayMPAg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCkbbMCA40i18i7UdjayMPAg",
                    "ArtistUrl": "https://youtube.com/channel/UCkbbMCA40i18i7UdjayMPAg",
                    "time": "4:04",
                    "second": 244
                },
                {
                    "SongTitle": "Step Back",
                    "SongID": "uBY1AoiF5Vo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=uBY1AoiF5Vo&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=uBY1AoiF5Vo&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "GOT the beat",
                    "ArtistID": "UCDDpqmryjNunitS05bv7-8w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCDDpqmryjNunitS05bv7-8w",
                    "ArtistUrl": "https://youtube.com/channel/UCDDpqmryjNunitS05bv7-8w",
                    "time": "3:51",
                    "second": 231
                },
                {
                    "SongTitle": "What is Love?",
                    "SongID": "i0p1bmr0EmE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=i0p1bmr0EmE&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=i0p1bmr0EmE&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "TWICE",
                    "ArtistID": "UCAq0pFGa2w9SjxOq0ZxKVIw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCAq0pFGa2w9SjxOq0ZxKVIw",
                    "ArtistUrl": "https://youtube.com/channel/UCAq0pFGa2w9SjxOq0ZxKVIw",
                    "time": "3:44",
                    "second": 224
                },
                {
                    "SongTitle": "Black Mamba",
                    "SongID": "ZeerrnuLi5E",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ZeerrnuLi5E&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=ZeerrnuLi5E&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "aespa",
                    "ArtistID": "UCEdZAdnnKqbaHOlv8nM6OtA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCEdZAdnnKqbaHOlv8nM6OtA",
                    "ArtistUrl": "https://youtube.com/channel/UCEdZAdnnKqbaHOlv8nM6OtA",
                    "time": "3:50",
                    "second": 230
                },
                {
                    "SongTitle": "In the Morning",
                    "SongID": "_ysomCGaZLw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=_ysomCGaZLw&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=_ysomCGaZLw&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "ITZY",
                    "ArtistID": "UCTP45_DE3fMLujU8sZ-MBzw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCTP45_DE3fMLujU8sZ-MBzw",
                    "ArtistUrl": "https://youtube.com/channel/UCTP45_DE3fMLujU8sZ-MBzw",
                    "time": "3:05",
                    "second": 185
                },
                {
                    "SongTitle": "DUMB DUMB",
                    "SongID": "tg2uF3R_Ozo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=tg2uF3R_Ozo&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=tg2uF3R_Ozo&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "SOMI",
                    "ArtistID": "UCDnYJA3OXXhRKYPe3jzLGeQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCDnYJA3OXXhRKYPe3jzLGeQ",
                    "ArtistUrl": "https://youtube.com/channel/UCDnYJA3OXXhRKYPe3jzLGeQ",
                    "time": "2:59",
                    "second": 179
                },
                {
                    "SongTitle": "AS IF IT'S YOUR LAST -KR ver.-",
                    "SongID": "Amq-qlqbjYA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Amq-qlqbjYA&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=Amq-qlqbjYA&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "BLACKPINK",
                    "ArtistID": "UCkbbMCA40i18i7UdjayMPAg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCkbbMCA40i18i7UdjayMPAg",
                    "ArtistUrl": "https://youtube.com/channel/UCkbbMCA40i18i7UdjayMPAg",
                    "time": "3:37",
                    "second": 217
                },
                {
                    "SongTitle": "O.O",
                    "SongID": "3GWscde8rM8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=3GWscde8rM8&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=3GWscde8rM8&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "NMIXX",
                    "ArtistID": "UC_Cx288SDUD9liYn7CiJLAA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC_Cx288SDUD9liYn7CiJLAA",
                    "ArtistUrl": "https://youtube.com/channel/UC_Cx288SDUD9liYn7CiJLAA",
                    "time": "3:34",
                    "second": 214
                },
                {
                    "SongTitle": "Alcohol-Free",
                    "SongID": "XA2YEHn-A8Q",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=XA2YEHn-A8Q&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=XA2YEHn-A8Q&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "TWICE",
                    "ArtistID": "UCAq0pFGa2w9SjxOq0ZxKVIw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCAq0pFGa2w9SjxOq0ZxKVIw",
                    "ArtistUrl": "https://youtube.com/channel/UCAq0pFGa2w9SjxOq0ZxKVIw",
                    "time": "3:34",
                    "second": 214
                },
                {
                    "SongTitle": "After School",
                    "SongID": "qfVuRQX0ydQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=qfVuRQX0ydQ&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=qfVuRQX0ydQ&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "Weeekly",
                    "ArtistID": "UCkkBzJl-jD2qWC_r67NSqEg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCkkBzJl-jD2qWC_r67NSqEg",
                    "ArtistUrl": "https://youtube.com/channel/UCkkBzJl-jD2qWC_r67NSqEg",
                    "time": "3:45",
                    "second": 225
                },
                {
                    "SongTitle": "DALLA DALLA",
                    "SongID": "pNfTK39k55U",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=pNfTK39k55U&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=pNfTK39k55U&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "ITZY",
                    "ArtistID": "UCTP45_DE3fMLujU8sZ-MBzw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCTP45_DE3fMLujU8sZ-MBzw",
                    "ArtistUrl": "https://youtube.com/channel/UCTP45_DE3fMLujU8sZ-MBzw",
                    "time": "3:47",
                    "second": 227
                },
                {
                    "SongTitle": "FOREVER 1",
                    "SongID": "Qpf26PtBXgo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Qpf26PtBXgo&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=Qpf26PtBXgo&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "少女時代",
                    "ArtistID": "UCGn8T3PmIkow87GeZC9mW7g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCGn8T3PmIkow87GeZC9mW7g",
                    "ArtistUrl": "https://youtube.com/channel/UCGn8T3PmIkow87GeZC9mW7g",
                    "time": "3:34",
                    "second": 214
                },
                {
                    "SongTitle": "Dreams Come True",
                    "SongID": "H69tJmsgd9I",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=H69tJmsgd9I&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=H69tJmsgd9I&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "aespa",
                    "ArtistID": "UCEdZAdnnKqbaHOlv8nM6OtA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCEdZAdnnKqbaHOlv8nM6OtA",
                    "ArtistUrl": "https://youtube.com/channel/UCEdZAdnnKqbaHOlv8nM6OtA",
                    "time": "3:41",
                    "second": 221
                },
                {
                    "SongTitle": "Queendom",
                    "SongID": "c9RzZpV460k",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=c9RzZpV460k&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=c9RzZpV460k&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "Red Velvet",
                    "ArtistID": "UCHmZYTfdTyVKQEJicLiXEOg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCHmZYTfdTyVKQEJicLiXEOg",
                    "ArtistUrl": "https://youtube.com/channel/UCHmZYTfdTyVKQEJicLiXEOg",
                    "time": "3:10",
                    "second": 190
                },
                {
                    "SongTitle": "SCIENTIST",
                    "SongID": "vPwaXytZcgI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=vPwaXytZcgI&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=vPwaXytZcgI&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "TWICE",
                    "ArtistID": "UCAq0pFGa2w9SjxOq0ZxKVIw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCAq0pFGa2w9SjxOq0ZxKVIw",
                    "ArtistUrl": "https://youtube.com/channel/UCAq0pFGa2w9SjxOq0ZxKVIw",
                    "time": "3:21",
                    "second": 201
                },
                {
                    "SongTitle": "Attention",
                    "SongID": "js1CtxSY38I",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=js1CtxSY38I&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=js1CtxSY38I&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "NewJeans",
                    "ArtistID": "UCxOqS3cYg4FaHbobICo7nFQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCxOqS3cYg4FaHbobICo7nFQ",
                    "ArtistUrl": "https://youtube.com/channel/UCxOqS3cYg4FaHbobICo7nFQ",
                    "time": "4:23",
                    "second": 263
                },
                {
                    "SongTitle": "Not Shy",
                    "SongID": "wTowEKjDGkU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=wTowEKjDGkU&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=wTowEKjDGkU&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "ITZY",
                    "ArtistID": "UCTP45_DE3fMLujU8sZ-MBzw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCTP45_DE3fMLujU8sZ-MBzw",
                    "ArtistUrl": "https://youtube.com/channel/UCTP45_DE3fMLujU8sZ-MBzw",
                    "time": "4:03",
                    "second": 243
                },
                {
                    "SongTitle": "RUN2U (TAK Remix)",
                    "SongID": "grG41kS4MUA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=grG41kS4MUA&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=grG41kS4MUA&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "STAYC",
                    "ArtistID": "UCwc9eSwp1MAoToS9QUTRpDw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCwc9eSwp1MAoToS9QUTRpDw",
                    "ArtistUrl": "https://youtube.com/channel/UCwc9eSwp1MAoToS9QUTRpDw",
                    "time": "3:36",
                    "second": 216
                },
                {
                    "SongTitle": "Life’s Too Short (English Ver.)",
                    "SongID": "z2ZjutyxmjA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=z2ZjutyxmjA&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=z2ZjutyxmjA&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "aespa",
                    "ArtistID": "UCEdZAdnnKqbaHOlv8nM6OtA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCEdZAdnnKqbaHOlv8nM6OtA",
                    "ArtistUrl": "https://youtube.com/channel/UCEdZAdnnKqbaHOlv8nM6OtA",
                    "time": "3:08",
                    "second": 188
                },
                {
                    "SongTitle": "Feel My Rhythm",
                    "SongID": "R9At2ICm4LQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=R9At2ICm4LQ&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=R9At2ICm4LQ&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "Red Velvet",
                    "ArtistID": "UCHmZYTfdTyVKQEJicLiXEOg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCHmZYTfdTyVKQEJicLiXEOg",
                    "ArtistUrl": "https://youtube.com/channel/UCHmZYTfdTyVKQEJicLiXEOg",
                    "time": "3:58",
                    "second": 238
                },
                {
                    "SongTitle": "Generation",
                    "SongID": "0cZ7o0Wn_dc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=0cZ7o0Wn_dc&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=0cZ7o0Wn_dc&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "tripleS",
                    "ArtistID": "UCn33sVkKks4vU4CbOXXmjQA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCn33sVkKks4vU4CbOXXmjQA",
                    "ArtistUrl": "https://youtube.com/channel/UCn33sVkKks4vU4CbOXXmjQA",
                    "time": "3:12",
                    "second": 192
                },
                {
                    "SongTitle": "Pirate",
                    "SongID": "-2X-pL06628",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=-2X-pL06628&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=-2X-pL06628&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "EVERGLOW",
                    "ArtistID": "UCT4Z6ZLJisGUy0z2LHzi2jQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCT4Z6ZLJisGUy0z2LHzi2jQ",
                    "ArtistUrl": "https://youtube.com/channel/UCT4Z6ZLJisGUy0z2LHzi2jQ",
                    "time": "3:38",
                    "second": 218
                },
                {
                    "SongTitle": "Up!",
                    "SongID": "hr-325mclek",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=hr-325mclek&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=hr-325mclek&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "Kep1er",
                    "ArtistID": "UCAKvDuIX3m1AUdPpDSqV_3w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCAKvDuIX3m1AUdPpDSqV_3w",
                    "ArtistUrl": "https://youtube.com/channel/UCAKvDuIX3m1AUdPpDSqV_3w",
                    "time": "3:19",
                    "second": 199
                },
                {
                    "SongTitle": "BEAUTIFUL MONSTER",
                    "SongID": "juQvizeZJFM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=juQvizeZJFM&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=juQvizeZJFM&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "STAYC",
                    "ArtistID": "UCwc9eSwp1MAoToS9QUTRpDw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCwc9eSwp1MAoToS9QUTRpDw",
                    "ArtistUrl": "https://youtube.com/channel/UCwc9eSwp1MAoToS9QUTRpDw",
                    "time": "3:01",
                    "second": 181
                },
                {
                    "SongTitle": "ILLELLA",
                    "SongID": "Vz508O9NNTg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Vz508O9NNTg&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=Vz508O9NNTg&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "MAMAMOO",
                    "ArtistID": "UCC_x7uhz40eyVag5DQnWj-g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCC_x7uhz40eyVag5DQnWj-g",
                    "ArtistUrl": "https://youtube.com/channel/UCC_x7uhz40eyVag5DQnWj-g",
                    "time": "3:29",
                    "second": 209
                },
                {
                    "SongTitle": "Birthday",
                    "SongID": "Ut1OzEVUiM4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Ut1OzEVUiM4&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=Ut1OzEVUiM4&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "Red Velvet",
                    "ArtistID": "UCHmZYTfdTyVKQEJicLiXEOg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCHmZYTfdTyVKQEJicLiXEOg",
                    "ArtistUrl": "https://youtube.com/channel/UCHmZYTfdTyVKQEJicLiXEOg",
                    "time": "4:05",
                    "second": 245
                },
                {
                    "SongTitle": "Panorama",
                    "SongID": "G8GaQdW2wHc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=G8GaQdW2wHc&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=G8GaQdW2wHc&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "IZ*ONE",
                    "ArtistID": "UCG81UKNsFg9Perf0uPQOsQw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCG81UKNsFg9Perf0uPQOsQw",
                    "ArtistUrl": "https://youtube.com/channel/UCG81UKNsFg9Perf0uPQOsQw",
                    "time": "3:52",
                    "second": 232
                },
                {
                    "SongTitle": "Flip That",
                    "SongID": "SPYX2y4NzTU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=SPYX2y4NzTU&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=SPYX2y4NzTU&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "本月少女",
                    "ArtistID": "UCa4ZqZPRjz9MYYnfpoh2few",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCa4ZqZPRjz9MYYnfpoh2few",
                    "ArtistUrl": "https://youtube.com/channel/UCa4ZqZPRjz9MYYnfpoh2few",
                    "time": "3:27",
                    "second": 207
                },
                {
                    "SongTitle": "Latata",
                    "SongID": "9mQk7Evt6Vs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=9mQk7Evt6Vs&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=9mQk7Evt6Vs&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "(G)I-DLE",
                    "ArtistID": "UCWT2ZfW7d8YI-HinHEVhyCA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCWT2ZfW7d8YI-HinHEVhyCA",
                    "ArtistUrl": "https://youtube.com/channel/UCWT2ZfW7d8YI-HinHEVhyCA",
                    "time": "3:42",
                    "second": 222
                },
                {
                    "SongTitle": "색안경 (STEREOTYPE)",
                    "SongID": "Xmxcnf2v_gs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Xmxcnf2v_gs&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=Xmxcnf2v_gs&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "STAYC",
                    "ArtistID": "UCwc9eSwp1MAoToS9QUTRpDw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCwc9eSwp1MAoToS9QUTRpDw",
                    "ArtistUrl": "https://youtube.com/channel/UCwc9eSwp1MAoToS9QUTRpDw",
                    "time": "3:12",
                    "second": 192
                },
                {
                    "SongTitle": "Boys Like You",
                    "SongID": "6uZy86ePgO0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=6uZy86ePgO0&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=6uZy86ePgO0&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "ITZY",
                    "ArtistID": "UCTP45_DE3fMLujU8sZ-MBzw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCTP45_DE3fMLujU8sZ-MBzw",
                    "ArtistUrl": "https://youtube.com/channel/UCTP45_DE3fMLujU8sZ-MBzw",
                    "time": "4:26",
                    "second": 266
                },
                {
                    "SongTitle": "Peek-A-Boo",
                    "SongID": "6uJf2IT2Zh8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=6uJf2IT2Zh8&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=6uJf2IT2Zh8&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "Red Velvet",
                    "ArtistID": "UCHmZYTfdTyVKQEJicLiXEOg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCHmZYTfdTyVKQEJicLiXEOg",
                    "ArtistUrl": "https://youtube.com/channel/UCHmZYTfdTyVKQEJicLiXEOg",
                    "time": "3:50",
                    "second": 230
                },
                {
                    "SongTitle": "28 Reasons",
                    "SongID": "G_BYjnopO6U",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=G_BYjnopO6U&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=G_BYjnopO6U&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "Seul Gi",
                    "ArtistID": "UCvAUJvMNPy1LLVKpFiu-X9w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCvAUJvMNPy1LLVKpFiu-X9w",
                    "ArtistUrl": "https://youtube.com/channel/UCvAUJvMNPy1LLVKpFiu-X9w",
                    "time": "3:47",
                    "second": 227
                },
                {
                    "SongTitle": "PTT (Paint the Town)",
                    "SongID": "_EEo-iE5u_A",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=_EEo-iE5u_A&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=_EEo-iE5u_A&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "本月少女",
                    "ArtistID": "UCa4ZqZPRjz9MYYnfpoh2few",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCa4ZqZPRjz9MYYnfpoh2few",
                    "ArtistUrl": "https://youtube.com/channel/UCa4ZqZPRjz9MYYnfpoh2few",
                    "time": "3:50",
                    "second": 230
                },
                {
                    "SongTitle": "KISS",
                    "SongID": "5UdoUmvu_n8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=5UdoUmvu_n8&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=5UdoUmvu_n8&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "TRI.BE",
                    "ArtistID": "UC_lpxJpTxlgQhxxQkAOWfmA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC_lpxJpTxlgQhxxQkAOWfmA",
                    "ArtistUrl": "https://youtube.com/channel/UC_lpxJpTxlgQhxxQkAOWfmA",
                    "time": "3:08",
                    "second": 188
                },
                {
                    "SongTitle": "Nonstop",
                    "SongID": "iDjQSdN_ig8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=iDjQSdN_ig8&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=iDjQSdN_ig8&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "Oh My Girl",
                    "ArtistID": "UCArTAXmvvTohDgCsegudy4w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCArTAXmvvTohDgCsegudy4w",
                    "ArtistUrl": "https://youtube.com/channel/UCArTAXmvvTohDgCsegudy4w",
                    "time": "3:24",
                    "second": 204
                },
                {
                    "SongTitle": "Violeta",
                    "SongID": "6eEZ7DJMzuk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=6eEZ7DJMzuk&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=6eEZ7DJMzuk&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "IZ*ONE",
                    "ArtistID": "UCG81UKNsFg9Perf0uPQOsQw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCG81UKNsFg9Perf0uPQOsQw",
                    "ArtistUrl": "https://youtube.com/channel/UCG81UKNsFg9Perf0uPQOsQw",
                    "time": "3:25",
                    "second": 205
                },
                {
                    "SongTitle": "GingaMingaYo (the strange world)",
                    "SongID": "YKKh8d4wZbU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=YKKh8d4wZbU&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=YKKh8d4wZbU&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "Billlie",
                    "ArtistID": "UC28EaHd6V5EFqgaKZG33pIQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC28EaHd6V5EFqgaKZG33pIQ",
                    "ArtistUrl": "https://youtube.com/channel/UC28EaHd6V5EFqgaKZG33pIQ",
                    "time": "5:09",
                    "second": 309
                },
                {
                    "SongTitle": "Illusion (Lyric Video)",
                    "SongID": "BpCvYeK5hcE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=BpCvYeK5hcE&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=BpCvYeK5hcE&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "aespa",
                    "ArtistID": "UCEdZAdnnKqbaHOlv8nM6OtA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCEdZAdnnKqbaHOlv8nM6OtA",
                    "ArtistUrl": "https://youtube.com/channel/UCEdZAdnnKqbaHOlv8nM6OtA",
                    "time": "3:29",
                    "second": 209
                },
                {
                    "SongTitle": "Chi Mat Ba Ram",
                    "SongID": "e70PkoJhQYM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=e70PkoJhQYM&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=e70PkoJhQYM&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "Brave Girls",
                    "ArtistID": "UChm_d4qO8txdwS4YadlvpSw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UChm_d4qO8txdwS4YadlvpSw",
                    "ArtistUrl": "https://youtube.com/channel/UChm_d4qO8txdwS4YadlvpSw",
                    "time": "3:50",
                    "second": 230
                },
                {
                    "SongTitle": "Hype Boy",
                    "SongID": "Rrf8uQFvICE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Rrf8uQFvICE&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=Rrf8uQFvICE&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "NewJeans",
                    "ArtistID": "UCxOqS3cYg4FaHbobICo7nFQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCxOqS3cYg4FaHbobICo7nFQ",
                    "ArtistUrl": "https://youtube.com/channel/UCxOqS3cYg4FaHbobICo7nFQ",
                    "time": "2:57",
                    "second": 177
                },
                {
                    "SongTitle": "Dun Dun Dance",
                    "SongID": "HzOjwL7IP_o",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=HzOjwL7IP_o&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=HzOjwL7IP_o&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "Oh My Girl",
                    "ArtistID": "UCArTAXmvvTohDgCsegudy4w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCArTAXmvvTohDgCsegudy4w",
                    "ArtistUrl": "https://youtube.com/channel/UCArTAXmvvTohDgCsegudy4w",
                    "time": "4:08",
                    "second": 248
                },
                {
                    "SongTitle": "SMILEY (合作演出：BIBI)",
                    "SongID": "y9kkXTucnLU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=y9kkXTucnLU&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=y9kkXTucnLU&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "Jena",
                    "ArtistID": "UC4mOLela441MNvGJNy6h8bg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC4mOLela441MNvGJNy6h8bg",
                    "ArtistUrl": "https://youtube.com/channel/UC4mOLela441MNvGJNy6h8bg",
                    "time": "4:14",
                    "second": 254
                },
                {
                    "SongTitle": "Tick Tick Boom",
                    "SongID": "dGJSl-NcXlk",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=dGJSl-NcXlk&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=dGJSl-NcXlk&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "Class:y",
                    "ArtistID": "UCEHoJ5bHcJ9PVCE_Nn0dDYA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCEHoJ5bHcJ9PVCE_Nn0dDYA",
                    "ArtistUrl": "https://youtube.com/channel/UCEHoJ5bHcJ9PVCE_Nn0dDYA",
                    "time": "5:13",
                    "second": 313
                },
                {
                    "SongTitle": "Loveable",
                    "SongID": "4zmWVaAZU-s",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=4zmWVaAZU-s&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=4zmWVaAZU-s&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "JO YURI",
                    "ArtistID": "UCwiHPGVc8ysb9mhOw9HjcTA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCwiHPGVc8ysb9mhOw9HjcTA",
                    "ArtistUrl": "https://youtube.com/channel/UCwiHPGVc8ysb9mhOw9HjcTA",
                    "time": "3:13",
                    "second": 193
                },
                {
                    "SongTitle": "LOVE DIVE",
                    "SongID": "l-jZOXa7gQY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=l-jZOXa7gQY&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=l-jZOXa7gQY&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "IVE",
                    "ArtistID": "UC_4Y1QqJr60C5Z7-eQWy-mw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC_4Y1QqJr60C5Z7-eQWy-mw",
                    "ArtistUrl": "https://youtube.com/channel/UC_4Y1QqJr60C5Z7-eQWy-mw",
                    "time": "2:58",
                    "second": 178
                },
                {
                    "SongTitle": "Underwater",
                    "SongID": "ny1YiHlX_iE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ny1YiHlX_iE&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=ny1YiHlX_iE&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "權恩菲",
                    "ArtistID": "UCqxneFT-NdkFAyVdmhD9drg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCqxneFT-NdkFAyVdmhD9drg",
                    "ArtistUrl": "https://youtube.com/channel/UCqxneFT-NdkFAyVdmhD9drg",
                    "time": "2:58",
                    "second": 178
                },
                {
                    "SongTitle": "TAP",
                    "SongID": "hJ9mG_17S8s",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=hJ9mG_17S8s&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=hJ9mG_17S8s&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "SECRET NUMBER",
                    "ArtistID": "UC5Et9DRe0DEj4Jzcsr8gHYQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC5Et9DRe0DEj4Jzcsr8gHYQ",
                    "ArtistUrl": "https://youtube.com/channel/UC5Et9DRe0DEj4Jzcsr8gHYQ",
                    "time": "3:55",
                    "second": 235
                },
                {
                    "SongTitle": "EXID – ‘불이나’ MV",
                    "SongID": "WsREawZfufw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=WsREawZfufw&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=WsREawZfufw&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "EXID",
                    "ArtistID": "UCeWtP2OHP1qgd0mDXZoN8xw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCeWtP2OHP1qgd0mDXZoN8xw",
                    "ArtistUrl": "https://youtube.com/channel/UCeWtP2OHP1qgd0mDXZoN8xw",
                    "time": "3:34",
                    "second": 214
                },
                {
                    "SongTitle": "Real Love",
                    "SongID": "BWK65TVZ_tM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=BWK65TVZ_tM&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=BWK65TVZ_tM&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "Oh My Girl",
                    "ArtistID": "UCArTAXmvvTohDgCsegudy4w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCArTAXmvvTohDgCsegudy4w",
                    "ArtistUrl": "https://youtube.com/channel/UCArTAXmvvTohDgCsegudy4w",
                    "time": "3:28",
                    "second": 208
                },
                {
                    "SongTitle": "Time for the moon night",
                    "SongID": "_XyBa8QsVQU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=_XyBa8QsVQU&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=_XyBa8QsVQU&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "GFRIEND",
                    "ArtistID": "UCKrKo2mifcYmM86K_suNz2Q",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCKrKo2mifcYmM86K_suNz2Q",
                    "ArtistUrl": "https://youtube.com/channel/UCKrKo2mifcYmM86K_suNz2Q",
                    "time": "3:54",
                    "second": 234
                },
                {
                    "SongTitle": "Love Shhh!",
                    "SongID": "w2P9NT8P8qA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=w2P9NT8P8qA&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=w2P9NT8P8qA&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "JO YURI",
                    "ArtistID": "UCwiHPGVc8ysb9mhOw9HjcTA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCwiHPGVc8ysb9mhOw9HjcTA",
                    "ArtistUrl": "https://youtube.com/channel/UCwiHPGVc8ysb9mhOw9HjcTA",
                    "time": "3:28",
                    "second": 208
                },
                {
                    "SongTitle": "Last Sequence",
                    "SongID": "z0YLZmcARRU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=z0YLZmcARRU&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=z0YLZmcARRU&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "宇宙少女",
                    "ArtistID": "UC2BvuqXOqNhRmmcRAJ_l3Pg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC2BvuqXOqNhRmmcRAJ_l3Pg",
                    "ArtistUrl": "https://youtube.com/channel/UC2BvuqXOqNhRmmcRAJ_l3Pg",
                    "time": "3:12",
                    "second": 192
                },
                {
                    "SongTitle": "Rollercoaster",
                    "SongID": "KkyUE7TcBcs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=KkyUE7TcBcs&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=KkyUE7TcBcs&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "woo!ah!",
                    "ArtistID": "UCZeh-lKmAbmnVLSpXhA8zvg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCZeh-lKmAbmnVLSpXhA8zvg",
                    "ArtistUrl": "https://youtube.com/channel/UCZeh-lKmAbmnVLSpXhA8zvg",
                    "time": "3:21",
                    "second": 201
                },
                {
                    "SongTitle": "ELEVEN",
                    "SongID": "e91HyUPLaMM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=e91HyUPLaMM&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=e91HyUPLaMM&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "IVE",
                    "ArtistID": "UC_4Y1QqJr60C5Z7-eQWy-mw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC_4Y1QqJr60C5Z7-eQWy-mw",
                    "ArtistUrl": "https://youtube.com/channel/UC_4Y1QqJr60C5Z7-eQWy-mw",
                    "time": "2:59",
                    "second": 179
                },
                {
                    "SongTitle": "ASAP",
                    "SongID": "_X3r09dgbQg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=_X3r09dgbQg&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=_X3r09dgbQg&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "StayC",
                    "ArtistID": "UCwc9eSwp1MAoToS9QUTRpDw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCwc9eSwp1MAoToS9QUTRpDw",
                    "ArtistUrl": "https://youtube.com/channel/UCwc9eSwp1MAoToS9QUTRpDw",
                    "time": "3:16",
                    "second": 196
                },
                {
                    "SongTitle": "FLASH",
                    "SongID": "oAbhfMWvcZs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=oAbhfMWvcZs&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=oAbhfMWvcZs&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "Rocket Punch",
                    "ArtistID": "UCIPoDemZetmB2SFSmibrBOg",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCIPoDemZetmB2SFSmibrBOg",
                    "ArtistUrl": "https://youtube.com/channel/UCIPoDemZetmB2SFSmibrBOg",
                    "time": "3:28",
                    "second": 208
                },
                {
                    "SongTitle": "BOP BOP!",
                    "SongID": "KLF85_qHujQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=KLF85_qHujQ&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=KLF85_qHujQ&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "VIVIZ",
                    "ArtistID": "UC4FICdicYyZH0zpEzHFZpMw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC4FICdicYyZH0zpEzHFZpMw",
                    "ArtistUrl": "https://youtube.com/channel/UC4FICdicYyZH0zpEzHFZpMw",
                    "time": "3:45",
                    "second": 225
                },
                {
                    "SongTitle": "DM",
                    "SongID": "1TyYpFW8X9U",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=1TyYpFW8X9U&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=1TyYpFW8X9U&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "fromis_9",
                    "ArtistID": "UC3M9MRdZz-WWtAQos94_h6w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC3M9MRdZz-WWtAQos94_h6w",
                    "ArtistUrl": "https://youtube.com/channel/UC3M9MRdZz-WWtAQos94_h6w",
                    "time": "3:32",
                    "second": 212
                },
                {
                    "SongTitle": "CLASSY",
                    "SongID": "MTs7GNrs5_o",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=MTs7GNrs5_o&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=MTs7GNrs5_o&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "Class:y",
                    "ArtistID": "UCEHoJ5bHcJ9PVCE_Nn0dDYA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCEHoJ5bHcJ9PVCE_Nn0dDYA",
                    "ArtistUrl": "https://youtube.com/channel/UCEHoJ5bHcJ9PVCE_Nn0dDYA",
                    "time": "2:49",
                    "second": 169
                },
                {
                    "SongTitle": "NMIXX (엔믹스) - Kiss [Special Clip]",
                    "SongID": "oiSmwzPZOOo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=oiSmwzPZOOo&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=oiSmwzPZOOo&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "워너뮤직코리아 (Warner Music Korea)",
                    "ArtistID": "UCLvhr40dgoBcV4XBlOhauNw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCLvhr40dgoBcV4XBlOhauNw",
                    "ArtistUrl": "https://youtube.com/channel/UCLvhr40dgoBcV4XBlOhauNw",
                    "time": "3:10",
                    "second": 190
                },
                {
                    "SongTitle": "Better",
                    "SongID": "eH8jn4W8Bqc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=eH8jn4W8Bqc&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=eH8jn4W8Bqc&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "MAMAMOO",
                    "ArtistID": "UCC_x7uhz40eyVag5DQnWj-g",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCC_x7uhz40eyVag5DQnWj-g",
                    "ArtistUrl": "https://youtube.com/channel/UCC_x7uhz40eyVag5DQnWj-g",
                    "time": "3:30",
                    "second": 210
                },
                {
                    "SongTitle": "Sugar Rush",
                    "SongID": "-wDj4H6K-D4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=-wDj4H6K-D4&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=-wDj4H6K-D4&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "Kep1er",
                    "ArtistID": "UCAKvDuIX3m1AUdPpDSqV_3w",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCAKvDuIX3m1AUdPpDSqV_3w",
                    "ArtistUrl": "https://youtube.com/channel/UCAKvDuIX3m1AUdPpDSqV_3w",
                    "time": "3:34",
                    "second": 214
                },
                {
                    "SongTitle": "LOVEADE",
                    "SongID": "7oGRnWulYCI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=7oGRnWulYCI&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=7oGRnWulYCI&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "VIVIZ",
                    "ArtistID": "UC4FICdicYyZH0zpEzHFZpMw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC4FICdicYyZH0zpEzHFZpMw",
                    "ArtistUrl": "https://youtube.com/channel/UC4FICdicYyZH0zpEzHFZpMw",
                    "time": "3:53",
                    "second": 233
                },
                {
                    "SongTitle": "Drive",
                    "SongID": "evBrJkHZCIo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=evBrJkHZCIo&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=evBrJkHZCIo&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "趙美延",
                    "ArtistID": "UCeGET2Y4cZqEt1Fir6YzZdQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCeGET2Y4cZqEt1Fir6YzZdQ",
                    "ArtistUrl": "https://youtube.com/channel/UCeGET2Y4cZqEt1Fir6YzZdQ",
                    "time": "3:46",
                    "second": 226
                },
                {
                    "SongTitle": "프로미스나인 (fromis_9) - 달빛바다 (Sea of Moonlight) [Special Clip]",
                    "SongID": "peBkYOfFAd4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=peBkYOfFAd4&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=peBkYOfFAd4&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "워너뮤직코리아 (Warner Music Korea)",
                    "ArtistID": "UCLvhr40dgoBcV4XBlOhauNw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCLvhr40dgoBcV4XBlOhauNw",
                    "ArtistUrl": "https://youtube.com/channel/UCLvhr40dgoBcV4XBlOhauNw",
                    "time": "3:10",
                    "second": 190
                },
                {
                    "SongTitle": "Rum Pum Pum",
                    "SongID": "PJIDqwvg2yo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=PJIDqwvg2yo&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "SongUrl": "https://youtube.com/watch?v=PJIDqwvg2yo&list=RDCLAK5uy_moWU7LFrqNAVA27VvUM3Mqfs12exbf7jY",
                    "Artist": "VIVIZ",
                    "ArtistID": "UC4FICdicYyZH0zpEzHFZpMw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC4FICdicYyZH0zpEzHFZpMw",
                    "ArtistUrl": "https://youtube.com/channel/UC4FICdicYyZH0zpEzHFZpMw",
                    "time": "4:00",
                    "second": 240
                }
            ]
        }
    ]
    return { data };
});
