export default defineEventHandler((event) => {
    const data = [
        {
            "ListName": "抖音神曲",
            "SongList": [
                {
                    "SongTitle": "顧帥Gs - 絕對不會離開你『縱使相隔千萬里 也沒開口先放棄，沒抗拒 一想起 心底就泛起漣漪。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "zbzef_To_U8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=zbzef_To_U8&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=zbzef_To_U8&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "3:10",
                    "second": 190
                },
                {
                    "SongTitle": "顧帥Gs - 絕對不會離開你『縱使相隔千萬里 也沒開口先放棄，沒抗拒 一想起 心底就泛起漣漪。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "zbzef_To_U8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=zbzef_To_U8&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=zbzef_To_U8&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "3:10",
                    "second": 190
                },
                {
                    "SongTitle": "葉瓊琳 - 一個人『又回到一個人忙碌著寂寞的時候，一個人只懂往前走不回頭。』【動態歌詞MV】",
                    "SongID": "So16bb9Jdkc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=So16bb9Jdkc&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=So16bb9Jdkc&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "Mousse Music",
                    "ArtistID": "UCkyZslsGezmcoVedVArvqnw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCkyZslsGezmcoVedVArvqnw",
                    "ArtistUrl": "https://youtube.com/channel/UCkyZslsGezmcoVedVArvqnw",
                    "time": "3:31",
                    "second": 211
                },
                {
                    "SongTitle": "王理文 - 一念之差『如果我們再多一次遷就 再多一次輓留，也許就能走到最後，只怪當時太過執拗。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "bEBillhm8Bc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=bEBillhm8Bc&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=bEBillhm8Bc&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "3:43",
                    "second": 223
                },
                {
                    "SongTitle": "Zic子晨 - 我要找到你（原唱：陳明）『我要找到你 喊出你的名字，打開幸福的盒子。』【動態歌詞MV】",
                    "SongID": "z2h_4HhLn_g",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=z2h_4HhLn_g&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=z2h_4HhLn_g&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "i-Music",
                    "ArtistID": "UC_a9jB1bHxtK2gHBcMgZDqw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC_a9jB1bHxtK2gHBcMgZDqw",
                    "ArtistUrl": "https://youtube.com/channel/UC_a9jB1bHxtK2gHBcMgZDqw",
                    "time": "3:05",
                    "second": 185
                },
                {
                    "SongTitle": "王欣宇 - 告白『因為你愛上整個夏末 我開始迷上你暖暖酒窩，你和我光腳並排著坐 天南地北什麼話都說。』【動態歌詞MV】",
                    "SongID": "huTULFLeX4Y",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=huTULFLeX4Y&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=huTULFLeX4Y&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "JN Music",
                    "ArtistID": "UCGpUIgdNw1F3WgTRl4RzPcA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCGpUIgdNw1F3WgTRl4RzPcA",
                    "ArtistUrl": "https://youtube.com/channel/UCGpUIgdNw1F3WgTRl4RzPcA",
                    "time": "4:10",
                    "second": 250
                },
                {
                    "SongTitle": "戴羽彤/虎二 - 你怎麼捨得我難過（原唱：黃品源）『最愛你的人是我 你怎麼捨得我難過，對你付出了這麼多 你卻沒有感動過。』【動態歌詞MV】",
                    "SongID": "vB0ntAgLDIA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=vB0ntAgLDIA&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=vB0ntAgLDIA&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "Panda Music",
                    "ArtistID": "UC56u_5CV7XirXp2H2VwGQTQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC56u_5CV7XirXp2H2VwGQTQ",
                    "ArtistUrl": "https://youtube.com/channel/UC56u_5CV7XirXp2H2VwGQTQ",
                    "time": "4:49",
                    "second": 289
                },
                {
                    "SongTitle": "井朧 - 回到原點『我想回到原點 回到當時的歲月，只怕沒有了你 我會流淚。』【動態歌詞MV】",
                    "SongID": "d62xYRXhTos",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=d62xYRXhTos&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=d62xYRXhTos&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "MilkShake Music",
                    "ArtistID": "UC2Cma-jrZV9QV5jx8VHaHXQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC2Cma-jrZV9QV5jx8VHaHXQ",
                    "ArtistUrl": "https://youtube.com/channel/UC2Cma-jrZV9QV5jx8VHaHXQ",
                    "time": "4:21",
                    "second": 261
                },
                {
                    "SongTitle": "尚士達 - 那就晚安『或是命中註定有緣無份，才讓我機緣巧合遇見你，然後毫無準備地失去你。』【動態歌詞MV】",
                    "SongID": "QXwVldR7UyM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=QXwVldR7UyM&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=QXwVldR7UyM&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "BOMBING Music",
                    "ArtistID": "UCpnYPL8WnRPOyr1QXrA6T8A",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCpnYPL8WnRPOyr1QXrA6T8A",
                    "ArtistUrl": "https://youtube.com/channel/UCpnYPL8WnRPOyr1QXrA6T8A",
                    "time": "5:02",
                    "second": 302
                },
                {
                    "SongTitle": "BigYear大年 - 我不會再去相信你了『我真的超級愛你 是真的真的愛你，但真的抱歉這次我不能再不去在意。』【動態歌詞MV】",
                    "SongID": "jPQ1vWNX60g",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=jPQ1vWNX60g&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=jPQ1vWNX60g&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "Popper Music",
                    "ArtistID": "UCC2ewkuwKpdYcrIVYsluPdA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCC2ewkuwKpdYcrIVYsluPdA",
                    "ArtistUrl": "https://youtube.com/channel/UCC2ewkuwKpdYcrIVYsluPdA",
                    "time": "5:19",
                    "second": 319
                },
                {
                    "SongTitle": "王恩信Est、二胖u - 飛『風浪沒平息 我宣告奔跑的意義，這不是叛逆 我只是淋了一場雨。』【動態歌詞MV】",
                    "SongID": "NDSYm8X8tSc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=NDSYm8X8tSc&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=NDSYm8X8tSc&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "YunShang-Music",
                    "ArtistID": "UCrWNEmqwt4iTmqhhI7Caeyw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCrWNEmqwt4iTmqhhI7Caeyw",
                    "ArtistUrl": "https://youtube.com/channel/UCrWNEmqwt4iTmqhhI7Caeyw",
                    "time": "3:40",
                    "second": 220
                },
                {
                    "SongTitle": "龔子婕JessieG - 朋友關係『原來每段朋友關係 再見是最後的默契，原諒我曾愛你 現在已經變得多餘。』【動態歌詞MV】",
                    "SongID": "xNIjhWZkCkY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=xNIjhWZkCkY&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=xNIjhWZkCkY&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "Mousse Music",
                    "ArtistID": "UCkyZslsGezmcoVedVArvqnw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCkyZslsGezmcoVedVArvqnw",
                    "ArtistUrl": "https://youtube.com/channel/UCkyZslsGezmcoVedVArvqnw",
                    "time": "4:14",
                    "second": 254
                },
                {
                    "SongTitle": "楊胖雨/Lambert - 重來『不想要和你分開 但時間註定回不來，想你的每個凌晨 只有煙和酒在陪伴。』【動態歌詞MV】",
                    "SongID": "peXpA2YZfGQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=peXpA2YZfGQ&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=peXpA2YZfGQ&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "i-Music",
                    "ArtistID": "UC_a9jB1bHxtK2gHBcMgZDqw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC_a9jB1bHxtK2gHBcMgZDqw",
                    "ArtistUrl": "https://youtube.com/channel/UC_a9jB1bHxtK2gHBcMgZDqw",
                    "time": "2:43",
                    "second": 163
                },
                {
                    "SongTitle": "王小帥 - 給昨天的自己『我應該灑脫 愛過恨過都屬於昨天那個我，當看見眼淚和我一起笑著明天要開始了』【動態歌詞MV】",
                    "SongID": "y0iX97mYV-k",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=y0iX97mYV-k&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=y0iX97mYV-k&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "JN Music",
                    "ArtistID": "UCGpUIgdNw1F3WgTRl4RzPcA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCGpUIgdNw1F3WgTRl4RzPcA",
                    "ArtistUrl": "https://youtube.com/channel/UCGpUIgdNw1F3WgTRl4RzPcA",
                    "time": "4:09",
                    "second": 249
                },
                {
                    "SongTitle": "劉思鑒 - 晝夜船『我給不了你要的偏愛，也曾想過跳下那天台，卻忘不掉那校門口的路牌。』【動態歌詞MV】",
                    "SongID": "Inlz4ftiEDs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Inlz4ftiEDs&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=Inlz4ftiEDs&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "MilkShake Music",
                    "ArtistID": "UC2Cma-jrZV9QV5jx8VHaHXQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC2Cma-jrZV9QV5jx8VHaHXQ",
                    "ArtistUrl": "https://youtube.com/channel/UC2Cma-jrZV9QV5jx8VHaHXQ",
                    "time": "4:07",
                    "second": 247
                },
                {
                    "SongTitle": "馮提莫 - 世間美好與你環環相扣（原唱：柏松）『此刻已皓月當空 愛的人手捧星光，我知他乘風破浪 去了黑暗一趟，感同身受 給你救贖熱望。』【動態歌詞MV】",
                    "SongID": "iecKlVwk0pA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=iecKlVwk0pA&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=iecKlVwk0pA&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "SOUL. MUSIC",
                    "ArtistID": "UC4E2adU04_ST8N1os77KAxQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC4E2adU04_ST8N1os77KAxQ",
                    "ArtistUrl": "https://youtube.com/channel/UC4E2adU04_ST8N1os77KAxQ",
                    "time": "3:53",
                    "second": 233
                },
                {
                    "SongTitle": "Joysaaaa - 忘不掉的星『忘不掉的人像是星星，到了晚上才顯得特別清晰，也許是我對你還談不上多了解。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "O6YIm9YtI4w",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=O6YIm9YtI4w&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=O6YIm9YtI4w&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "4:20",
                    "second": 260
                },
                {
                    "SongTitle": "羅雲熙 - 逆流而上『再逆流而上 最遠的旅行，我一定是你 最大的勇氣。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "PdSOe6Tvphs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=PdSOe6Tvphs&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=PdSOe6Tvphs&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "4:37",
                    "second": 277
                },
                {
                    "SongTitle": "你的二智bb - 不等了『就這樣一天兩天三天四天想你好多遍，可怎麼不能回到從前。』【動態歌詞MV】",
                    "SongID": "JHyg3HlsPRY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=JHyg3HlsPRY&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=JHyg3HlsPRY&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "Panda Music",
                    "ArtistID": "UC56u_5CV7XirXp2H2VwGQTQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC56u_5CV7XirXp2H2VwGQTQ",
                    "ArtistUrl": "https://youtube.com/channel/UC56u_5CV7XirXp2H2VwGQTQ",
                    "time": "3:55",
                    "second": 235
                },
                {
                    "SongTitle": "顏人中 - 有可能的夜晚（原唱：曾軼可）『讓蠟燭代替所有燈，讓音樂代替話語聲，此時無聲勝有聲。』【動態歌詞MV】",
                    "SongID": "OeTwMBCMY5c",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=OeTwMBCMY5c&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=OeTwMBCMY5c&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "BLUE MUSIC",
                    "ArtistID": "UCpR5JmRWGixoWEUQNVu-ImA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCpR5JmRWGixoWEUQNVu-ImA",
                    "ArtistUrl": "https://youtube.com/channel/UCpR5JmRWGixoWEUQNVu-ImA",
                    "time": "4:37",
                    "second": 277
                },
                {
                    "SongTitle": "劉宇寧 - 昨日少年(電影《企鵝公路》少年版中文主題曲)『我知道 成長總會有很多妥協，但在心中 仍舊住著驕傲的少年。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "qLkyrIfVHyQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=qLkyrIfVHyQ&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=qLkyrIfVHyQ&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "4:10",
                    "second": 250
                },
                {
                    "SongTitle": "張赫宣 - 風的味道（電視劇《海上繁花》插曲）『風吹落了樹葉 你的話還在耳邊，當我學會了愛 你卻已經離開。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "CpuqJcI9iag",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=CpuqJcI9iag&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=CpuqJcI9iag&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "4:18",
                    "second": 258
                },
                {
                    "SongTitle": "楊胖雨/十七草 - 喜歡你這件事『喜歡你這件事每天溫習幾遍，有你的昨天今天明天都是晴天。』【動態歌詞MV】",
                    "SongID": "DJuioVWOy_U",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=DJuioVWOy_U&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=DJuioVWOy_U&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "Popper Music",
                    "ArtistID": "UCC2ewkuwKpdYcrIVYsluPdA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCC2ewkuwKpdYcrIVYsluPdA",
                    "ArtistUrl": "https://youtube.com/channel/UCC2ewkuwKpdYcrIVYsluPdA",
                    "time": "2:53",
                    "second": 173
                },
                {
                    "SongTitle": "尚士達 - 迷人的危險（原唱：Dance flow）『為什麼最迷人的最危險，為什麼愛會讓人變殘缺。』【動態歌詞MV】",
                    "SongID": "HQKORmk_7ms",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=HQKORmk_7ms&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=HQKORmk_7ms&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "YunShang-Music",
                    "ArtistID": "UCrWNEmqwt4iTmqhhI7Caeyw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCrWNEmqwt4iTmqhhI7Caeyw",
                    "ArtistUrl": "https://youtube.com/channel/UCrWNEmqwt4iTmqhhI7Caeyw",
                    "time": "4:03",
                    "second": 243
                },
                {
                    "SongTitle": "陳壹千 - 比你更愛我的人『也許會有很多比我還要痛的人 一邊哭一邊揭開傷痕，在歌裡找心疼才算一種安慰。』【動態歌詞MV】",
                    "SongID": "31XrwcuaEmo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=31XrwcuaEmo&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=31XrwcuaEmo&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "BOMBING Music",
                    "ArtistID": "UCpnYPL8WnRPOyr1QXrA6T8A",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCpnYPL8WnRPOyr1QXrA6T8A",
                    "ArtistUrl": "https://youtube.com/channel/UCpnYPL8WnRPOyr1QXrA6T8A",
                    "time": "4:22",
                    "second": 262
                },
                {
                    "SongTitle": "G2er/黃詩扶 - 楊花落盡子規啼『楊花落盡子規啼 聞道龍標過五溪，我寄愁心與明月 隨風直到夜郎西。』【動態歌詞MV】",
                    "SongID": "0NsE5Fhe1ZA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=0NsE5Fhe1ZA&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=0NsE5Fhe1ZA&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "i-Music",
                    "ArtistID": "UC_a9jB1bHxtK2gHBcMgZDqw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC_a9jB1bHxtK2gHBcMgZDqw",
                    "ArtistUrl": "https://youtube.com/channel/UC_a9jB1bHxtK2gHBcMgZDqw",
                    "time": "3:46",
                    "second": 226
                },
                {
                    "SongTitle": "夏婉安 - 可有可無的人『原來我只是一個他可有可無的人，可笑我還為他放棄了所有的人。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "rdp6EB1N-nA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=rdp6EB1N-nA&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=rdp6EB1N-nA&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "3:54",
                    "second": 234
                },
                {
                    "SongTitle": "你的二智bb - 這一生關於你的風景（原唱：枯木逢春）『我多想能多陪你一場，把前半生的風景對你講。』【動態歌詞MV】",
                    "SongID": "xiQ5xWZRCoU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=xiQ5xWZRCoU&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=xiQ5xWZRCoU&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "JN Music",
                    "ArtistID": "UCGpUIgdNw1F3WgTRl4RzPcA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCGpUIgdNw1F3WgTRl4RzPcA",
                    "ArtistUrl": "https://youtube.com/channel/UCGpUIgdNw1F3WgTRl4RzPcA",
                    "time": "4:39",
                    "second": 279
                },
                {
                    "SongTitle": "戴羽彤 - 那女孩對我說（原唱：黃義達）『那女孩對我說 說我保護她的夢，說這個世界 對她這樣的不多。』【動態歌詞MV】",
                    "SongID": "SM-2yHYtYSY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=SM-2yHYtYSY&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=SM-2yHYtYSY&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "SOUL. MUSIC",
                    "ArtistID": "UC4E2adU04_ST8N1os77KAxQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC4E2adU04_ST8N1os77KAxQ",
                    "ArtistUrl": "https://youtube.com/channel/UC4E2adU04_ST8N1os77KAxQ",
                    "time": "5:04",
                    "second": 304
                },
                {
                    "SongTitle": "木小雅 - 可能否『可能我撞了南墻才會回頭吧，可能我見了黃河才會死心吧。』【動態歌詞MV】",
                    "SongID": "o-91onq2Zx8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=o-91onq2Zx8&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=o-91onq2Zx8&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "MilkShake Music",
                    "ArtistID": "UC2Cma-jrZV9QV5jx8VHaHXQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC2Cma-jrZV9QV5jx8VHaHXQ",
                    "ArtistUrl": "https://youtube.com/channel/UC2Cma-jrZV9QV5jx8VHaHXQ",
                    "time": "3:48",
                    "second": 228
                },
                {
                    "SongTitle": "王貳浪 - 往後餘生（原唱：馬良）『想帶你去看晴空萬里，想大聲告訴你我為你著迷，往後的餘生 我只要你。』【動態歌詞MV】",
                    "SongID": "JUsvbW6s6hI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=JUsvbW6s6hI&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=JUsvbW6s6hI&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "Panda Music",
                    "ArtistID": "UC56u_5CV7XirXp2H2VwGQTQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC56u_5CV7XirXp2H2VwGQTQ",
                    "ArtistUrl": "https://youtube.com/channel/UC56u_5CV7XirXp2H2VwGQTQ",
                    "time": "3:52",
                    "second": 232
                },
                {
                    "SongTitle": "金海心 - 反方向流浪（青春暗戀劇《上游》主題推廣曲）『我只好假裝去說謊 去流浪 很幸福的模樣，那窗外的雪就陪著我想。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "WIbYti2psrA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=WIbYti2psrA&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=WIbYti2psrA&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "4:11",
                    "second": 251
                },
                {
                    "SongTitle": "丫蛋蛋 - 大田後生仔（原唱：林啟得）『做人一輩子 快樂沒幾天，一條大路分兩邊 隨你要走哪一邊。』【動態歌詞MV】",
                    "SongID": "ky6TWIhL7FI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ky6TWIhL7FI&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=ky6TWIhL7FI&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "BLUE MUSIC",
                    "ArtistID": "UCpR5JmRWGixoWEUQNVu-ImA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCpR5JmRWGixoWEUQNVu-ImA",
                    "ArtistUrl": "https://youtube.com/channel/UCpR5JmRWGixoWEUQNVu-ImA",
                    "time": "3:03",
                    "second": 183
                },
                {
                    "SongTitle": "陳冰 - 有些話只有聽的人記得（電視劇《海上繁花》插曲）『你說的那些話只有聽過的人記得，被時間碾過才會更深刻。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "-TP4PVIKN-Q",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=-TP4PVIKN-Q&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=-TP4PVIKN-Q&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "4:23",
                    "second": 263
                },
                {
                    "SongTitle": "喻言家 - 是想你的聲音啊（DJ版）『你快聽 滴答滴 滴答滴 滴答滴 是雨滴的聲音，你快聽 是我在 是我在 是我在哼你最愛聽的旋律。』【動態歌詞MV】",
                    "SongID": "yZVNrZynfhM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=yZVNrZynfhM&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=yZVNrZynfhM&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "Mousse Music",
                    "ArtistID": "UCkyZslsGezmcoVedVArvqnw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCkyZslsGezmcoVedVArvqnw",
                    "ArtistUrl": "https://youtube.com/channel/UCkyZslsGezmcoVedVArvqnw",
                    "time": "2:34",
                    "second": 154
                },
                {
                    "SongTitle": "花粥 - 紙短情長『我真的好想你 在每一個雨季，你選擇遺忘的 是我最不捨的，我的故事都是關於你呀。』【動態歌詞MV】",
                    "SongID": "YJDt1rSFCms",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=YJDt1rSFCms&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=YJDt1rSFCms&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "BOMBING Music",
                    "ArtistID": "UCpnYPL8WnRPOyr1QXrA6T8A",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCpnYPL8WnRPOyr1QXrA6T8A",
                    "ArtistUrl": "https://youtube.com/channel/UCpnYPL8WnRPOyr1QXrA6T8A",
                    "time": "3:07",
                    "second": 187
                },
                {
                    "SongTitle": "小潘潘（潘柚彤）- 甜狗『不刷牙就別親親 雖然很想被你親醒，電影裡的劇情不切實際 但我不想拆穿你。』【動態歌詞MV】",
                    "SongID": "w1EfCqWD0Vc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=w1EfCqWD0Vc&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=w1EfCqWD0Vc&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "Popper Music",
                    "ArtistID": "UCC2ewkuwKpdYcrIVYsluPdA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCC2ewkuwKpdYcrIVYsluPdA",
                    "ArtistUrl": "https://youtube.com/channel/UCC2ewkuwKpdYcrIVYsluPdA",
                    "time": "3:22",
                    "second": 202
                },
                {
                    "SongTitle": "杜宣達 - 月光總會落在你身上『沒人知道未來會怎樣，對的人不該用錯過收場，就像月光總會落在你身上。』【動態歌詞MV】",
                    "SongID": "nO9lkai3adY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=nO9lkai3adY&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=nO9lkai3adY&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "YunShang-Music",
                    "ArtistID": "UCrWNEmqwt4iTmqhhI7Caeyw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCrWNEmqwt4iTmqhhI7Caeyw",
                    "ArtistUrl": "https://youtube.com/channel/UCrWNEmqwt4iTmqhhI7Caeyw",
                    "time": "2:30",
                    "second": 150
                },
                {
                    "SongTitle": "藍心羽 - 虛情假意『從開始相遇 是緣分的一臂之力，默默付出真心 卻換不來我愛你。』【動態歌詞MV】",
                    "SongID": "DXQrAyUinYw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=DXQrAyUinYw&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=DXQrAyUinYw&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "i-Music",
                    "ArtistID": "UC_a9jB1bHxtK2gHBcMgZDqw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC_a9jB1bHxtK2gHBcMgZDqw",
                    "ArtistUrl": "https://youtube.com/channel/UC_a9jB1bHxtK2gHBcMgZDqw",
                    "time": "3:09",
                    "second": 189
                },
                {
                    "SongTitle": "鄭潤澤 - 雨天（男聲版）『你能體諒 我有雨天，偶爾膽怯 你都了解，過去那些大雨落下的瞬間 我突然發現。』【動態歌詞MV】",
                    "SongID": "4lFUgEVCSXA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=4lFUgEVCSXA&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=4lFUgEVCSXA&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "JN Music",
                    "ArtistID": "UCGpUIgdNw1F3WgTRl4RzPcA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCGpUIgdNw1F3WgTRl4RzPcA",
                    "ArtistUrl": "https://youtube.com/channel/UCGpUIgdNw1F3WgTRl4RzPcA",
                    "time": "3:01",
                    "second": 181
                },
                {
                    "SongTitle": "1個球 - 咱們結婚吧『哦My Love 咱們結婚吧，好想和你擁有一個家。』【動態歌詞MV】",
                    "SongID": "WZrwKIow-ZY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=WZrwKIow-ZY&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=WZrwKIow-ZY&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "SOUL. MUSIC",
                    "ArtistID": "UC4E2adU04_ST8N1os77KAxQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC4E2adU04_ST8N1os77KAxQ",
                    "ArtistUrl": "https://youtube.com/channel/UC4E2adU04_ST8N1os77KAxQ",
                    "time": "2:52",
                    "second": 172
                },
                {
                    "SongTitle": "劉大拿/劉思達LOFTHESTAR - 我愛你（原唱：盧廣仲）『曾經在我眼前 卻又消失不見，這是今天的第六遍。』【動態歌詞MV】",
                    "SongID": "AiyrlIlvij0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=AiyrlIlvij0&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=AiyrlIlvij0&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "MilkShake Music",
                    "ArtistID": "UC2Cma-jrZV9QV5jx8VHaHXQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC2Cma-jrZV9QV5jx8VHaHXQ",
                    "ArtistUrl": "https://youtube.com/channel/UC2Cma-jrZV9QV5jx8VHaHXQ",
                    "time": "2:59",
                    "second": 179
                },
                {
                    "SongTitle": "劉惜君 - 荒丘(《不完美受害人》電視劇插曲)『同在迷途漂泊人海中，心在流浪追尋愛與夢。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "MGwFrjzUrEY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=MGwFrjzUrEY&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=MGwFrjzUrEY&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "3:29",
                    "second": 209
                },
                {
                    "SongTitle": "印子月 - 習慣彼此習慣『卸下偽裝 原來我們也都會害怕孤單，固執建立在習慣彼此習慣。』【動態歌詞MV】",
                    "SongID": "PlAcZt6rzRs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=PlAcZt6rzRs&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=PlAcZt6rzRs&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "Panda Music",
                    "ArtistID": "UC56u_5CV7XirXp2H2VwGQTQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC56u_5CV7XirXp2H2VwGQTQ",
                    "ArtistUrl": "https://youtube.com/channel/UC56u_5CV7XirXp2H2VwGQTQ",
                    "time": "4:03",
                    "second": 243
                },
                {
                    "SongTitle": "刀郎 - 羅剎海市『她兩耳傍肩三孔鼻 未曾開言先轉腚，每一日蹲窩裡把蛋來臥。』【動態歌詞MV】",
                    "SongID": "ik02YxJ_FBA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=ik02YxJ_FBA&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=ik02YxJ_FBA&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "BLUE MUSIC",
                    "ArtistID": "UCpR5JmRWGixoWEUQNVu-ImA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCpR5JmRWGixoWEUQNVu-ImA",
                    "ArtistUrl": "https://youtube.com/channel/UCpR5JmRWGixoWEUQNVu-ImA",
                    "time": "5:33",
                    "second": 333
                },
                {
                    "SongTitle": "郁可唯 - 我知道 (《不完美受害人》電視劇主題曲) 『那些命運的考驗 留下懸念，按自己的心願 過今天。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "MvpmksY61j8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=MvpmksY61j8&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=MvpmksY61j8&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "3:08",
                    "second": 188
                },
                {
                    "SongTitle": "隔壁老樊 - 你我不一『我從來沒想過過多好 卻也沒想過那麼糟，原來真的是世事難預料。』【動態歌詞MV】",
                    "SongID": "okt0699Wn8o",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=okt0699Wn8o&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=okt0699Wn8o&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "SEEK Music Studio",
                    "ArtistID": "UCMge6Qofn2CIEk8yXpL5pWQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCMge6Qofn2CIEk8yXpL5pWQ",
                    "ArtistUrl": "https://youtube.com/channel/UCMge6Qofn2CIEk8yXpL5pWQ",
                    "time": "3:56",
                    "second": 236
                },
                {
                    "SongTitle": "井朧 - 丟了你『我總在每一個黑夜想你，嘲笑自己傻得可以，沒懂得珍惜 那麼輕易丟了你。』【動態歌詞MV】",
                    "SongID": "mg0-kV0PKWs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=mg0-kV0PKWs&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=mg0-kV0PKWs&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "Popper Music",
                    "ArtistID": "UCC2ewkuwKpdYcrIVYsluPdA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCC2ewkuwKpdYcrIVYsluPdA",
                    "ArtistUrl": "https://youtube.com/channel/UCC2ewkuwKpdYcrIVYsluPdA",
                    "time": "4:38",
                    "second": 278
                },
                {
                    "SongTitle": "彭宇昕Chloe - 滿分距離『可我始終只能混跡在人海裡，始終不敢越界說句我愛你，保持著你說過的滿分距離。』【動態歌詞MV】",
                    "SongID": "c4rASaK_mP0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=c4rASaK_mP0&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=c4rASaK_mP0&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "BOMBING Music",
                    "ArtistID": "UCpnYPL8WnRPOyr1QXrA6T8A",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCpnYPL8WnRPOyr1QXrA6T8A",
                    "ArtistUrl": "https://youtube.com/channel/UCpnYPL8WnRPOyr1QXrA6T8A",
                    "time": "4:11",
                    "second": 251
                },
                {
                    "SongTitle": "盧盧快閉嘴/劉思達LOFTHESTAR - 猜不透（說唱版）『如果忽遠忽近的灑脫 是你要的自由，那我寧願回到一個人生活。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "JuamLXmE1C8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=JuamLXmE1C8&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=JuamLXmE1C8&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "3:28",
                    "second": 208
                },
                {
                    "SongTitle": "二胖u - 我走就是了『你別皺眉了 我走就是了，快樂是你的 與我無關了。』【動態歌詞MV】",
                    "SongID": "2zapaG9SyCY",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=2zapaG9SyCY&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=2zapaG9SyCY&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "Mousse Music",
                    "ArtistID": "UCkyZslsGezmcoVedVArvqnw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCkyZslsGezmcoVedVArvqnw",
                    "ArtistUrl": "https://youtube.com/channel/UCkyZslsGezmcoVedVArvqnw",
                    "time": "3:07",
                    "second": 187
                },
                {
                    "SongTitle": "徐真真/呂口口 - 再也不願見你（愛如潮水）『我再也不願見你在深夜裡買醉，不願別的男人見識你的嫵媚。』【動態歌詞MV】",
                    "SongID": "W_NG-sIWdQQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=W_NG-sIWdQQ&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=W_NG-sIWdQQ&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "YunShang-Music",
                    "ArtistID": "UCrWNEmqwt4iTmqhhI7Caeyw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCrWNEmqwt4iTmqhhI7Caeyw",
                    "ArtistUrl": "https://youtube.com/channel/UCrWNEmqwt4iTmqhhI7Caeyw",
                    "time": "3:58",
                    "second": 238
                },
                {
                    "SongTitle": "顏人中 - 晚安『幾人份的暢談 道三兩句晚安，惹多情的遐想 卻輕易地走散。』【動態歌詞MV】",
                    "SongID": "kfZZyIPpZk0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=kfZZyIPpZk0&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=kfZZyIPpZk0&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "i-Music",
                    "ArtistID": "UC_a9jB1bHxtK2gHBcMgZDqw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC_a9jB1bHxtK2gHBcMgZDqw",
                    "ArtistUrl": "https://youtube.com/channel/UC_a9jB1bHxtK2gHBcMgZDqw",
                    "time": "4:50",
                    "second": 290
                },
                {
                    "SongTitle": "阿涵 - 過客『你只是一個過客 從我的世界路過，我不敢太多不捨 怕你看出我難過。』【動態歌詞MV】",
                    "SongID": "CNN-OIx5Hp0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=CNN-OIx5Hp0&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=CNN-OIx5Hp0&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "SEEK Music Studio",
                    "ArtistID": "UCMge6Qofn2CIEk8yXpL5pWQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCMge6Qofn2CIEk8yXpL5pWQ",
                    "ArtistUrl": "https://youtube.com/channel/UCMge6Qofn2CIEk8yXpL5pWQ",
                    "time": "4:30",
                    "second": 270
                },
                {
                    "SongTitle": "九姨太 - 替我愛你『希望她能替我 給你要的快樂，而我身為過客 擁有的已經很多。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "LWbqYE3pwbo",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=LWbqYE3pwbo&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=LWbqYE3pwbo&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "3:50",
                    "second": 230
                },
                {
                    "SongTitle": "刀郎 - 羅剎海市『她兩耳傍肩三孔鼻 未曾開言先轉腚，每一日蹲窩裡把蛋來臥。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "6dwMnKzSv8c",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=6dwMnKzSv8c&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=6dwMnKzSv8c&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "5:33",
                    "second": 333
                },
                {
                    "SongTitle": "Ycccc - 何期『將軍笑 用一生戎馬換幾州盛世，卻換不回歸期 為她斬相思。』【動態歌詞MV】",
                    "SongID": "NpUD0Blbtqs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=NpUD0Blbtqs&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=NpUD0Blbtqs&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "SOUL. MUSIC",
                    "ArtistID": "UC4E2adU04_ST8N1os77KAxQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC4E2adU04_ST8N1os77KAxQ",
                    "ArtistUrl": "https://youtube.com/channel/UC4E2adU04_ST8N1os77KAxQ",
                    "time": "3:42",
                    "second": 222
                },
                {
                    "SongTitle": "GG啵！ - 一分鐘戀人『和你做個一分鐘戀人 尋求一分鐘安穩，一分鐘之後 想再多一次擁吻。』【動態歌詞MV】",
                    "SongID": "H2EBnzhGHgI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=H2EBnzhGHgI&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=H2EBnzhGHgI&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "MilkShake Music",
                    "ArtistID": "UC2Cma-jrZV9QV5jx8VHaHXQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC2Cma-jrZV9QV5jx8VHaHXQ",
                    "ArtistUrl": "https://youtube.com/channel/UC2Cma-jrZV9QV5jx8VHaHXQ",
                    "time": "3:59",
                    "second": 239
                },
                {
                    "SongTitle": "王巨星 - 太陽（原唱：邱振哲）『我只想做你的太陽 你的太陽，在你的心裡呀 在你的心底呀。』【動態歌詞MV】",
                    "SongID": "V5cDATJMb1U",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=V5cDATJMb1U&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=V5cDATJMb1U&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "Panda Music",
                    "ArtistID": "UC56u_5CV7XirXp2H2VwGQTQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC56u_5CV7XirXp2H2VwGQTQ",
                    "ArtistUrl": "https://youtube.com/channel/UC56u_5CV7XirXp2H2VwGQTQ",
                    "time": "4:32",
                    "second": 272
                },
                {
                    "SongTitle": "盧盧快閉嘴 - 等到世界顛倒（原唱：王小帥）『等到世界顛倒你會來愛我，等到五個季節我才最獨特。』【動態歌詞MV】",
                    "SongID": "Y34oT_chtfE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Y34oT_chtfE&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=Y34oT_chtfE&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "BLUE MUSIC",
                    "ArtistID": "UCpR5JmRWGixoWEUQNVu-ImA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCpR5JmRWGixoWEUQNVu-ImA",
                    "ArtistUrl": "https://youtube.com/channel/UCpR5JmRWGixoWEUQNVu-ImA",
                    "time": "4:22",
                    "second": 262
                },
                {
                    "SongTitle": "怪阿姨 - 權衡利弊的選擇『我是你權衡利弊放棄的人 也是你二選一被拋棄的人，我是你有空才會想起的人 也是你讚許的好人。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "pYpnQfx85Fg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=pYpnQfx85Fg&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=pYpnQfx85Fg&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "3:35",
                    "second": 215
                },
                {
                    "SongTitle": "Aioz - 22秒『你二十二秒的語音我收藏了三年，每當我喝醉時候頭腦短了路 斷了片 卻還硬撐著惦念。』【動態歌詞MV】",
                    "SongID": "_O6jJRj2fY8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=_O6jJRj2fY8&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=_O6jJRj2fY8&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "SEEK Music Studio",
                    "ArtistID": "UCMge6Qofn2CIEk8yXpL5pWQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCMge6Qofn2CIEk8yXpL5pWQ",
                    "ArtistUrl": "https://youtube.com/channel/UCMge6Qofn2CIEk8yXpL5pWQ",
                    "time": "2:52",
                    "second": 172
                },
                {
                    "SongTitle": "王小草 - 下雨天（想念版）（原唱：南拳媽媽）『怎樣的雨 怎樣的夜，怎樣的我能讓你更想念。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "8e6dwQBpRZU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=8e6dwQBpRZU&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=8e6dwQBpRZU&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "3:52",
                    "second": 232
                },
                {
                    "SongTitle": "易自豪 - 敏感『麻木自己的敏感 學會妥協找答案，只是我如何能夠找回這走丟的一半。』【動態歌詞MV】",
                    "SongID": "Y1VZ8JVo1WQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Y1VZ8JVo1WQ&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=Y1VZ8JVo1WQ&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "YunShang-Music",
                    "ArtistID": "UCrWNEmqwt4iTmqhhI7Caeyw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCrWNEmqwt4iTmqhhI7Caeyw",
                    "ArtistUrl": "https://youtube.com/channel/UCrWNEmqwt4iTmqhhI7Caeyw",
                    "time": "3:31",
                    "second": 211
                },
                {
                    "SongTitle": "于冬然 - 聽說你『聽說你輕描淡寫 安慰她說從來沒愛過我，堅如礁石的承諾 也逃不過潮汐裡沉沒。』【動態歌詞MV】",
                    "SongID": "soY7_qh4QcE",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=soY7_qh4QcE&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=soY7_qh4QcE&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "Mousse Music",
                    "ArtistID": "UCkyZslsGezmcoVedVArvqnw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCkyZslsGezmcoVedVArvqnw",
                    "ArtistUrl": "https://youtube.com/channel/UCkyZslsGezmcoVedVArvqnw",
                    "time": "4:00",
                    "second": 240
                },
                {
                    "SongTitle": "王理文 - 愛而不得『愛情裡有一種遺憾叫作愛而不得，有一種放手叫作棄而不捨。』【動態歌詞MV】",
                    "SongID": "AvSjFlw8Qso",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=AvSjFlw8Qso&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=AvSjFlw8Qso&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "i-Music",
                    "ArtistID": "UC_a9jB1bHxtK2gHBcMgZDqw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC_a9jB1bHxtK2gHBcMgZDqw",
                    "ArtistUrl": "https://youtube.com/channel/UC_a9jB1bHxtK2gHBcMgZDqw",
                    "time": "3:43",
                    "second": 223
                },
                {
                    "SongTitle": "劉大拿 - Letting Go（原唱：蔡健雅）『我終於捨得為你放開手，因為愛你愛到我心痛 但你卻不懂。』【動態歌詞MV】",
                    "SongID": "Z-XFDDV37j0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Z-XFDDV37j0&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=Z-XFDDV37j0&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "SOUL. MUSIC",
                    "ArtistID": "UC4E2adU04_ST8N1os77KAxQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC4E2adU04_ST8N1os77KAxQ",
                    "ArtistUrl": "https://youtube.com/channel/UC4E2adU04_ST8N1os77KAxQ",
                    "time": "4:07",
                    "second": 247
                },
                {
                    "SongTitle": "王天戈 - 心安理得『如果說是我太過遷就所以淪為愛囚，活該我獨自承受獨自寂寞轉身懷舊。』【動態歌詞MV】",
                    "SongID": "JqIl83VrSVI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=JqIl83VrSVI&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=JqIl83VrSVI&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "MilkShake Music",
                    "ArtistID": "UC2Cma-jrZV9QV5jx8VHaHXQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC2Cma-jrZV9QV5jx8VHaHXQ",
                    "ArtistUrl": "https://youtube.com/channel/UC2Cma-jrZV9QV5jx8VHaHXQ",
                    "time": "4:30",
                    "second": 270
                },
                {
                    "SongTitle": "隊長 - 予你『當你握住我的手 我擁有一整個宇宙，而你是星光照亮 只有你是我的解藥。』【動態歌詞MV】",
                    "SongID": "5IVpro0SNDI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=5IVpro0SNDI&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=5IVpro0SNDI&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "JN Music",
                    "ArtistID": "UCGpUIgdNw1F3WgTRl4RzPcA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCGpUIgdNw1F3WgTRl4RzPcA",
                    "ArtistUrl": "https://youtube.com/channel/UCGpUIgdNw1F3WgTRl4RzPcA",
                    "time": "3:52",
                    "second": 232
                },
                {
                    "SongTitle": "辛雯 - 失約的你『我們呀 穿過人海喧嘩 卻散在朝夕相處的樓下，愛與不愛的反差 痛苦被放大。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "WAiZGuuzy6A",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=WAiZGuuzy6A&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=WAiZGuuzy6A&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "4:23",
                    "second": 263
                },
                {
                    "SongTitle": "煙(許佳豪) - 刪了吧『要不你還是把我刪了吧，我咬緊牙關命令我發出這句話。』【動態歌詞MV】",
                    "SongID": "VNGXsf7sywU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=VNGXsf7sywU&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=VNGXsf7sywU&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "Panda Music",
                    "ArtistID": "UC56u_5CV7XirXp2H2VwGQTQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC56u_5CV7XirXp2H2VwGQTQ",
                    "ArtistUrl": "https://youtube.com/channel/UC56u_5CV7XirXp2H2VwGQTQ",
                    "time": "3:26",
                    "second": 206
                },
                {
                    "SongTitle": "徐薇 - 遠方不遠『我們讓時間推著走了好遠，若時間能退回到單純的少年，多幸運此生能有你 遠方的你。』【動態歌詞MV】",
                    "SongID": "agmCdjY62aM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=agmCdjY62aM&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=agmCdjY62aM&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "BLUE MUSIC",
                    "ArtistID": "UCpR5JmRWGixoWEUQNVu-ImA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCpR5JmRWGixoWEUQNVu-ImA",
                    "ArtistUrl": "https://youtube.com/channel/UCpR5JmRWGixoWEUQNVu-ImA",
                    "time": "4:24",
                    "second": 264
                },
                {
                    "SongTitle": "傲七爺 - 日落的600秒『在日落的600秒裡想起你 可你在哪裡，我尋遍山川萬里人海四季 找不到你蹤跡。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "jAoDVWsPKH0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=jAoDVWsPKH0&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=jAoDVWsPKH0&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "3:53",
                    "second": 233
                },
                {
                    "SongTitle": "藍心羽 - 寂寞煙火『我曾經走過多遙遠的路 跨越過多少海洋去看你，孤單的黑夜途中 只要想著你，我就不會惶恐。』【動態歌詞MV】",
                    "SongID": "qJqHKTaF7HI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=qJqHKTaF7HI&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=qJqHKTaF7HI&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "SEEK Music Studio",
                    "ArtistID": "UCMge6Qofn2CIEk8yXpL5pWQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCMge6Qofn2CIEk8yXpL5pWQ",
                    "ArtistUrl": "https://youtube.com/channel/UCMge6Qofn2CIEk8yXpL5pWQ",
                    "time": "4:13",
                    "second": 253
                },
                {
                    "SongTitle": "林小珂 - 美人畫卷（原唱：聞人聽書_）『青山常伴綠水 燕雀已是南飛，美人畫卷殘留一絲青灰嘆余美。』【動態歌詞MV】",
                    "SongID": "Fwv_WF-bksU",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Fwv_WF-bksU&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=Fwv_WF-bksU&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "i-Music",
                    "ArtistID": "UC_a9jB1bHxtK2gHBcMgZDqw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC_a9jB1bHxtK2gHBcMgZDqw",
                    "ArtistUrl": "https://youtube.com/channel/UC_a9jB1bHxtK2gHBcMgZDqw",
                    "time": "3:05",
                    "second": 185
                },
                {
                    "SongTitle": "是二智呀 - 赤伶（原唱：HITA）『台下人走過 不見舊顏色，台上人唱著 心碎離別歌。』【動態歌詞MV】",
                    "SongID": "9PNlJrzI_rM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=9PNlJrzI_rM&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=9PNlJrzI_rM&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "SOUL. MUSIC",
                    "ArtistID": "UC4E2adU04_ST8N1os77KAxQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC4E2adU04_ST8N1os77KAxQ",
                    "ArtistUrl": "https://youtube.com/channel/UC4E2adU04_ST8N1os77KAxQ",
                    "time": "4:26",
                    "second": 266
                },
                {
                    "SongTitle": "我是張怡啊 - 吻得太逼真（原唱：張敬軒）『和你吻吻吻吻吻 你吻得太逼真，讓我把虛情假意當作最真心的親吻。』【動態歌詞MV】",
                    "SongID": "mwEQ1OfcJIw",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=mwEQ1OfcJIw&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=mwEQ1OfcJIw&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "MilkShake Music",
                    "ArtistID": "UC2Cma-jrZV9QV5jx8VHaHXQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC2Cma-jrZV9QV5jx8VHaHXQ",
                    "ArtistUrl": "https://youtube.com/channel/UC2Cma-jrZV9QV5jx8VHaHXQ",
                    "time": "3:51",
                    "second": 231
                },
                {
                    "SongTitle": "王澤科 - 念你時說晚安（原唱：高泰宇）『我多麼多麼用力的 最後一次放開你的手，冰冷的顫抖 微弱卻沉重。』【動態歌詞MV】",
                    "SongID": "zGNJD_hzT1E",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=zGNJD_hzT1E&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=zGNJD_hzT1E&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "Panda Music",
                    "ArtistID": "UC56u_5CV7XirXp2H2VwGQTQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC56u_5CV7XirXp2H2VwGQTQ",
                    "ArtistUrl": "https://youtube.com/channel/UC56u_5CV7XirXp2H2VwGQTQ",
                    "time": "4:41",
                    "second": 281
                },
                {
                    "SongTitle": "胡66 - 看破『看過了太多分分合合 沒有幾個能懂得把握，最初的相守最後都變成過客。』【動態歌詞MV】",
                    "SongID": "cu3-Y9_IK9c",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=cu3-Y9_IK9c&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=cu3-Y9_IK9c&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "BLUE MUSIC",
                    "ArtistID": "UCpR5JmRWGixoWEUQNVu-ImA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCpR5JmRWGixoWEUQNVu-ImA",
                    "ArtistUrl": "https://youtube.com/channel/UCpR5JmRWGixoWEUQNVu-ImA",
                    "time": "3:39",
                    "second": 219
                },
                {
                    "SongTitle": "旺仔小喬 - 愛的回歸線（原唱：陳韻若、陳每文）『在愛的回歸線 有期待終會有相見，天會晴 心會暖 陽光在手指間。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "i8pm6-bwNiM",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=i8pm6-bwNiM&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=i8pm6-bwNiM&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "3:47",
                    "second": 227
                },
                {
                    "SongTitle": "王貳浪 - 一直很安靜（原唱：阿桑）『給你的愛一直很安靜，明明是三個人的電影，我卻始終不能有姓名。』【動態歌詞MV】",
                    "SongID": "RVcZRGOY60g",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=RVcZRGOY60g&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=RVcZRGOY60g&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "SEEK Music Studio",
                    "ArtistID": "UCMge6Qofn2CIEk8yXpL5pWQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCMge6Qofn2CIEk8yXpL5pWQ",
                    "ArtistUrl": "https://youtube.com/channel/UCMge6Qofn2CIEk8yXpL5pWQ",
                    "time": "3:49",
                    "second": 229
                },
                {
                    "SongTitle": "yihuik苡慧 - 如果可以·2023（原唱：韋禮安）『如果可以我想和你回到那天相遇，讓時間停止那一場雨。』【動態歌詞MV】",
                    "SongID": "Hys1redI8Xc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=Hys1redI8Xc&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=Hys1redI8Xc&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "JN Music",
                    "ArtistID": "UCGpUIgdNw1F3WgTRl4RzPcA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCGpUIgdNw1F3WgTRl4RzPcA",
                    "ArtistUrl": "https://youtube.com/channel/UCGpUIgdNw1F3WgTRl4RzPcA",
                    "time": "3:45",
                    "second": 225
                },
                {
                    "SongTitle": "張天樞  - 遇到（原唱：方雅賢）『我們繞了這麼一圈才遇到 我比誰都更明白你的重要，這麼久了我就決定了 決定了握著你的手我不會放掉。』【動態歌詞MV】",
                    "SongID": "1M8w4aH5yuI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=1M8w4aH5yuI&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=1M8w4aH5yuI&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "YunShang-Music",
                    "ArtistID": "UCrWNEmqwt4iTmqhhI7Caeyw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCrWNEmqwt4iTmqhhI7Caeyw",
                    "ArtistUrl": "https://youtube.com/channel/UCrWNEmqwt4iTmqhhI7Caeyw",
                    "time": "3:17",
                    "second": 197
                },
                {
                    "SongTitle": "要不要買菜 - 紅豆（原唱：王菲）『有時候 有時候 我會相信一切有盡頭，相聚離開 都有時候，沒有什麼會永垂不朽。』【動態歌詞MV】",
                    "SongID": "k3ZzY4tOStI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=k3ZzY4tOStI&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=k3ZzY4tOStI&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "Mousse Music",
                    "ArtistID": "UCkyZslsGezmcoVedVArvqnw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCkyZslsGezmcoVedVArvqnw",
                    "ArtistUrl": "https://youtube.com/channel/UCkyZslsGezmcoVedVArvqnw",
                    "time": "3:25",
                    "second": 205
                },
                {
                    "SongTitle": "煙(許佳豪) - 一直想著他（原唱：莊心妍）『一直還想著他 折磨自己對嗎？他都已經放下 愛上了另一個她。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "jrMUacN1K2c",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=jrMUacN1K2c&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=jrMUacN1K2c&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "4:13",
                    "second": 253
                },
                {
                    "SongTitle": "單依純 - 讓我隨風（《三體》電視劇插曲）『我的心 我的命 都隨風漂蕩去，從此就了無蹤跡。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "gnwRW0xdMO4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=gnwRW0xdMO4&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=gnwRW0xdMO4&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "3:58",
                    "second": 238
                },
                {
                    "SongTitle": "周深 - 永恆孤獨（《三體》電視劇主題曲）『在宇宙懷中 渺小地呼喚浩瀚時空，世界隱隱作痛 剩永恆孤獨。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "LEE6AZlH3Jg",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=LEE6AZlH3Jg&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=LEE6AZlH3Jg&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "5:09",
                    "second": 309
                },
                {
                    "SongTitle": "半噸兄弟 - 天黑黑（原唱：孫燕姿）『我愛上讓我奮不顧身的一個人，我以為這就是我所追求的世界，然而橫衝直撞被誤解被騙。』【動態歌詞MV】",
                    "SongID": "YMSAhTMzwV4",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=YMSAhTMzwV4&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=YMSAhTMzwV4&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "i-Music",
                    "ArtistID": "UC_a9jB1bHxtK2gHBcMgZDqw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC_a9jB1bHxtK2gHBcMgZDqw",
                    "ArtistUrl": "https://youtube.com/channel/UC_a9jB1bHxtK2gHBcMgZDqw",
                    "time": "3:50",
                    "second": 230
                },
                {
                    "SongTitle": "Bell玲惠 - Comethru『And there's one thing that I need from you，Can you come through,through.』【動態歌詞MV】",
                    "SongID": "awcomtEP-XI",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=awcomtEP-XI&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=awcomtEP-XI&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "SOUL. MUSIC",
                    "ArtistID": "UC4E2adU04_ST8N1os77KAxQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC4E2adU04_ST8N1os77KAxQ",
                    "ArtistUrl": "https://youtube.com/channel/UC4E2adU04_ST8N1os77KAxQ",
                    "time": "2:54",
                    "second": 174
                },
                {
                    "SongTitle": "不是花火呀/褚晨茜 - 下個路口再見吧（原唱：李宇春）『平行的畫 DI DI DA，幾時交叉 DI DI DA，下個路口再見吧。』【動態歌詞MV】",
                    "SongID": "PhybvYP2pCQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=PhybvYP2pCQ&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=PhybvYP2pCQ&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "MilkShake Music",
                    "ArtistID": "UC2Cma-jrZV9QV5jx8VHaHXQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC2Cma-jrZV9QV5jx8VHaHXQ",
                    "ArtistUrl": "https://youtube.com/channel/UC2Cma-jrZV9QV5jx8VHaHXQ",
                    "time": "3:09",
                    "second": 189
                },
                {
                    "SongTitle": "姜雲升/劉美麟 - 你消失後『你曾說喜歡大雨 喜歡在屋裡看雨，這城市萬家燈火 全是和你的回憶。』【動態歌詞MV】",
                    "SongID": "IVK6senvqzs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=IVK6senvqzs&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=IVK6senvqzs&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "Panda Music",
                    "ArtistID": "UC56u_5CV7XirXp2H2VwGQTQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC56u_5CV7XirXp2H2VwGQTQ",
                    "ArtistUrl": "https://youtube.com/channel/UC56u_5CV7XirXp2H2VwGQTQ",
                    "time": "4:34",
                    "second": 274
                },
                {
                    "SongTitle": "劉思鑒 - 下不完的雨『愛是下不完的雨 讓人破碎讓人著迷，雨點訴說著過去 為什麼我感覺不到熟悉。』【動態歌詞/Vietsub/Pinyin Lyrics】",
                    "SongID": "BfGwXeZ7i5w",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=BfGwXeZ7i5w&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=BfGwXeZ7i5w&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "2:15",
                    "second": 135
                },
                {
                    "SongTitle": "歐陽耀瑩 - 戒不掉（原聲版）『誰從屏幕裡看從前，而誰停下企我門前，猶如是十八歲的青年很討厭。』【動態歌詞/Vietsub/粵語歌】",
                    "SongID": "U7vNhWhnZEQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=U7vNhWhnZEQ&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=U7vNhWhnZEQ&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "3:07",
                    "second": 187
                },
                {
                    "SongTitle": "傅夢彤 - 引力陷阱『連呼吸也會來不及 不小心 落入你的引力陷阱，無止盡的回憶 被拉進失眠的銀河系。』【動態歌詞MV】",
                    "SongID": "F1l5lNA7pv8",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=F1l5lNA7pv8&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=F1l5lNA7pv8&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "SEEK Music Studio",
                    "ArtistID": "UCMge6Qofn2CIEk8yXpL5pWQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCMge6Qofn2CIEk8yXpL5pWQ",
                    "ArtistUrl": "https://youtube.com/channel/UCMge6Qofn2CIEk8yXpL5pWQ",
                    "time": "3:13",
                    "second": 193
                },
                {
                    "SongTitle": "劉大拿 - 不分手的戀愛（原唱：汪蘇瀧）『你的愛被埋葬 恨被收藏，痛應該原諒，我的愛不用講 恨不用想，思念在發燙。』【動態歌詞MV】",
                    "SongID": "JQahWp5puJQ",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=JQahWp5puJQ&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=JQahWp5puJQ&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "EHPMusicChannel",
                    "ArtistID": "UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "ArtistUrl": "https://youtube.com/channel/UC345x_D7DgK5313D3ftM_EQ",
                    "time": "3:06",
                    "second": 186
                },
                {
                    "SongTitle": "是你的垚 - 魚仔（原唱：盧廣仲）『我需要你 需要你 需要你陪伴我，好想要你 想要你 想要你陪著我。』【動態歌詞MV】",
                    "SongID": "B-m1zmIhtx0",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=B-m1zmIhtx0&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=B-m1zmIhtx0&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "YunShang-Music",
                    "ArtistID": "UCrWNEmqwt4iTmqhhI7Caeyw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCrWNEmqwt4iTmqhhI7Caeyw",
                    "ArtistUrl": "https://youtube.com/channel/UCrWNEmqwt4iTmqhhI7Caeyw",
                    "time": "5:08",
                    "second": 308
                },
                {
                    "SongTitle": "林寶馨 - 沉醉的青絲『如果回憶容易 我會想你念你，假裝你在這裡，那本舊的日曆 翻了日期，告訴我牢記不容易。』【動態歌詞MV】",
                    "SongID": "2R8od2ifA_M",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=2R8od2ifA_M&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=2R8od2ifA_M&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "Mousse Music",
                    "ArtistID": "UCkyZslsGezmcoVedVArvqnw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCkyZslsGezmcoVedVArvqnw",
                    "ArtistUrl": "https://youtube.com/channel/UCkyZslsGezmcoVedVArvqnw",
                    "time": "3:42",
                    "second": 222
                },
                {
                    "SongTitle": "王雨桐 - 塵埃（原唱：家家）『我的愛像塵埃 散落在邊疆地帶，不再對誰期待 難道是一種自由自在。』【動態歌詞MV】",
                    "SongID": "9eiM-HxSSDc",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=9eiM-HxSSDc&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=9eiM-HxSSDc&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "i-Music",
                    "ArtistID": "UC_a9jB1bHxtK2gHBcMgZDqw",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC_a9jB1bHxtK2gHBcMgZDqw",
                    "ArtistUrl": "https://youtube.com/channel/UC_a9jB1bHxtK2gHBcMgZDqw",
                    "time": "4:04",
                    "second": 244
                },
                {
                    "SongTitle": "王巨星 - 給我一個理由忘記（原唱：A-Lin）『有些愛越想抽離 卻越更清晰，那最痛的距離 是你不在身邊卻在我的心裡。』【動態歌詞MV】",
                    "SongID": "8COxlyYO9fs",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=8COxlyYO9fs&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=8COxlyYO9fs&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "JN Music",
                    "ArtistID": "UCGpUIgdNw1F3WgTRl4RzPcA",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UCGpUIgdNw1F3WgTRl4RzPcA",
                    "ArtistUrl": "https://youtube.com/channel/UCGpUIgdNw1F3WgTRl4RzPcA",
                    "time": "4:22",
                    "second": 262
                },
                {
                    "SongTitle": "陳子晴 - 偏向『我嫌棄你的偏向 瞎話編得冠冕堂皇，掩飾不了你做的假象 像被隱形繩子捆綁 逞著強。』【動態歌詞MV】",
                    "SongID": "HI2qM7mlkyA",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=HI2qM7mlkyA&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=HI2qM7mlkyA&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "SOUL. MUSIC",
                    "ArtistID": "UC4E2adU04_ST8N1os77KAxQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC4E2adU04_ST8N1os77KAxQ",
                    "ArtistUrl": "https://youtube.com/channel/UC4E2adU04_ST8N1os77KAxQ",
                    "time": "3:07",
                    "second": 187
                },
                {
                    "SongTitle": "楊胖雨 - 窒息『本來都愛著愛著愛到都快要窒息，可不知為何你卻突然就離我遠去。』【動態歌詞MV】",
                    "SongID": "BuP-PQp40Ic",
                    "SongMusicUrl": "https://music.youtube.com/watch?v=BuP-PQp40Ic&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "SongUrl": "https://youtube.com/watch?v=BuP-PQp40Ic&list=PLtAw-mgfCzRwduBTjBHknz5U4_ZM4n6qm",
                    "Artist": "MilkShake Music",
                    "ArtistID": "UC2Cma-jrZV9QV5jx8VHaHXQ",
                    "ArtistMusicUrl": "https://music.youtube.com/channel/UC2Cma-jrZV9QV5jx8VHaHXQ",
                    "ArtistUrl": "https://youtube.com/channel/UC2Cma-jrZV9QV5jx8VHaHXQ",
                    "time": "3:21",
                    "second": 201
                }
            ]
        }
    ]
    return { data };
});
